//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Address represents an IPv4 or IPv6 IP address.
internal struct Address: Sendable, Content, Hashable {

    /** IP address. */
    internal var addr: String?
    /** Mask length of the IP address. */
    internal var prefixLen: Int?

    internal init(addr: String? = nil, prefixLen: Int? = nil) {
        self.addr = addr
        self.prefixLen = prefixLen
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case addr = "Addr"
        case prefixLen = "PrefixLen"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(addr, forKey: .addr)
        try keyedContainer.encodeIfPresent(prefixLen, forKey: .prefixLen)
    }
}
