//
// AuthConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct AuthConfig: Sendable, Content, Hashable {

    internal var username: String?
    internal var password: String?
    /** Email is an optional value associated with the username.  > **Deprecated**: This field is deprecated since docker 1.11 (API v1.23) and will be removed in a future release.  */
    internal var email: String?
    internal var serveraddress: String?

    internal init(username: String? = nil, password: String? = nil, email: String? = nil, serveraddress: String? = nil) {
        self.username = username
        self.password = password
        self.email = email
        self.serveraddress = serveraddress
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
        case email
        case serveraddress
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(username, forKey: .username)
        try keyedContainer.encodeIfPresent(password, forKey: .password)
        try keyedContainer.encodeIfPresent(email, forKey: .email)
        try keyedContainer.encodeIfPresent(serveraddress, forKey: .serveraddress)
    }
}
