//
// BuildCache.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// BuildCache contains information about a build cache record.
internal struct BuildCache: Sendable, Content, Hashable {

    internal enum ModelType: String, Sendable, Content, Hashable, CaseIterable {
        case `internal` = "internal"
        case frontend = "frontend"
        case sourcePeriodLocal = "source.local"
        case sourcePeriodGitPeriodCheckout = "source.git.checkout"
        case execPeriodCachemount = "exec.cachemount"
        case regular = "regular"
    }
    /** Unique ID of the build cache record.  */
    internal var ID: String?
    /** List of parent build cache record IDs.  */
    internal var parents: [String]?
    /** Cache record type.  */
    internal var type: ModelType?
    /** Description of the build-step that produced the build cache.  */
    internal var description: String?
    /** Indicates if the build cache is in use.  */
    internal var inUse: Bool?
    /** Indicates if the build cache is shared.  */
    internal var shared: Bool?
    /** Amount of disk space used by the build cache (in bytes).  */
    internal var size: Int?
    /** Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var createdAt: String?
    /** Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var lastUsedAt: String?
    internal var usageCount: Int?

    internal init(
        ID: String? = nil, parents: [String]? = nil, type: ModelType? = nil, description: String? = nil, inUse: Bool? = nil, shared: Bool? = nil, size: Int? = nil,
        createdAt: String? = nil, lastUsedAt: String? = nil, usageCount: Int? = nil
    ) {
        self.ID = ID
        self.parents = parents
        self.type = type
        self.description = description
        self.inUse = inUse
        self.shared = shared
        self.size = size
        self.createdAt = createdAt
        self.lastUsedAt = lastUsedAt
        self.usageCount = usageCount
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case parents = "Parents"
        case type = "Type"
        case description = "Description"
        case inUse = "InUse"
        case shared = "Shared"
        case size = "Size"
        case createdAt = "CreatedAt"
        case lastUsedAt = "LastUsedAt"
        case usageCount = "UsageCount"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(parents, forKey: .parents)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(description, forKey: .description)
        try keyedContainer.encodeIfPresent(inUse, forKey: .inUse)
        try keyedContainer.encodeIfPresent(shared, forKey: .shared)
        try keyedContainer.encodeIfPresent(size, forKey: .size)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try keyedContainer.encodeIfPresent(usageCount, forKey: .usageCount)
    }
}
