//
// BuildPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct BuildPruneResponse: Sendable, Content, Hashable {

    internal var cachesDeleted: [String]?
    /** Disk space reclaimed in bytes */
    internal var spaceReclaimed: Int64?

    internal init(cachesDeleted: [String]? = nil, spaceReclaimed: Int64? = nil) {
        self.cachesDeleted = cachesDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cachesDeleted = "CachesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(cachesDeleted, forKey: .cachesDeleted)
        try keyedContainer.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}
