//
// BuildInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct BuildInfo: Sendable, Content, Hashable {

    internal var id: String?
    internal var stream: String?
    /** errors encountered during the operation.   > **Deprecated**: This field is deprecated since API v1.4, and will be omitted in a future API version. Use the information in errorDetail instead. */
    internal var error: String?
    internal var errorDetail: ErrorDetail?
    internal var status: String?
    /** Progress is a pre-formatted presentation of progressDetail.   > **Deprecated**: This field is deprecated since API v1.8, and will be omitted in a future API version. Use the information in progressDetail instead. */
    internal var progress: String?
    internal var progressDetail: ProgressDetail?
    internal var aux: ImageID?

    internal init(
        id: String? = nil, stream: String? = nil, error: String? = nil, errorDetail: ErrorDetail? = nil, status: String? = nil, progress: String? = nil,
        progressDetail: ProgressDetail? = nil, aux: ImageID? = nil
    ) {
        self.id = id
        self.stream = stream
        self.error = error
        self.errorDetail = errorDetail
        self.status = status
        self.progress = progress
        self.progressDetail = progressDetail
        self.aux = aux
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case stream
        case error
        case errorDetail
        case status
        case progress
        case progressDetail
        case aux
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(stream, forKey: .stream)
        try keyedContainer.encodeIfPresent(error, forKey: .error)
        try keyedContainer.encodeIfPresent(errorDetail, forKey: .errorDetail)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
        try keyedContainer.encodeIfPresent(progress, forKey: .progress)
        try keyedContainer.encodeIfPresent(progressDetail, forKey: .progressDetail)
        try keyedContainer.encodeIfPresent(aux, forKey: .aux)
    }
}

extension BuildInfo: Identifiable {}
