//
// ChangeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Kind of change  Can be one of:  - &#x60;0&#x60;: Modified (\&quot;C\&quot;) - &#x60;1&#x60;: Added (\&quot;A\&quot;) - &#x60;2&#x60;: Deleted (\&quot;D\&quot;)
internal enum ChangeType: Int, Sendable, Content, Hashable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
