//
// ClusterVolumeSpecAccessModeSecretsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// One cluster volume secret entry. Defines a key-value pair that is passed to the plugin.
internal struct ClusterVolumeSpecAccessModeSecretsInner: Sendable, Content, Hashable {

    /** Key is the name of the key of the key-value pair passed to the plugin.  */
    internal var key: String?
    /** Secret is the swarm Secret object from which to read data. This can be a Secret name or ID. The Secret data is retrieved by swarm and used as the value of the key-value pair passed to the plugin.  */
    internal var secret: String?

    internal init(key: String? = nil, secret: String? = nil) {
        self.key = key
        self.secret = secret
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case key = "Key"
        case secret = "Secret"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(key, forKey: .key)
        try keyedContainer.encodeIfPresent(secret, forKey: .secret)
    }
}
