//
// ClusterVolumeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about the global status of the volume.
internal struct ClusterVolumeInfo: Sendable, Content, Hashable {

    /** The capacity of the volume in bytes. A value of 0 indicates that the capacity is unknown.  */
    internal var capacityBytes: Int64?
    /** A map of strings to strings returned from the storage plugin when the volume is created.  */
    internal var volumeContext: [String: String]?
    /** The ID of the volume as returned by the CSI storage plugin. This is distinct from the volume's ID as provided by Docker. This ID is never used by the user when communicating with Docker to refer to this volume. If the ID is blank, then the Volume has not been successfully created in the plugin yet.  */
    internal var volumeID: String?
    /** The topology this volume is actually accessible from.  */
    internal var accessibleTopology: [Topology]?

    internal init(capacityBytes: Int64? = nil, volumeContext: [String: String]? = nil, volumeID: String? = nil, accessibleTopology: [Topology]? = nil) {
        self.capacityBytes = capacityBytes
        self.volumeContext = volumeContext
        self.volumeID = volumeID
        self.accessibleTopology = accessibleTopology
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case capacityBytes = "CapacityBytes"
        case volumeContext = "VolumeContext"
        case volumeID = "VolumeID"
        case accessibleTopology = "AccessibleTopology"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(capacityBytes, forKey: .capacityBytes)
        try keyedContainer.encodeIfPresent(volumeContext, forKey: .volumeContext)
        try keyedContainer.encodeIfPresent(volumeID, forKey: .volumeID)
        try keyedContainer.encodeIfPresent(accessibleTopology, forKey: .accessibleTopology)
    }
}
