//
// ClusterVolume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Options and information specific to, and only present on, Swarm CSI cluster volumes.
internal struct ClusterVolume: Sendable, Content, Hashable {

    /** The Swarm ID of this volume. Because cluster volumes are Swarm objects, they have an ID, unlike non-cluster volumes. This ID can be used to refer to the Volume instead of the name.  */
    internal var ID: String?
    internal var version: ObjectVersion?
    internal var createdAt: String?
    internal var updatedAt: String?
    internal var spec: ClusterVolumeSpec?
    internal var info: ClusterVolumeInfo?
    /** The status of the volume as it pertains to its publishing and use on specific nodes  */
    internal var publishStatus: [ClusterVolumePublishStatusInner]?

    internal init(
        ID: String? = nil, version: ObjectVersion? = nil, createdAt: String? = nil, updatedAt: String? = nil, spec: ClusterVolumeSpec? = nil, info: ClusterVolumeInfo? = nil,
        publishStatus: [ClusterVolumePublishStatusInner]? = nil
    ) {
        self.ID = ID
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.spec = spec
        self.info = info
        self.publishStatus = publishStatus
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case version = "Version"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case spec = "Spec"
        case info = "Info"
        case publishStatus = "PublishStatus"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
        try keyedContainer.encodeIfPresent(info, forKey: .info)
        try keyedContainer.encodeIfPresent(publishStatus, forKey: .publishStatus)
    }
}
