//
// ClusterVolumeSpecAccessModeAccessibilityRequirements.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Requirements for the accessible topology of the volume. These fields are optional. For an in-depth description of what these fields mean, see the CSI specification.
internal struct ClusterVolumeSpecAccessModeAccessibilityRequirements: Sendable, Content, Hashable {

    /** A list of required topologies, at least one of which the volume must be accessible from.  */
    internal var requisite: [Topology]?
    /** A list of topologies that the volume should attempt to be provisioned in.  */
    internal var preferred: [Topology]?

    internal init(requisite: [Topology]? = nil, preferred: [Topology]? = nil) {
        self.requisite = requisite
        self.preferred = preferred
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requisite = "Requisite"
        case preferred = "Preferred"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(requisite, forKey: .requisite)
        try keyedContainer.encodeIfPresent(preferred, forKey: .preferred)
    }
}
