//
// ClusterVolumeSpecAccessModeCapacityRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The desired capacity that the volume should be created with. If empty, the plugin will decide the capacity.
internal struct ClusterVolumeSpecAccessModeCapacityRange: Sendable, Content, Hashable {

    /** The volume must be at least this big. The value of 0 indicates an unspecified minimum  */
    internal var requiredBytes: Int64?
    /** The volume must not be bigger than this. The value of 0 indicates an unspecified maximum.  */
    internal var limitBytes: Int64?

    internal init(requiredBytes: Int64? = nil, limitBytes: Int64? = nil) {
        self.requiredBytes = requiredBytes
        self.limitBytes = limitBytes
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case requiredBytes = "RequiredBytes"
        case limitBytes = "LimitBytes"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(requiredBytes, forKey: .requiredBytes)
        try keyedContainer.encodeIfPresent(limitBytes, forKey: .limitBytes)
    }
}
