//
// ClusterInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// ClusterInfo represents information about the swarm as is returned by the \&quot;/info\&quot; endpoint. Join-tokens are not included.
internal struct ClusterInfo: Sendable, Content, Hashable {

    /** The ID of the swarm. */
    internal var ID: String?
    internal var version: ObjectVersion?
    /** Date and time at which the swarm was initialised in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var createdAt: String?
    /** Date and time at which the swarm was last updated in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var updatedAt: String?
    internal var spec: SwarmSpec?
    internal var tLSInfo: TLSInfo?
    /** Whether there is currently a root CA rotation in progress for the swarm  */
    internal var rootRotationInProgress: Bool?
    /** DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. If no port is set or is set to 0, the default port (4789) is used.  */
    internal var dataPathPort: Int?
    /** Default Address Pool specifies default subnet pools for global scope networks.  */
    internal var defaultAddrPool: [String]?
    /** SubnetSize specifies the subnet size of the networks created from the default subnet pool.  */
    internal var subnetSize: Int?

    internal init(
        ID: String? = nil, version: ObjectVersion? = nil, createdAt: String? = nil, updatedAt: String? = nil, spec: SwarmSpec? = nil, tLSInfo: TLSInfo? = nil,
        rootRotationInProgress: Bool? = nil, dataPathPort: Int? = nil, defaultAddrPool: [String]? = nil, subnetSize: Int? = nil
    ) {
        self.ID = ID
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.spec = spec
        self.tLSInfo = tLSInfo
        self.rootRotationInProgress = rootRotationInProgress
        self.dataPathPort = dataPathPort
        self.defaultAddrPool = defaultAddrPool
        self.subnetSize = subnetSize
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case version = "Version"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case spec = "Spec"
        case tLSInfo = "TLSInfo"
        case rootRotationInProgress = "RootRotationInProgress"
        case dataPathPort = "DataPathPort"
        case defaultAddrPool = "DefaultAddrPool"
        case subnetSize = "SubnetSize"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
        try keyedContainer.encodeIfPresent(tLSInfo, forKey: .tLSInfo)
        try keyedContainer.encodeIfPresent(rootRotationInProgress, forKey: .rootRotationInProgress)
        try keyedContainer.encodeIfPresent(dataPathPort, forKey: .dataPathPort)
        try keyedContainer.encodeIfPresent(defaultAddrPool, forKey: .defaultAddrPool)
        try keyedContainer.encodeIfPresent(subnetSize, forKey: .subnetSize)
    }
}
