//
// ClusterVolumeSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Cluster-specific options used to create the volume.
internal struct ClusterVolumeSpec: Sendable, Content, Hashable {

    /** Group defines the volume group of this volume. Volumes belonging to the same group can be referred to by group name when creating Services.  Referring to a volume by group instructs Swarm to treat volumes in that group interchangeably for the purpose of scheduling. Volumes with an empty string for a group technically all belong to the same, emptystring group.  */
    internal var group: String?
    internal var accessMode: ClusterVolumeSpecAccessMode?

    internal init(group: String? = nil, accessMode: ClusterVolumeSpecAccessMode? = nil) {
        self.group = group
        self.accessMode = accessMode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case group = "Group"
        case accessMode = "AccessMode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(group, forKey: .group)
        try keyedContainer.encodeIfPresent(accessMode, forKey: .accessMode)
    }
}
