//
// Commit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as &#x60;containerd&#x60;, or &#x60;runC&#x60;.
internal struct Commit: Sendable, Content, Hashable {

    /** Actual commit ID of external tool. */
    internal var ID: String?

    internal init(ID: String? = nil) {
        self.ID = ID
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
    }
}
