//
// ConfigSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ConfigSpec: Sendable, Content, Hashable {

    /** User-defined name of the config. */
    internal var name: String?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** Data is the data to store as a config, formatted as a standard base64-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-4)) string. The maximum allowed size is 1000KB, as defined in [MaxConfigSize](https://pkg.go.dev/github.com/moby/swarmkit/v2@v2.0.0-20250103191802-8c1959736554/manager/controlapi#MaxConfigSize).  */
    internal var data: String?
    internal var templating: Driver?

    internal init(name: String? = nil, labels: [String: String]? = nil, data: String? = nil, templating: Driver? = nil) {
        self.name = name
        self.labels = labels
        self.data = data
        self.templating = templating
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case labels = "Labels"
        case data = "Data"
        case templating = "Templating"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(data, forKey: .data)
        try keyedContainer.encodeIfPresent(templating, forKey: .templating)
    }
}
