//
// ConfigReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The config-only network source to provide the configuration for this network.
internal struct ConfigReference: Sendable, Content, Hashable {

    /** The name of the config-only network that provides the network's configuration. The specified network must be an existing config-only network. Only network names are allowed, not network IDs.  */
    internal var network: String?

    internal init(network: String? = nil) {
        self.network = network
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case network = "Network"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(network, forKey: .network)
    }
}
