//
// ContainerStatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Statistics sample for a container.
internal struct ContainerStatsResponse: Sendable, Content, Hashable {

    /** Name of the container */
    internal var name: String?
    /** ID of the container */
    internal var id: String?
    /** Date and time at which this sample was collected. The value is formatted as [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) with nano-seconds.  */
    internal var read: Date?
    /** Date and time at which this first sample was collected. This field is not propagated if the \"one-shot\" option is set. If the \"one-shot\" option is set, this field may be omitted, empty, or set to a default date (`0001-01-01T00:00:00Z`).  The value is formatted as [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) with nano-seconds.  */
    internal var preread: Date?
    internal var pidsStats: ContainerPidsStats?
    internal var blkioStats: ContainerBlkioStats?
    /** The number of processors on the system.  This field is Windows-specific and always zero for Linux containers.  */
    internal var numProcs: Int?
    internal var storageStats: ContainerStorageStats?
    internal var cpuStats: ContainerCPUStats?
    internal var precpuStats: ContainerCPUStats?
    internal var memoryStats: ContainerMemoryStats?
    /** Network statistics for the container per interface.  This field is omitted if the container has no networking enabled.  */
    internal var networks: JSONValue?

    internal init(
        name: String? = nil, id: String? = nil, read: Date? = nil, preread: Date? = nil, pidsStats: ContainerPidsStats? = nil, blkioStats: ContainerBlkioStats? = nil,
        numProcs: Int? = nil, storageStats: ContainerStorageStats? = nil, cpuStats: ContainerCPUStats? = nil, precpuStats: ContainerCPUStats? = nil,
        memoryStats: ContainerMemoryStats? = nil, networks: JSONValue? = nil
    ) {
        self.name = name
        self.id = id
        self.read = read
        self.preread = preread
        self.pidsStats = pidsStats
        self.blkioStats = blkioStats
        self.numProcs = numProcs
        self.storageStats = storageStats
        self.cpuStats = cpuStats
        self.precpuStats = precpuStats
        self.memoryStats = memoryStats
        self.networks = networks
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case id
        case read
        case preread
        case pidsStats = "pids_stats"
        case blkioStats = "blkio_stats"
        case numProcs = "num_procs"
        case storageStats = "storage_stats"
        case cpuStats = "cpu_stats"
        case precpuStats = "precpu_stats"
        case memoryStats = "memory_stats"
        case networks
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(read, forKey: .read)
        try keyedContainer.encodeIfPresent(preread, forKey: .preread)
        try keyedContainer.encodeIfPresent(pidsStats, forKey: .pidsStats)
        try keyedContainer.encodeIfPresent(blkioStats, forKey: .blkioStats)
        try keyedContainer.encodeIfPresent(numProcs, forKey: .numProcs)
        try keyedContainer.encodeIfPresent(storageStats, forKey: .storageStats)
        try keyedContainer.encodeIfPresent(cpuStats, forKey: .cpuStats)
        try keyedContainer.encodeIfPresent(precpuStats, forKey: .precpuStats)
        try keyedContainer.encodeIfPresent(memoryStats, forKey: .memoryStats)
        try keyedContainer.encodeIfPresent(networks, forKey: .networks)
    }
}

extension ContainerStatsResponse: Identifiable {}
