//
// ContainerNetworkStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Aggregates the network stats of one container
internal struct ContainerNetworkStats: Sendable, Content, Hashable {

    /** Bytes received. Windows and Linux.  */
    internal var rxBytes: Int?
    /** Packets received. Windows and Linux.  */
    internal var rxPackets: Int?
    /** Received errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.  */
    internal var rxErrors: Int?
    /** Incoming packets dropped. Windows and Linux.  */
    internal var rxDropped: Int?
    /** Bytes sent. Windows and Linux.  */
    internal var txBytes: Int?
    /** Packets sent. Windows and Linux.  */
    internal var txPackets: Int?
    /** Sent errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.  */
    internal var txErrors: Int?
    /** Outgoing packets dropped. Windows and Linux.  */
    internal var txDropped: Int?
    /** Endpoint ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.  */
    internal var endpointId: String?
    /** Instance ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.  */
    internal var instanceId: String?

    internal init(
        rxBytes: Int? = nil, rxPackets: Int? = nil, rxErrors: Int? = nil, rxDropped: Int? = nil, txBytes: Int? = nil, txPackets: Int? = nil, txErrors: Int? = nil,
        txDropped: Int? = nil, endpointId: String? = nil, instanceId: String? = nil
    ) {
        self.rxBytes = rxBytes
        self.rxPackets = rxPackets
        self.rxErrors = rxErrors
        self.rxDropped = rxDropped
        self.txBytes = txBytes
        self.txPackets = txPackets
        self.txErrors = txErrors
        self.txDropped = txDropped
        self.endpointId = endpointId
        self.instanceId = instanceId
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case rxBytes = "rx_bytes"
        case rxPackets = "rx_packets"
        case rxErrors = "rx_errors"
        case rxDropped = "rx_dropped"
        case txBytes = "tx_bytes"
        case txPackets = "tx_packets"
        case txErrors = "tx_errors"
        case txDropped = "tx_dropped"
        case endpointId = "endpoint_id"
        case instanceId = "instance_id"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(rxBytes, forKey: .rxBytes)
        try keyedContainer.encodeIfPresent(rxPackets, forKey: .rxPackets)
        try keyedContainer.encodeIfPresent(rxErrors, forKey: .rxErrors)
        try keyedContainer.encodeIfPresent(rxDropped, forKey: .rxDropped)
        try keyedContainer.encodeIfPresent(txBytes, forKey: .txBytes)
        try keyedContainer.encodeIfPresent(txPackets, forKey: .txPackets)
        try keyedContainer.encodeIfPresent(txErrors, forKey: .txErrors)
        try keyedContainer.encodeIfPresent(txDropped, forKey: .txDropped)
        try keyedContainer.encodeIfPresent(endpointId, forKey: .endpointId)
        try keyedContainer.encodeIfPresent(instanceId, forKey: .instanceId)
    }
}
