//
// ContainerInspectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ContainerInspectResponse: Sendable, Content, Hashable {

    /** The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes). */
    internal var id: String?
    /** Date and time at which the container was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds. */
    internal var created: String?
    /** The path to the command being run */
    internal var path: String?
    /** The arguments to the command being run */
    internal var args: [String]?
    internal var state: ContainerState?
    /** The ID (digest) of the image that this container was created from. */
    internal var image: String?
    /** Location of the `/etc/resolv.conf` generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools. */
    internal var resolvConfPath: String?
    /** Location of the `/etc/hostname` generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools. */
    internal var hostnamePath: String?
    /** Location of the `/etc/hosts` generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools. */
    internal var hostsPath: String?
    /** Location of the file used to buffer the container's logs. Depending on the logging-driver used for the container, this field may be omitted.  This file is managed through the docker daemon, and should not be accessed or modified by other tools. */
    internal var logPath: String?
    /** The name associated with this container.  For historic reasons, the name may be prefixed with a forward-slash (`/`). */
    internal var name: String?
    /** Number of times the container was restarted since it was created, or since daemon was started. */
    internal var restartCount: Int?
    /** The storage-driver used for the container's filesystem (graph-driver or snapshotter). */
    internal var driver: String?
    /** The platform (operating system) for which the container was created.  This field was introduced for the experimental \"LCOW\" (Linux Containers On Windows) features, which has been removed. In most cases, this field is equal to the host's operating system (`linux` or `windows`). */
    internal var platform: String?
    internal var imageManifestDescriptor: OCIDescriptor?
    /** SELinux mount label set for the container. */
    internal var mountLabel: String?
    /** SELinux process label set for the container. */
    internal var processLabel: String?
    /** The AppArmor profile set for the container. */
    internal var appArmorProfile: String?
    /** IDs of exec instances that are running in the container. */
    internal var execIDs: [String]?
    internal var hostConfig: HostConfig?
    internal var graphDriver: DriverData?
    /** The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request. */
    internal var sizeRw: Int64?
    /** The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request. */
    internal var sizeRootFs: Int64?
    /** List of mounts used by the container. */
    internal var mounts: [MountPoint]?
    internal var config: ContainerConfig?
    internal var networkSettings: NetworkSettings?

    internal init(
        id: String? = nil, created: String? = nil, path: String? = nil, args: [String]? = nil, state: ContainerState? = nil, image: String? = nil, resolvConfPath: String? = nil,
        hostnamePath: String? = nil, hostsPath: String? = nil, logPath: String? = nil, name: String? = nil, restartCount: Int? = nil, driver: String? = nil,
        platform: String? = nil, imageManifestDescriptor: OCIDescriptor? = nil, mountLabel: String? = nil, processLabel: String? = nil, appArmorProfile: String? = nil,
        execIDs: [String]? = nil, hostConfig: HostConfig? = nil, graphDriver: DriverData? = nil, sizeRw: Int64? = nil, sizeRootFs: Int64? = nil, mounts: [MountPoint]? = nil,
        config: ContainerConfig? = nil, networkSettings: NetworkSettings? = nil
    ) {
        self.id = id
        self.created = created
        self.path = path
        self.args = args
        self.state = state
        self.image = image
        self.resolvConfPath = resolvConfPath
        self.hostnamePath = hostnamePath
        self.hostsPath = hostsPath
        self.logPath = logPath
        self.name = name
        self.restartCount = restartCount
        self.driver = driver
        self.platform = platform
        self.imageManifestDescriptor = imageManifestDescriptor
        self.mountLabel = mountLabel
        self.processLabel = processLabel
        self.appArmorProfile = appArmorProfile
        self.execIDs = execIDs
        self.hostConfig = hostConfig
        self.graphDriver = graphDriver
        self.sizeRw = sizeRw
        self.sizeRootFs = sizeRootFs
        self.mounts = mounts
        self.config = config
        self.networkSettings = networkSettings
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case created = "Created"
        case path = "Path"
        case args = "Args"
        case state = "State"
        case image = "Image"
        case resolvConfPath = "ResolvConfPath"
        case hostnamePath = "HostnamePath"
        case hostsPath = "HostsPath"
        case logPath = "LogPath"
        case name = "Name"
        case restartCount = "RestartCount"
        case driver = "Driver"
        case platform = "Platform"
        case imageManifestDescriptor = "ImageManifestDescriptor"
        case mountLabel = "MountLabel"
        case processLabel = "ProcessLabel"
        case appArmorProfile = "AppArmorProfile"
        case execIDs = "ExecIDs"
        case hostConfig = "HostConfig"
        case graphDriver = "GraphDriver"
        case sizeRw = "SizeRw"
        case sizeRootFs = "SizeRootFs"
        case mounts = "Mounts"
        case config = "Config"
        case networkSettings = "NetworkSettings"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(created, forKey: .created)
        try keyedContainer.encodeIfPresent(path, forKey: .path)
        try keyedContainer.encodeIfPresent(args, forKey: .args)
        try keyedContainer.encodeIfPresent(state, forKey: .state)
        try keyedContainer.encodeIfPresent(image, forKey: .image)
        try keyedContainer.encodeIfPresent(resolvConfPath, forKey: .resolvConfPath)
        try keyedContainer.encodeIfPresent(hostnamePath, forKey: .hostnamePath)
        try keyedContainer.encodeIfPresent(hostsPath, forKey: .hostsPath)
        try keyedContainer.encodeIfPresent(logPath, forKey: .logPath)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(restartCount, forKey: .restartCount)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(platform, forKey: .platform)
        try keyedContainer.encodeIfPresent(imageManifestDescriptor, forKey: .imageManifestDescriptor)
        try keyedContainer.encodeIfPresent(mountLabel, forKey: .mountLabel)
        try keyedContainer.encodeIfPresent(processLabel, forKey: .processLabel)
        try keyedContainer.encodeIfPresent(appArmorProfile, forKey: .appArmorProfile)
        try keyedContainer.encodeIfPresent(execIDs, forKey: .execIDs)
        try keyedContainer.encodeIfPresent(hostConfig, forKey: .hostConfig)
        try keyedContainer.encodeIfPresent(graphDriver, forKey: .graphDriver)
        try keyedContainer.encodeIfPresent(sizeRw, forKey: .sizeRw)
        try keyedContainer.encodeIfPresent(sizeRootFs, forKey: .sizeRootFs)
        try keyedContainer.encodeIfPresent(mounts, forKey: .mounts)
        try keyedContainer.encodeIfPresent(config, forKey: .config)
        try keyedContainer.encodeIfPresent(networkSettings, forKey: .networkSettings)
    }
}
