//
// ContainerWaitExitError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// container waiting error, if any
internal struct ContainerWaitExitError: Sendable, Content, Hashable {

    /** Details of an error */
    internal var message: String?

    internal init(message: String? = nil) {
        self.message = message
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case message = "Message"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(message, forKey: .message)
    }
}
