//
// ContainerSummaryNetworkSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Summary of the container&#39;s network settings
internal struct ContainerSummaryNetworkSettings: Sendable, Content, Hashable {

    /** Summary of network-settings for each network the container is attached to. */
    internal var networks: [String: EndpointSettings]?

    internal init(networks: [String: EndpointSettings]? = nil) {
        self.networks = networks
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case networks = "Networks"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(networks, forKey: .networks)
    }
}
