//
// ContainerBlkioStatEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Blkio stats entry.  This type is Linux-specific and omitted for Windows containers.
internal struct ContainerBlkioStatEntry: Sendable, Content, Hashable {

    internal var major: Int?
    internal var minor: Int?
    internal var op: String?
    internal var value: Int?

    internal init(major: Int? = nil, minor: Int? = nil, op: String? = nil, value: Int? = nil) {
        self.major = major
        self.minor = minor
        self.op = op
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case major
        case minor
        case op
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(major, forKey: .major)
        try keyedContainer.encodeIfPresent(minor, forKey: .minor)
        try keyedContainer.encodeIfPresent(op, forKey: .op)
        try keyedContainer.encodeIfPresent(value, forKey: .value)
    }
}
