//
// ContainerCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// OK response to ContainerCreate operation
internal struct ContainerCreateResponse: Sendable, Content, Hashable {

    /** The ID of the created container */
    internal var id: String
    /** Warnings encountered when creating the container */
    internal var warnings: [String]

    internal init(id: String, warnings: [String]) {
        self.id = id
        self.warnings = warnings
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(id, forKey: .id)
        try keyedContainer.encode(warnings, forKey: .warnings)
    }
}
