//
// ContainerdInfoNamespaces.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The namespaces that the daemon uses for running containers and plugins in containerd. These namespaces can be configured in the daemon configuration, and are considered to be used exclusively by the daemon, Tampering with the containerd instance may cause unexpected behavior.  As these namespaces are considered to be exclusively accessed by the daemon, it is not recommended to change these values, or to change them to a value that is used by other systems, such as cri-containerd.
internal struct ContainerdInfoNamespaces: Sendable, Content, Hashable {

    /** The default containerd namespace used for containers managed by the daemon.  The default namespace for containers is \"moby\", but will be suffixed with the `<uid>.<gid>` of the remapped `root` if user-namespaces are enabled and the containerd image-store is used.  */
    internal var containers: String? = "moby"
    /** The default containerd namespace used for plugins managed by the daemon.  The default namespace for plugins is \"plugins.moby\", but will be suffixed with the `<uid>.<gid>` of the remapped `root` if user-namespaces are enabled and the containerd image-store is used.  */
    internal var plugins: String? = "plugins.moby"

    internal init(containers: String? = "moby", plugins: String? = "plugins.moby") {
        self.containers = containers
        self.plugins = plugins
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case containers = "Containers"
        case plugins = "Plugins"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(containers, forKey: .containers)
        try keyedContainer.encodeIfPresent(plugins, forKey: .plugins)
    }
}
