//
// ContainerCPUStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// CPU related info of the container
internal struct ContainerCPUStats: Sendable, Content, Hashable {

    internal var cpuUsage: ContainerCPUUsage?
    /** System Usage.  This field is Linux-specific and omitted for Windows containers.  */
    internal var systemCpuUsage: Int?
    /** Number of online CPUs.  This field is Linux-specific and omitted for Windows containers.  */
    internal var onlineCpus: Int?
    internal var throttlingData: ContainerThrottlingData?

    internal init(cpuUsage: ContainerCPUUsage? = nil, systemCpuUsage: Int? = nil, onlineCpus: Int? = nil, throttlingData: ContainerThrottlingData? = nil) {
        self.cpuUsage = cpuUsage
        self.systemCpuUsage = systemCpuUsage
        self.onlineCpus = onlineCpus
        self.throttlingData = throttlingData
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cpuUsage = "cpu_usage"
        case systemCpuUsage = "system_cpu_usage"
        case onlineCpus = "online_cpus"
        case throttlingData = "throttling_data"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(cpuUsage, forKey: .cpuUsage)
        try keyedContainer.encodeIfPresent(systemCpuUsage, forKey: .systemCpuUsage)
        try keyedContainer.encodeIfPresent(onlineCpus, forKey: .onlineCpus)
        try keyedContainer.encodeIfPresent(throttlingData, forKey: .throttlingData)
    }
}
