//
// ContainerThrottlingData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// CPU throttling stats of the container.  This type is Linux-specific and omitted for Windows containers.
internal struct ContainerThrottlingData: Sendable, Content, Hashable {

    /** Number of periods with throttling active.  */
    internal var periods: Int?
    /** Number of periods when the container hit its throttling limit.  */
    internal var throttledPeriods: Int?
    /** Aggregated time (in nanoseconds) the container was throttled for.  */
    internal var throttledTime: Int?

    internal init(periods: Int? = nil, throttledPeriods: Int? = nil, throttledTime: Int? = nil) {
        self.periods = periods
        self.throttledPeriods = throttledPeriods
        self.throttledTime = throttledTime
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case periods
        case throttledPeriods = "throttled_periods"
        case throttledTime = "throttled_time"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(periods, forKey: .periods)
        try keyedContainer.encodeIfPresent(throttledPeriods, forKey: .throttledPeriods)
        try keyedContainer.encodeIfPresent(throttledTime, forKey: .throttledTime)
    }
}
