//
// ContainerConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Configuration for a container that is portable between hosts.
internal struct ContainerConfig: Sendable, Content, Hashable {

    /** The hostname to use for the container, as a valid RFC 1123 hostname.  */
    internal var hostname: String?
    /** The domain name to use for the container.  */
    internal var domainname: String?
    /** Commands run as this user inside the container. If omitted, commands run as the user specified in the image the container was started from.  Can be either user-name or UID, and optional group-name or GID, separated by a colon (`<user-name|UID>[<:group-name|GID>]`). */
    internal var user: String?
    /** Whether to attach to `stdin`. */
    internal var attachStdin: Bool? = false
    /** Whether to attach to `stdout`. */
    internal var attachStdout: Bool? = true
    /** Whether to attach to `stderr`. */
    internal var attachStderr: Bool? = true
    /** An object mapping ports to an empty object in the form:  `{\"<port>/<tcp|udp|sctp>\": {}}`  */
    internal var exposedPorts: [String: JSONValue]?
    /** Attach standard streams to a TTY, including `stdin` if it is not closed.  */
    internal var tty: Bool? = false
    /** Open `stdin` */
    internal var openStdin: Bool? = false
    /** Close `stdin` after one attached client disconnects */
    internal var stdinOnce: Bool? = false
    /** A list of environment variables to set inside the container in the form `[\"VAR=value\", ...]`. A variable without `=` is removed from the environment, rather than to have an empty value.  */
    internal var env: [String]?
    /** Command to run specified as a string or an array of strings.  */
    internal var cmd: [String]?
    internal var healthcheck: HealthConfig?
    /** Command is already escaped (Windows only) */
    internal var argsEscaped: Bool? = false
    /** The name (or reference) of the image to use when creating the container, or which was used when the container was created.  */
    internal var image: String?
    /** An object mapping mount point paths inside the container to empty objects.  */
    internal var volumes: [String: JSONValue]?
    /** The working directory for commands to run in. */
    internal var workingDir: String?
    /** The entry point for the container as a string or an array of strings.  If the array consists of exactly one empty string (`[\"\"]`) then the entry point is reset to system default (i.e., the entry point used by docker when there is no `ENTRYPOINT` instruction in the `Dockerfile`).  */
    internal var entrypoint: [String]?
    /** Disable networking for the container. */
    internal var networkDisabled: Bool?
    /** MAC address of the container.  Deprecated: this field is deprecated in API v1.44 and up. Use EndpointSettings.MacAddress instead.  */
    internal var macAddress: String?
    /** `ONBUILD` metadata that were defined in the image's `Dockerfile`.  */
    internal var onBuild: [String]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** Signal to stop a container as a string or unsigned integer.  */
    internal var stopSignal: String?
    /** Timeout to stop a container in seconds. */
    internal var stopTimeout: Int?
    /** Shell for when `RUN`, `CMD`, and `ENTRYPOINT` uses a shell.  */
    internal var shell: [String]?

    internal init(
        hostname: String? = nil, domainname: String? = nil, user: String? = nil, attachStdin: Bool? = false, attachStdout: Bool? = true, attachStderr: Bool? = true,
        exposedPorts: [String: JSONValue]? = nil, tty: Bool? = false, openStdin: Bool? = false, stdinOnce: Bool? = false, env: [String]? = nil, cmd: [String]? = nil,
        healthcheck: HealthConfig? = nil, argsEscaped: Bool? = false, image: String? = nil, volumes: [String: JSONValue]? = nil, workingDir: String? = nil,
        entrypoint: [String]? = nil, networkDisabled: Bool? = nil, macAddress: String? = nil, onBuild: [String]? = nil, labels: [String: String]? = nil, stopSignal: String? = nil,
        stopTimeout: Int? = nil, shell: [String]? = nil
    ) {
        self.hostname = hostname
        self.domainname = domainname
        self.user = user
        self.attachStdin = attachStdin
        self.attachStdout = attachStdout
        self.attachStderr = attachStderr
        self.exposedPorts = exposedPorts
        self.tty = tty
        self.openStdin = openStdin
        self.stdinOnce = stdinOnce
        self.env = env
        self.cmd = cmd
        self.healthcheck = healthcheck
        self.argsEscaped = argsEscaped
        self.image = image
        self.volumes = volumes
        self.workingDir = workingDir
        self.entrypoint = entrypoint
        self.networkDisabled = networkDisabled
        self.macAddress = macAddress
        self.onBuild = onBuild
        self.labels = labels
        self.stopSignal = stopSignal
        self.stopTimeout = stopTimeout
        self.shell = shell
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case hostname = "Hostname"
        case domainname = "Domainname"
        case user = "User"
        case attachStdin = "AttachStdin"
        case attachStdout = "AttachStdout"
        case attachStderr = "AttachStderr"
        case exposedPorts = "ExposedPorts"
        case tty = "Tty"
        case openStdin = "OpenStdin"
        case stdinOnce = "StdinOnce"
        case env = "Env"
        case cmd = "Cmd"
        case healthcheck = "Healthcheck"
        case argsEscaped = "ArgsEscaped"
        case image = "Image"
        case volumes = "Volumes"
        case workingDir = "WorkingDir"
        case entrypoint = "Entrypoint"
        case networkDisabled = "NetworkDisabled"
        case macAddress = "MacAddress"
        case onBuild = "OnBuild"
        case labels = "Labels"
        case stopSignal = "StopSignal"
        case stopTimeout = "StopTimeout"
        case shell = "Shell"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(hostname, forKey: .hostname)
        try keyedContainer.encodeIfPresent(domainname, forKey: .domainname)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(attachStdin, forKey: .attachStdin)
        try keyedContainer.encodeIfPresent(attachStdout, forKey: .attachStdout)
        try keyedContainer.encodeIfPresent(attachStderr, forKey: .attachStderr)
        try keyedContainer.encodeIfPresent(exposedPorts, forKey: .exposedPorts)
        try keyedContainer.encodeIfPresent(tty, forKey: .tty)
        try keyedContainer.encodeIfPresent(openStdin, forKey: .openStdin)
        try keyedContainer.encodeIfPresent(stdinOnce, forKey: .stdinOnce)
        try keyedContainer.encodeIfPresent(env, forKey: .env)
        try keyedContainer.encodeIfPresent(cmd, forKey: .cmd)
        try keyedContainer.encodeIfPresent(healthcheck, forKey: .healthcheck)
        try keyedContainer.encodeIfPresent(argsEscaped, forKey: .argsEscaped)
        try keyedContainer.encodeIfPresent(image, forKey: .image)
        try keyedContainer.encodeIfPresent(volumes, forKey: .volumes)
        try keyedContainer.encodeIfPresent(workingDir, forKey: .workingDir)
        try keyedContainer.encodeIfPresent(entrypoint, forKey: .entrypoint)
        try keyedContainer.encodeIfPresent(networkDisabled, forKey: .networkDisabled)
        try keyedContainer.encodeIfPresent(macAddress, forKey: .macAddress)
        try keyedContainer.encodeIfPresent(onBuild, forKey: .onBuild)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(stopSignal, forKey: .stopSignal)
        try keyedContainer.encodeIfPresent(stopTimeout, forKey: .stopTimeout)
        try keyedContainer.encodeIfPresent(shell, forKey: .shell)
    }
}
