//
// ContainerPidsStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// PidsStats contains Linux-specific stats of a container&#39;s process-IDs (PIDs).  This type is Linux-specific and omitted for Windows containers.
internal struct ContainerPidsStats: Sendable, Content, Hashable {

    /** Current is the number of PIDs in the cgroup.  */
    internal var current: Int?
    /** Limit is the hard limit on the number of pids in the cgroup. A \"Limit\" of 0 means that there is no limit.  */
    internal var limit: Int?

    internal init(current: Int? = nil, limit: Int? = nil) {
        self.current = current
        self.limit = limit
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case limit
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(current, forKey: .current)
        try keyedContainer.encodeIfPresent(limit, forKey: .limit)
    }
}
