//
// ContainerStorageStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// StorageStats is the disk I/O stats for read/write on Windows.  This type is Windows-specific and omitted for Linux containers.
internal struct ContainerStorageStats: Sendable, Content, Hashable {

    internal var readCountNormalized: Int?
    internal var readSizeBytes: Int?
    internal var writeCountNormalized: Int?
    internal var writeSizeBytes: Int?

    internal init(readCountNormalized: Int? = nil, readSizeBytes: Int? = nil, writeCountNormalized: Int? = nil, writeSizeBytes: Int? = nil) {
        self.readCountNormalized = readCountNormalized
        self.readSizeBytes = readSizeBytes
        self.writeCountNormalized = writeCountNormalized
        self.writeSizeBytes = writeSizeBytes
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case readCountNormalized = "read_count_normalized"
        case readSizeBytes = "read_size_bytes"
        case writeCountNormalized = "write_count_normalized"
        case writeSizeBytes = "write_size_bytes"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(readCountNormalized, forKey: .readCountNormalized)
        try keyedContainer.encodeIfPresent(readSizeBytes, forKey: .readSizeBytes)
        try keyedContainer.encodeIfPresent(writeCountNormalized, forKey: .writeCountNormalized)
        try keyedContainer.encodeIfPresent(writeSizeBytes, forKey: .writeSizeBytes)
    }
}
