//
// ContainerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// represents the status of a container.
internal struct ContainerStatus: Sendable, Content, Hashable {

    internal var containerID: String?
    internal var PID: Int?
    internal var exitCode: Int?

    internal init(containerID: String? = nil, PID: Int? = nil, exitCode: Int? = nil) {
        self.containerID = containerID
        self.PID = PID
        self.exitCode = exitCode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case containerID = "ContainerID"
        case PID
        case exitCode = "ExitCode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(containerID, forKey: .containerID)
        try keyedContainer.encodeIfPresent(PID, forKey: .PID)
        try keyedContainer.encodeIfPresent(exitCode, forKey: .exitCode)
    }
}
