//
// ContainerTopResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Container \&quot;top\&quot; response.
internal struct ContainerTopResponse: Sendable, Content, Hashable {

    /** The ps column titles */
    internal var titles: [String]?
    /** Each process running in the container, where each process is an array of values corresponding to the titles. */
    internal var processes: [[String]]?

    internal init(titles: [String]? = nil, processes: [[String]]? = nil) {
        self.titles = titles
        self.processes = processes
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case titles = "Titles"
        case processes = "Processes"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(titles, forKey: .titles)
        try keyedContainer.encodeIfPresent(processes, forKey: .processes)
    }
}
