//
// ContainerUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ContainerUpdateRequest: Sendable, Content, Hashable {

    /** An integer value representing this container's relative CPU weight versus other containers.  */
    internal var cpuShares: Int?
    /** Memory limit in bytes. */
    internal var memory: Int64? = 0
    /** Path to `cgroups` under which the container's `cgroup` is created. If the path is not absolute, the path is considered to be relative to the `cgroups` path of the init process. Cgroups are created if they do not already exist.  */
    internal var cgroupParent: String?
    /** Block IO weight (relative weight). */
    internal var blkioWeight: Int?
    /** Block IO weight (relative device weight) in the form:  ``` [{\"Path\": \"device_path\", \"Weight\": weight}] ```  */
    internal var blkioWeightDevice: [ResourcesBlkioWeightDeviceInner]?
    /** Limit read rate (bytes per second) from a device, in the form:  ``` [{\"Path\": \"device_path\", \"Rate\": rate}] ```  */
    internal var blkioDeviceReadBps: [ThrottleDevice]?
    /** Limit write rate (bytes per second) to a device, in the form:  ``` [{\"Path\": \"device_path\", \"Rate\": rate}] ```  */
    internal var blkioDeviceWriteBps: [ThrottleDevice]?
    /** Limit read rate (IO per second) from a device, in the form:  ``` [{\"Path\": \"device_path\", \"Rate\": rate}] ```  */
    internal var blkioDeviceReadIOps: [ThrottleDevice]?
    /** Limit write rate (IO per second) to a device, in the form:  ``` [{\"Path\": \"device_path\", \"Rate\": rate}] ```  */
    internal var blkioDeviceWriteIOps: [ThrottleDevice]?
    /** The length of a CPU period in microseconds. */
    internal var cpuPeriod: Int64?
    /** Microseconds of CPU time that the container can get in a CPU period.  */
    internal var cpuQuota: Int64?
    /** The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.  */
    internal var cpuRealtimePeriod: Int64?
    /** The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.  */
    internal var cpuRealtimeRuntime: Int64?
    /** CPUs in which to allow execution (e.g., `0-3`, `0,1`).  */
    internal var cpusetCpus: String?
    /** Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.  */
    internal var cpusetMems: String?
    /** A list of devices to add to the container. */
    internal var devices: [DeviceMapping]?
    /** a list of cgroup rules to apply to the container */
    internal var deviceCgroupRules: [String]?
    /** A list of requests for devices to be sent to device drivers.  */
    internal var deviceRequests: [DeviceRequest]?
    /** Hard limit for kernel TCP buffer memory (in bytes). Depending on the OCI runtime in use, this option may be ignored. It is no longer supported by the default (runc) runtime.  This field is omitted when empty.  **Deprecated**: This field is deprecated as kernel 6.12 has deprecated `memory.kmem.tcp.limit_in_bytes` field for cgroups v1. This field will be removed in a future release.  */
    internal var kernelMemoryTCP: Int64?
    /** Memory soft limit in bytes. */
    internal var memoryReservation: Int64?
    /** Total memory limit (memory + swap). Set as `-1` to enable unlimited swap.  */
    internal var memorySwap: Int64?
    /** Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.  */
    internal var memorySwappiness: Int64?
    /** CPU quota in units of 10<sup>-9</sup> CPUs. */
    internal var nanoCpus: Int64?
    /** Disable OOM Killer for the container. */
    internal var oomKillDisable: Bool?
    /** Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.  */
    internal var `init`: Bool?
    /** Tune a container's PIDs limit. Set `0` or `-1` for unlimited, or `null` to not change.  */
    internal var pidsLimit: Int64?
    /** A list of resource limits to set in the container. For example:  ``` {\"Name\": \"nofile\", \"Soft\": 1024, \"Hard\": 2048} ```  */
    internal var ulimits: [ResourcesUlimitsInner]?
    /** The number of usable CPUs (Windows only).  On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is `CPUCount` first, then `CPUShares`, and `CPUPercent` last.  */
    internal var cpuCount: Int64?
    /** The usable percentage of the available CPUs (Windows only).  On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is `CPUCount` first, then `CPUShares`, and `CPUPercent` last.  */
    internal var cpuPercent: Int64?
    /** Maximum IOps for the container system drive (Windows only) */
    internal var iOMaximumIOps: Int64?
    /** Maximum IO in bytes per second for the container system drive (Windows only).  */
    internal var iOMaximumBandwidth: Int64?
    internal var restartPolicy: RestartPolicy?

    internal init(
        cpuShares: Int? = nil, memory: Int64? = 0, cgroupParent: String? = nil, blkioWeight: Int? = nil, blkioWeightDevice: [ResourcesBlkioWeightDeviceInner]? = nil,
        blkioDeviceReadBps: [ThrottleDevice]? = nil, blkioDeviceWriteBps: [ThrottleDevice]? = nil, blkioDeviceReadIOps: [ThrottleDevice]? = nil,
        blkioDeviceWriteIOps: [ThrottleDevice]? = nil, cpuPeriod: Int64? = nil, cpuQuota: Int64? = nil, cpuRealtimePeriod: Int64? = nil, cpuRealtimeRuntime: Int64? = nil,
        cpusetCpus: String? = nil, cpusetMems: String? = nil, devices: [DeviceMapping]? = nil, deviceCgroupRules: [String]? = nil, deviceRequests: [DeviceRequest]? = nil,
        kernelMemoryTCP: Int64? = nil, memoryReservation: Int64? = nil, memorySwap: Int64? = nil, memorySwappiness: Int64? = nil, nanoCpus: Int64? = nil,
        oomKillDisable: Bool? = nil, `init`: Bool? = nil, pidsLimit: Int64? = nil, ulimits: [ResourcesUlimitsInner]? = nil, cpuCount: Int64? = nil, cpuPercent: Int64? = nil,
        iOMaximumIOps: Int64? = nil, iOMaximumBandwidth: Int64? = nil, restartPolicy: RestartPolicy? = nil
    ) {
        self.cpuShares = cpuShares
        self.memory = memory
        self.cgroupParent = cgroupParent
        self.blkioWeight = blkioWeight
        self.blkioWeightDevice = blkioWeightDevice
        self.blkioDeviceReadBps = blkioDeviceReadBps
        self.blkioDeviceWriteBps = blkioDeviceWriteBps
        self.blkioDeviceReadIOps = blkioDeviceReadIOps
        self.blkioDeviceWriteIOps = blkioDeviceWriteIOps
        self.cpuPeriod = cpuPeriod
        self.cpuQuota = cpuQuota
        self.cpuRealtimePeriod = cpuRealtimePeriod
        self.cpuRealtimeRuntime = cpuRealtimeRuntime
        self.cpusetCpus = cpusetCpus
        self.cpusetMems = cpusetMems
        self.devices = devices
        self.deviceCgroupRules = deviceCgroupRules
        self.deviceRequests = deviceRequests
        self.kernelMemoryTCP = kernelMemoryTCP
        self.memoryReservation = memoryReservation
        self.memorySwap = memorySwap
        self.memorySwappiness = memorySwappiness
        self.nanoCpus = nanoCpus
        self.oomKillDisable = oomKillDisable
        self.`init` = `init`
        self.pidsLimit = pidsLimit
        self.ulimits = ulimits
        self.cpuCount = cpuCount
        self.cpuPercent = cpuPercent
        self.iOMaximumIOps = iOMaximumIOps
        self.iOMaximumBandwidth = iOMaximumBandwidth
        self.restartPolicy = restartPolicy
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case cpuShares = "CpuShares"
        case memory = "Memory"
        case cgroupParent = "CgroupParent"
        case blkioWeight = "BlkioWeight"
        case blkioWeightDevice = "BlkioWeightDevice"
        case blkioDeviceReadBps = "BlkioDeviceReadBps"
        case blkioDeviceWriteBps = "BlkioDeviceWriteBps"
        case blkioDeviceReadIOps = "BlkioDeviceReadIOps"
        case blkioDeviceWriteIOps = "BlkioDeviceWriteIOps"
        case cpuPeriod = "CpuPeriod"
        case cpuQuota = "CpuQuota"
        case cpuRealtimePeriod = "CpuRealtimePeriod"
        case cpuRealtimeRuntime = "CpuRealtimeRuntime"
        case cpusetCpus = "CpusetCpus"
        case cpusetMems = "CpusetMems"
        case devices = "Devices"
        case deviceCgroupRules = "DeviceCgroupRules"
        case deviceRequests = "DeviceRequests"
        case kernelMemoryTCP = "KernelMemoryTCP"
        case memoryReservation = "MemoryReservation"
        case memorySwap = "MemorySwap"
        case memorySwappiness = "MemorySwappiness"
        case nanoCpus = "NanoCpus"
        case oomKillDisable = "OomKillDisable"
        case `init` = "Init"
        case pidsLimit = "PidsLimit"
        case ulimits = "Ulimits"
        case cpuCount = "CpuCount"
        case cpuPercent = "CpuPercent"
        case iOMaximumIOps = "IOMaximumIOps"
        case iOMaximumBandwidth = "IOMaximumBandwidth"
        case restartPolicy = "RestartPolicy"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(cpuShares, forKey: .cpuShares)
        try keyedContainer.encodeIfPresent(memory, forKey: .memory)
        try keyedContainer.encodeIfPresent(cgroupParent, forKey: .cgroupParent)
        try keyedContainer.encodeIfPresent(blkioWeight, forKey: .blkioWeight)
        try keyedContainer.encodeIfPresent(blkioWeightDevice, forKey: .blkioWeightDevice)
        try keyedContainer.encodeIfPresent(blkioDeviceReadBps, forKey: .blkioDeviceReadBps)
        try keyedContainer.encodeIfPresent(blkioDeviceWriteBps, forKey: .blkioDeviceWriteBps)
        try keyedContainer.encodeIfPresent(blkioDeviceReadIOps, forKey: .blkioDeviceReadIOps)
        try keyedContainer.encodeIfPresent(blkioDeviceWriteIOps, forKey: .blkioDeviceWriteIOps)
        try keyedContainer.encodeIfPresent(cpuPeriod, forKey: .cpuPeriod)
        try keyedContainer.encodeIfPresent(cpuQuota, forKey: .cpuQuota)
        try keyedContainer.encodeIfPresent(cpuRealtimePeriod, forKey: .cpuRealtimePeriod)
        try keyedContainer.encodeIfPresent(cpuRealtimeRuntime, forKey: .cpuRealtimeRuntime)
        try keyedContainer.encodeIfPresent(cpusetCpus, forKey: .cpusetCpus)
        try keyedContainer.encodeIfPresent(cpusetMems, forKey: .cpusetMems)
        try keyedContainer.encodeIfPresent(devices, forKey: .devices)
        try keyedContainer.encodeIfPresent(deviceCgroupRules, forKey: .deviceCgroupRules)
        try keyedContainer.encodeIfPresent(deviceRequests, forKey: .deviceRequests)
        try keyedContainer.encodeIfPresent(kernelMemoryTCP, forKey: .kernelMemoryTCP)
        try keyedContainer.encodeIfPresent(memoryReservation, forKey: .memoryReservation)
        try keyedContainer.encodeIfPresent(memorySwap, forKey: .memorySwap)
        try keyedContainer.encodeIfPresent(memorySwappiness, forKey: .memorySwappiness)
        try keyedContainer.encodeIfPresent(nanoCpus, forKey: .nanoCpus)
        try keyedContainer.encodeIfPresent(oomKillDisable, forKey: .oomKillDisable)
        try keyedContainer.encodeIfPresent(`init`, forKey: .`init`)
        try keyedContainer.encodeIfPresent(pidsLimit, forKey: .pidsLimit)
        try keyedContainer.encodeIfPresent(ulimits, forKey: .ulimits)
        try keyedContainer.encodeIfPresent(cpuCount, forKey: .cpuCount)
        try keyedContainer.encodeIfPresent(cpuPercent, forKey: .cpuPercent)
        try keyedContainer.encodeIfPresent(iOMaximumIOps, forKey: .iOMaximumIOps)
        try keyedContainer.encodeIfPresent(iOMaximumBandwidth, forKey: .iOMaximumBandwidth)
        try keyedContainer.encodeIfPresent(restartPolicy, forKey: .restartPolicy)
    }
}
