//
// ContainerMemoryStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Aggregates all memory stats since container inception on Linux. Windows returns stats for commit and private working set only.
internal struct ContainerMemoryStats: Sendable, Content, Hashable {

    /** Current `res_counter` usage for memory.  This field is Linux-specific and omitted for Windows containers.  */
    internal var usage: Int?
    /** Maximum usage ever recorded.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.  */
    internal var maxUsage: Int?
    /** All the stats exported via memory.stat.  The fields in this object differ between cgroups v1 and v2. On cgroups v1, fields such as `cache`, `rss`, `mapped_file` are available. On cgroups v2, fields such as `file`, `anon`, `inactive_file` are available.  This field is Linux-specific and omitted for Windows containers.  */
    internal var stats: [String: Int?]?
    /** Number of times memory usage hits limits.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.  */
    internal var failcnt: Int?
    /** This field is Linux-specific and omitted for Windows containers.  */
    internal var limit: Int?
    /** Committed bytes.  This field is Windows-specific and omitted for Linux containers.  */
    internal var commitbytes: Int?
    /** Peak committed bytes.  This field is Windows-specific and omitted for Linux containers.  */
    internal var commitpeakbytes: Int?
    /** Private working set.  This field is Windows-specific and omitted for Linux containers.  */
    internal var privateworkingset: Int?

    internal init(
        usage: Int? = nil, maxUsage: Int? = nil, stats: [String: Int?]? = nil, failcnt: Int? = nil, limit: Int? = nil, commitbytes: Int? = nil, commitpeakbytes: Int? = nil,
        privateworkingset: Int? = nil
    ) {
        self.usage = usage
        self.maxUsage = maxUsage
        self.stats = stats
        self.failcnt = failcnt
        self.limit = limit
        self.commitbytes = commitbytes
        self.commitpeakbytes = commitpeakbytes
        self.privateworkingset = privateworkingset
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case usage
        case maxUsage = "max_usage"
        case stats
        case failcnt
        case limit
        case commitbytes
        case commitpeakbytes
        case privateworkingset
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(usage, forKey: .usage)
        try keyedContainer.encodeIfPresent(maxUsage, forKey: .maxUsage)
        try keyedContainer.encodeIfPresent(stats, forKey: .stats)
        try keyedContainer.encodeIfPresent(failcnt, forKey: .failcnt)
        try keyedContainer.encodeIfPresent(limit, forKey: .limit)
        try keyedContainer.encodeIfPresent(commitbytes, forKey: .commitbytes)
        try keyedContainer.encodeIfPresent(commitpeakbytes, forKey: .commitpeakbytes)
        try keyedContainer.encodeIfPresent(privateworkingset, forKey: .privateworkingset)
    }
}
