//
// ContainerBlkioStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// BlkioStats stores all IO service stats for data read and write.  This type is Linux-specific and holds many fields that are specific to cgroups v1. On a cgroup v2 host, all fields other than &#x60;io_service_bytes_recursive&#x60; are omitted or &#x60;null&#x60;.  This type is only populated on Linux and omitted for Windows containers.
internal struct ContainerBlkioStats: Sendable, Content, Hashable {

    internal var ioServiceBytesRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioServicedRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioQueueRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioServiceTimeRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioWaitTimeRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioMergedRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var ioTimeRecursive: [ContainerBlkioStatEntry]?
    /** This field is only available when using Linux containers with cgroups v1. It is omitted or `null` when using cgroups v2.  */
    internal var sectorsRecursive: [ContainerBlkioStatEntry]?

    internal init(
        ioServiceBytesRecursive: [ContainerBlkioStatEntry]? = nil, ioServicedRecursive: [ContainerBlkioStatEntry]? = nil, ioQueueRecursive: [ContainerBlkioStatEntry]? = nil,
        ioServiceTimeRecursive: [ContainerBlkioStatEntry]? = nil, ioWaitTimeRecursive: [ContainerBlkioStatEntry]? = nil, ioMergedRecursive: [ContainerBlkioStatEntry]? = nil,
        ioTimeRecursive: [ContainerBlkioStatEntry]? = nil, sectorsRecursive: [ContainerBlkioStatEntry]? = nil
    ) {
        self.ioServiceBytesRecursive = ioServiceBytesRecursive
        self.ioServicedRecursive = ioServicedRecursive
        self.ioQueueRecursive = ioQueueRecursive
        self.ioServiceTimeRecursive = ioServiceTimeRecursive
        self.ioWaitTimeRecursive = ioWaitTimeRecursive
        self.ioMergedRecursive = ioMergedRecursive
        self.ioTimeRecursive = ioTimeRecursive
        self.sectorsRecursive = sectorsRecursive
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ioServiceBytesRecursive = "io_service_bytes_recursive"
        case ioServicedRecursive = "io_serviced_recursive"
        case ioQueueRecursive = "io_queue_recursive"
        case ioServiceTimeRecursive = "io_service_time_recursive"
        case ioWaitTimeRecursive = "io_wait_time_recursive"
        case ioMergedRecursive = "io_merged_recursive"
        case ioTimeRecursive = "io_time_recursive"
        case sectorsRecursive = "sectors_recursive"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ioServiceBytesRecursive, forKey: .ioServiceBytesRecursive)
        try keyedContainer.encodeIfPresent(ioServicedRecursive, forKey: .ioServicedRecursive)
        try keyedContainer.encodeIfPresent(ioQueueRecursive, forKey: .ioQueueRecursive)
        try keyedContainer.encodeIfPresent(ioServiceTimeRecursive, forKey: .ioServiceTimeRecursive)
        try keyedContainer.encodeIfPresent(ioWaitTimeRecursive, forKey: .ioWaitTimeRecursive)
        try keyedContainer.encodeIfPresent(ioMergedRecursive, forKey: .ioMergedRecursive)
        try keyedContainer.encodeIfPresent(ioTimeRecursive, forKey: .ioTimeRecursive)
        try keyedContainer.encodeIfPresent(sectorsRecursive, forKey: .sectorsRecursive)
    }
}
