//
// ContainerCPUUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// All CPU stats aggregated since container inception.
internal struct ContainerCPUUsage: Sendable, Content, Hashable {

    /** Total CPU time consumed in nanoseconds (Linux) or 100's of nanoseconds (Windows).  */
    internal var totalUsage: Int?
    /** Total CPU time (in nanoseconds) consumed per core (Linux).  This field is Linux-specific when using cgroups v1. It is omitted when using cgroups v2 and Windows containers.  */
    internal var percpuUsage: [Int]?
    /** Time (in nanoseconds) spent by tasks of the cgroup in kernel mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.  */
    internal var usageInKernelmode: Int?
    /** Time (in nanoseconds) spent by tasks of the cgroup in user mode (Linux), or time spent (in 100's of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.  */
    internal var usageInUsermode: Int?

    internal init(totalUsage: Int? = nil, percpuUsage: [Int]? = nil, usageInKernelmode: Int? = nil, usageInUsermode: Int? = nil) {
        self.totalUsage = totalUsage
        self.percpuUsage = percpuUsage
        self.usageInKernelmode = usageInKernelmode
        self.usageInUsermode = usageInUsermode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case totalUsage = "total_usage"
        case percpuUsage = "percpu_usage"
        case usageInKernelmode = "usage_in_kernelmode"
        case usageInUsermode = "usage_in_usermode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(totalUsage, forKey: .totalUsage)
        try keyedContainer.encodeIfPresent(percpuUsage, forKey: .percpuUsage)
        try keyedContainer.encodeIfPresent(usageInKernelmode, forKey: .usageInKernelmode)
        try keyedContainer.encodeIfPresent(usageInUsermode, forKey: .usageInUsermode)
    }
}
