//
// ContainerSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ContainerSummary: Sendable, Content, Hashable {

    internal enum State: String, Sendable, Content, Hashable, CaseIterable {
        case created = "created"
        case running = "running"
        case paused = "paused"
        case restarting = "restarting"
        case exited = "exited"
        case removing = "removing"
        case dead = "dead"
    }
    /** The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes). */
    internal var id: String?
    /** The names associated with this container. Most containers have a single name, but when using legacy \"links\", the container can have multiple names.  For historic reasons, names are prefixed with a forward-slash (`/`). */
    internal var names: [String]?
    /** The name or ID of the image used to create the container.  This field shows the image reference as was specified when creating the container, which can be in its canonical form (e.g., `docker.io/library/ubuntu:latest` or `docker.io/library/ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`), short form (e.g., `ubuntu:latest`)), or the ID(-prefix) of the image (e.g., `72297848456d`).  The content of this field can be updated at runtime if the image used to create the container is untagged, in which case the field is updated to contain the the image ID (digest) it was resolved to in its canonical, non-truncated form (e.g., `sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782`). */
    internal var image: String?
    /** The ID (digest) of the image that this container was created from. */
    internal var imageID: String?
    internal var imageManifestDescriptor: OCIDescriptor?
    /** Command to run when starting the container */
    internal var command: String?
    /** Date and time at which the container was created as a Unix timestamp (number of seconds since EPOCH). */
    internal var created: Int64?
    /** Port-mappings for the container. */
    internal var ports: [Port]?
    /** The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request. */
    internal var sizeRw: Int64?
    /** The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request. */
    internal var sizeRootFs: Int64?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** The state of this container.  */
    internal var state: State?
    /** Additional human-readable status of this container (e.g. `Exit 0`) */
    internal var status: String?
    internal var hostConfig: ContainerSummaryHostConfig?
    internal var networkSettings: ContainerSummaryNetworkSettings?
    /** List of mounts used by the container. */
    internal var mounts: [MountPoint]?

    internal init(
        id: String? = nil, names: [String]? = nil, image: String? = nil, imageID: String? = nil, imageManifestDescriptor: OCIDescriptor? = nil, command: String? = nil,
        created: Int64? = nil, ports: [Port]? = nil, sizeRw: Int64? = nil, sizeRootFs: Int64? = nil, labels: [String: String]? = nil, state: State? = nil, status: String? = nil,
        hostConfig: ContainerSummaryHostConfig? = nil, networkSettings: ContainerSummaryNetworkSettings? = nil, mounts: [MountPoint]? = nil
    ) {
        self.id = id
        self.names = names
        self.image = image
        self.imageID = imageID
        self.imageManifestDescriptor = imageManifestDescriptor
        self.command = command
        self.created = created
        self.ports = ports
        self.sizeRw = sizeRw
        self.sizeRootFs = sizeRootFs
        self.labels = labels
        self.state = state
        self.status = status
        self.hostConfig = hostConfig
        self.networkSettings = networkSettings
        self.mounts = mounts
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case names = "Names"
        case image = "Image"
        case imageID = "ImageID"
        case imageManifestDescriptor = "ImageManifestDescriptor"
        case command = "Command"
        case created = "Created"
        case ports = "Ports"
        case sizeRw = "SizeRw"
        case sizeRootFs = "SizeRootFs"
        case labels = "Labels"
        case state = "State"
        case status = "Status"
        case hostConfig = "HostConfig"
        case networkSettings = "NetworkSettings"
        case mounts = "Mounts"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(names, forKey: .names)
        try keyedContainer.encodeIfPresent(image, forKey: .image)
        try keyedContainer.encodeIfPresent(imageID, forKey: .imageID)
        try keyedContainer.encodeIfPresent(imageManifestDescriptor, forKey: .imageManifestDescriptor)
        try keyedContainer.encodeIfPresent(command, forKey: .command)
        try keyedContainer.encodeIfPresent(created, forKey: .created)
        try keyedContainer.encodeIfPresent(ports, forKey: .ports)
        try keyedContainer.encodeIfPresent(sizeRw, forKey: .sizeRw)
        try keyedContainer.encodeIfPresent(sizeRootFs, forKey: .sizeRootFs)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(state, forKey: .state)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
        try keyedContainer.encodeIfPresent(hostConfig, forKey: .hostConfig)
        try keyedContainer.encodeIfPresent(networkSettings, forKey: .networkSettings)
        try keyedContainer.encodeIfPresent(mounts, forKey: .mounts)
    }
}
