//
// ContainerPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ContainerPruneResponse: Sendable, Content, Hashable {

    /** Container IDs that were deleted */
    internal var containersDeleted: [String]?
    /** Disk space reclaimed in bytes */
    internal var spaceReclaimed: Int64?

    internal init(containersDeleted: [String]? = nil, spaceReclaimed: Int64? = nil) {
        self.containersDeleted = containersDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case containersDeleted = "ContainersDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(containersDeleted, forKey: .containersDeleted)
        try keyedContainer.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}
