//
// ContainerSummaryHostConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Summary of host-specific runtime information of the container. This is a reduced set of information in the container&#39;s \&quot;HostConfig\&quot; as available in the container \&quot;inspect\&quot; response.
internal struct ContainerSummaryHostConfig: Sendable, Content, Hashable {

    /** Networking mode (`host`, `none`, `container:<id>`) or name of the primary network the container is using.  This field is primarily for backward compatibility. The container can be connected to multiple networks for which information can be found in the `NetworkSettings.Networks` field, which enumerates settings per network. */
    internal var networkMode: String?
    /** Arbitrary key-value metadata attached to the container. */
    internal var annotations: [String: String]?

    internal init(networkMode: String? = nil, annotations: [String: String]? = nil) {
        self.networkMode = networkMode
        self.annotations = annotations
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case networkMode = "NetworkMode"
        case annotations = "Annotations"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(networkMode, forKey: .networkMode)
        try keyedContainer.encodeIfPresent(annotations, forKey: .annotations)
    }
}
