//
// ContainerWaitResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// OK response to ContainerWait operation
internal struct ContainerWaitResponse: Sendable, Content, Hashable {

    /** Exit code of the container */
    internal var statusCode: Int64
    internal var error: ContainerWaitExitError?

    internal init(statusCode: Int64, error: ContainerWaitExitError? = nil) {
        self.statusCode = statusCode
        self.error = error
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode = "StatusCode"
        case error = "Error"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(statusCode, forKey: .statusCode)
        try keyedContainer.encodeIfPresent(error, forKey: .error)
    }
}
