//
// DeviceMapping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A device mapping between the host and container
internal struct DeviceMapping: Sendable, Content, Hashable {

    internal var pathOnHost: String?
    internal var pathInContainer: String?
    internal var cgroupPermissions: String?

    internal init(pathOnHost: String? = nil, pathInContainer: String? = nil, cgroupPermissions: String? = nil) {
        self.pathOnHost = pathOnHost
        self.pathInContainer = pathInContainer
        self.cgroupPermissions = cgroupPermissions
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case pathOnHost = "PathOnHost"
        case pathInContainer = "PathInContainer"
        case cgroupPermissions = "CgroupPermissions"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(pathOnHost, forKey: .pathOnHost)
        try keyedContainer.encodeIfPresent(pathInContainer, forKey: .pathInContainer)
        try keyedContainer.encodeIfPresent(cgroupPermissions, forKey: .cgroupPermissions)
    }
}
