//
// DeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A request for devices to be sent to device drivers
internal struct DeviceRequest: Sendable, Content, Hashable {

    internal var driver: String?
    internal var count: Int?
    internal var deviceIDs: [String]?
    /** A list of capabilities; an OR list of AND lists of capabilities.  */
    internal var capabilities: [[String]]?
    /** Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.  */
    internal var options: [String: String]?

    internal init(driver: String? = nil, count: Int? = nil, deviceIDs: [String]? = nil, capabilities: [[String]]? = nil, options: [String: String]? = nil) {
        self.driver = driver
        self.count = count
        self.deviceIDs = deviceIDs
        self.capabilities = capabilities
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case driver = "Driver"
        case count = "Count"
        case deviceIDs = "DeviceIDs"
        case capabilities = "Capabilities"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(count, forKey: .count)
        try keyedContainer.encodeIfPresent(deviceIDs, forKey: .deviceIDs)
        try keyedContainer.encodeIfPresent(capabilities, forKey: .capabilities)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
