//
// DeviceInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// DeviceInfo represents a device that can be used by a container.
internal struct DeviceInfo: Sendable, Content, Hashable {

    /** The origin device driver.  */
    internal var source: String?
    /** The unique identifier for the device within its source driver. For CDI devices, this would be an FQDN like \"vendor.com/gpu=0\".  */
    internal var ID: String?

    internal init(source: String? = nil, ID: String? = nil) {
        self.source = source
        self.ID = ID
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case source = "Source"
        case ID
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(source, forKey: .source)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
    }
}
