//
// DistributionInspect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Describes the result obtained from contacting the registry to retrieve image metadata.
internal struct DistributionInspect: Sendable, Content, Hashable {

    internal var descriptor: OCIDescriptor
    /** An array containing all platforms supported by the image.  */
    internal var platforms: [OCIPlatform]

    internal init(descriptor: OCIDescriptor, platforms: [OCIPlatform]) {
        self.descriptor = descriptor
        self.platforms = platforms
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case descriptor = "Descriptor"
        case platforms = "Platforms"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(descriptor, forKey: .descriptor)
        try keyedContainer.encode(platforms, forKey: .platforms)
    }
}
