//
// DockerErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Represents an error.
internal struct DockerErrorResponse: Sendable, Content, Hashable {

    /** The error message. */
    internal var message: String

    internal init(message: String) {
        self.message = message
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case message
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(message, forKey: .message)
    }
}
