//
// DockerImageDeleteResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct DockerImageDeleteResponseItem: Sendable, Content, Hashable {

    /** The image ID of an image that was untagged */
    internal var untagged: String?
    /** The image ID of an image that was deleted */
    internal var deleted: String?

    internal init(untagged: String? = nil, deleted: String? = nil) {
        self.untagged = untagged
        self.deleted = deleted
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case untagged = "Untagged"
        case deleted = "Deleted"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(untagged, forKey: .untagged)
        try keyedContainer.encodeIfPresent(deleted, forKey: .deleted)
    }
}
