//
// DockerPlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Platform represents the platform (Arch/OS).
internal struct DockerPlatform: Sendable, Content, Hashable {

    /** Architecture represents the hardware architecture (for example, `x86_64`).  */
    internal var architecture: String?
    /** OS represents the Operating System (for example, `linux` or `windows`).  */
    internal var OS: String?

    internal init(architecture: String? = nil, OS: String? = nil) {
        self.architecture = architecture
        self.OS = OS
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case architecture = "Architecture"
        case OS
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(architecture, forKey: .architecture)
        try keyedContainer.encodeIfPresent(OS, forKey: .OS)
    }
}
