//
// DriverData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about the storage driver used to store the container&#39;s and image&#39;s filesystem.
internal struct DriverData: Sendable, Content, Hashable {

    /** Name of the storage driver. */
    internal var name: String
    /** Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.  */
    internal var data: [String: String]

    internal init(name: String, data: [String: String]) {
        self.name = name
        self.data = data
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case data = "Data"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(data, forKey: .data)
    }
}
