//
// Driver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Driver represents a driver (network, logging, secrets).
internal struct Driver: Sendable, Content, Hashable {

    /** Name of the driver. */
    internal var name: String
    /** Key/value map of driver-specific options. */
    internal var options: [String: String]?

    internal init(name: String, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
