//
// EndpointIPAMConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// EndpointIPAMConfig represents an endpoint&#39;s IPAM configuration.
internal struct EndpointIPAMConfig: Sendable, Content, Hashable {

    internal var iPv4Address: String?
    internal var iPv6Address: String?
    internal var linkLocalIPs: [String]?

    internal init(iPv4Address: String? = nil, iPv6Address: String? = nil, linkLocalIPs: [String]? = nil) {
        self.iPv4Address = iPv4Address
        self.iPv6Address = iPv6Address
        self.linkLocalIPs = linkLocalIPs
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case iPv4Address = "IPv4Address"
        case iPv6Address = "IPv6Address"
        case linkLocalIPs = "LinkLocalIPs"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(iPv4Address, forKey: .iPv4Address)
        try keyedContainer.encodeIfPresent(iPv6Address, forKey: .iPv6Address)
        try keyedContainer.encodeIfPresent(linkLocalIPs, forKey: .linkLocalIPs)
    }
}
