//
// EndpointPortConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct EndpointPortConfig: Sendable, Content, Hashable {

    internal enum ModelProtocol: String, Sendable, Content, Hashable, CaseIterable {
        case tcp = "tcp"
        case udp = "udp"
        case sctp = "sctp"
    }
    internal enum PublishMode: String, Sendable, Content, Hashable, CaseIterable {
        case ingress = "ingress"
        case host = "host"
    }
    internal var name: String?
    internal var `protocol`: ModelProtocol?
    /** The port inside the container. */
    internal var targetPort: Int?
    /** The port on the swarm hosts. */
    internal var publishedPort: Int?
    /** The mode in which port is published.  <p><br /></p>  - \"ingress\" makes the target port accessible on every node,   regardless of whether there is a task for the service running on   that node or not. - \"host\" bypasses the routing mesh and publish the port directly on   the swarm node where that service is running.  */
    internal var publishMode: PublishMode? = .ingress

    internal init(name: String? = nil, `protocol`: ModelProtocol? = nil, targetPort: Int? = nil, publishedPort: Int? = nil, publishMode: PublishMode? = .ingress) {
        self.name = name
        self.`protocol` = `protocol`
        self.targetPort = targetPort
        self.publishedPort = publishedPort
        self.publishMode = publishMode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case `protocol` = "Protocol"
        case targetPort = "TargetPort"
        case publishedPort = "PublishedPort"
        case publishMode = "PublishMode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(`protocol`, forKey: .`protocol`)
        try keyedContainer.encodeIfPresent(targetPort, forKey: .targetPort)
        try keyedContainer.encodeIfPresent(publishedPort, forKey: .publishedPort)
        try keyedContainer.encodeIfPresent(publishMode, forKey: .publishMode)
    }
}
