//
// EndpointSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Configuration for a network endpoint.
internal struct EndpointSettings: Sendable, Content, Hashable {

    internal var iPAMConfig: EndpointIPAMConfig?
    internal var links: [String]?
    /** MAC address for the endpoint on this network. The network driver might ignore this parameter.  */
    internal var macAddress: String?
    internal var aliases: [String]?
    /** DriverOpts is a mapping of driver options and values. These options are passed directly to the driver and are driver specific.  */
    internal var driverOpts: [String: String]?
    /** This property determines which endpoint will provide the default gateway for a container. The endpoint with the highest priority will be used. If multiple endpoints have the same priority, endpoints are lexicographically sorted based on their network name, and the one that sorts first is picked.  */
    internal var gwPriority: Int64?
    /** Unique ID of the network.  */
    internal var networkID: String?
    /** Unique ID for the service endpoint in a Sandbox.  */
    internal var endpointID: String?
    /** Gateway address for this network.  */
    internal var gateway: String?
    /** IPv4 address.  */
    internal var iPAddress: String?
    /** Mask length of the IPv4 address.  */
    internal var iPPrefixLen: Int?
    /** IPv6 gateway address.  */
    internal var iPv6Gateway: String?
    /** Global IPv6 address.  */
    internal var globalIPv6Address: String?
    /** Mask length of the global IPv6 address.  */
    internal var globalIPv6PrefixLen: Int64?
    /** List of all DNS names an endpoint has on a specific network. This list is based on the container name, network aliases, container short ID, and hostname.  These DNS names are non-fully qualified but can contain several dots. You can get fully qualified DNS names by appending `.<network-name>`. For instance, if container name is `my.ctr` and the network is named `testnet`, `DNSNames` will contain `my.ctr` and the FQDN will be `my.ctr.testnet`.  */
    internal var dNSNames: [String]?

    internal init(
        iPAMConfig: EndpointIPAMConfig? = nil, links: [String]? = nil, macAddress: String? = nil, aliases: [String]? = nil, driverOpts: [String: String]? = nil,
        gwPriority: Int64? = nil, networkID: String? = nil, endpointID: String? = nil, gateway: String? = nil, iPAddress: String? = nil, iPPrefixLen: Int? = nil,
        iPv6Gateway: String? = nil, globalIPv6Address: String? = nil, globalIPv6PrefixLen: Int64? = nil, dNSNames: [String]? = nil
    ) {
        self.iPAMConfig = iPAMConfig
        self.links = links
        self.macAddress = macAddress
        self.aliases = aliases
        self.driverOpts = driverOpts
        self.gwPriority = gwPriority
        self.networkID = networkID
        self.endpointID = endpointID
        self.gateway = gateway
        self.iPAddress = iPAddress
        self.iPPrefixLen = iPPrefixLen
        self.iPv6Gateway = iPv6Gateway
        self.globalIPv6Address = globalIPv6Address
        self.globalIPv6PrefixLen = globalIPv6PrefixLen
        self.dNSNames = dNSNames
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case iPAMConfig = "IPAMConfig"
        case links = "Links"
        case macAddress = "MacAddress"
        case aliases = "Aliases"
        case driverOpts = "DriverOpts"
        case gwPriority = "GwPriority"
        case networkID = "NetworkID"
        case endpointID = "EndpointID"
        case gateway = "Gateway"
        case iPAddress = "IPAddress"
        case iPPrefixLen = "IPPrefixLen"
        case iPv6Gateway = "IPv6Gateway"
        case globalIPv6Address = "GlobalIPv6Address"
        case globalIPv6PrefixLen = "GlobalIPv6PrefixLen"
        case dNSNames = "DNSNames"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(iPAMConfig, forKey: .iPAMConfig)
        try keyedContainer.encodeIfPresent(links, forKey: .links)
        try keyedContainer.encodeIfPresent(macAddress, forKey: .macAddress)
        try keyedContainer.encodeIfPresent(aliases, forKey: .aliases)
        try keyedContainer.encodeIfPresent(driverOpts, forKey: .driverOpts)
        try keyedContainer.encodeIfPresent(gwPriority, forKey: .gwPriority)
        try keyedContainer.encodeIfPresent(networkID, forKey: .networkID)
        try keyedContainer.encodeIfPresent(endpointID, forKey: .endpointID)
        try keyedContainer.encodeIfPresent(gateway, forKey: .gateway)
        try keyedContainer.encodeIfPresent(iPAddress, forKey: .iPAddress)
        try keyedContainer.encodeIfPresent(iPPrefixLen, forKey: .iPPrefixLen)
        try keyedContainer.encodeIfPresent(iPv6Gateway, forKey: .iPv6Gateway)
        try keyedContainer.encodeIfPresent(globalIPv6Address, forKey: .globalIPv6Address)
        try keyedContainer.encodeIfPresent(globalIPv6PrefixLen, forKey: .globalIPv6PrefixLen)
        try keyedContainer.encodeIfPresent(dNSNames, forKey: .dNSNames)
    }
}
