//
// EndpointSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Properties that can be configured to access and load balance a service.
internal struct EndpointSpec: Sendable, Content, Hashable {

    internal enum Mode: String, Sendable, Content, Hashable, CaseIterable {
        case vip = "vip"
        case dnsrr = "dnsrr"
    }
    /** The mode of resolution to use for internal load balancing between tasks.  */
    internal var mode: Mode? = .vip
    /** List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.  */
    internal var ports: [EndpointPortConfig]?

    internal init(mode: Mode? = .vip, ports: [EndpointPortConfig]? = nil) {
        self.mode = mode
        self.ports = ports
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mode = "Mode"
        case ports = "Ports"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
        try keyedContainer.encodeIfPresent(ports, forKey: .ports)
    }
}
