//
// EngineDescriptionPluginsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct EngineDescriptionPluginsInner: Sendable, Content, Hashable {

    internal var type: String?
    internal var name: String?

    internal init(type: String? = nil, name: String? = nil) {
        self.type = type
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case name = "Name"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
    }
}
