//
// EngineDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// EngineDescription provides information about an engine.
internal struct EngineDescription: Sendable, Content, Hashable {

    internal var engineVersion: String?
    internal var labels: [String: String]?
    internal var plugins: [EngineDescriptionPluginsInner]?

    internal init(engineVersion: String? = nil, labels: [String: String]? = nil, plugins: [EngineDescriptionPluginsInner]? = nil) {
        self.engineVersion = engineVersion
        self.labels = labels
        self.plugins = plugins
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case engineVersion = "EngineVersion"
        case labels = "Labels"
        case plugins = "Plugins"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(engineVersion, forKey: .engineVersion)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(plugins, forKey: .plugins)
    }
}
