//
// ErrorDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ErrorDetail: Sendable, Content, Hashable {

    internal var code: Int?
    internal var message: String?

    internal init(code: Int? = nil, message: String? = nil) {
        self.code = code
        self.message = message
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(code, forKey: .code)
        try keyedContainer.encodeIfPresent(message, forKey: .message)
    }
}
