//
// EventActor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Actor describes something that generates events, like a container, network, or a volume.
internal struct EventActor: Sendable, Content, Hashable {

    /** The ID of the object emitting the event */
    internal var ID: String?
    /** Various key/value attributes of the object, depending on its type.  */
    internal var attributes: [String: String]?

    internal init(ID: String? = nil, attributes: [String: String]? = nil) {
        self.ID = ID
        self.attributes = attributes
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case attributes = "Attributes"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(attributes, forKey: .attributes)
    }
}
