//
// EventMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// EventMessage represents the information an event contains.
internal struct EventMessage: Sendable, Content, Hashable {

    internal enum ModelType: String, Sendable, Content, Hashable, CaseIterable {
        case builder = "builder"
        case config = "config"
        case container = "container"
        case daemon = "daemon"
        case image = "image"
        case network = "network"
        case node = "node"
        case plugin = "plugin"
        case secret = "secret"
        case service = "service"
        case volume = "volume"
    }
    internal enum Scope: String, Sendable, Content, Hashable, CaseIterable {
        case local = "local"
        case swarm = "swarm"
    }
    /** The type of object emitting the event */
    internal var type: ModelType?
    /** The type of event */
    internal var action: String?
    internal var actor: EventActor?
    /** Scope of the event. Engine events are `local` scope. Cluster (Swarm) events are `swarm` scope.  */
    internal var scope: Scope?
    /** Timestamp of event */
    internal var time: Int64?
    /** Timestamp of event, with nanosecond accuracy */
    internal var timeNano: Int64?

    internal init(type: ModelType? = nil, action: String? = nil, actor: EventActor? = nil, scope: Scope? = nil, time: Int64? = nil, timeNano: Int64? = nil) {
        self.type = type
        self.action = action
        self.actor = actor
        self.scope = scope
        self.time = time
        self.timeNano = timeNano
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case action = "Action"
        case actor = "Actor"
        case scope
        case time
        case timeNano
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(action, forKey: .action)
        try keyedContainer.encodeIfPresent(actor, forKey: .actor)
        try keyedContainer.encodeIfPresent(scope, forKey: .scope)
        try keyedContainer.encodeIfPresent(time, forKey: .time)
        try keyedContainer.encodeIfPresent(timeNano, forKey: .timeNano)
    }
}
