//
// ExecStartConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ExecStartConfig: Sendable, Content, Hashable {

    /** Detach from the command. */
    internal var detach: Bool?
    /** Allocate a pseudo-TTY. */
    internal var tty: Bool?
    /** Initial console size, as an `[height, width]` array. */
    internal var consoleSize: [Int]?

    internal init(detach: Bool? = nil, tty: Bool? = nil, consoleSize: [Int]? = nil) {
        self.detach = detach
        self.tty = tty
        self.consoleSize = consoleSize
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case detach = "Detach"
        case tty = "Tty"
        case consoleSize = "ConsoleSize"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(detach, forKey: .detach)
        try keyedContainer.encodeIfPresent(tty, forKey: .tty)
        try keyedContainer.encodeIfPresent(consoleSize, forKey: .consoleSize)
    }
}
