//
// ExecConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ExecConfig: Sendable, Content, Hashable {

    /** Attach to `stdin` of the exec command. */
    internal var attachStdin: Bool?
    /** Attach to `stdout` of the exec command. */
    internal var attachStdout: Bool?
    /** Attach to `stderr` of the exec command. */
    internal var attachStderr: Bool?
    /** Initial console size, as an `[height, width]` array. */
    internal var consoleSize: [Int]?
    /** Override the key sequence for detaching a container. Format is a single character `[a-Z]` or `ctrl-<value>` where `<value>` is one of: `a-z`, `@`, `^`, `[`, `,` or `_`.  */
    internal var detachKeys: String?
    /** Allocate a pseudo-TTY. */
    internal var tty: Bool?
    /** A list of environment variables in the form `[\"VAR=value\", ...]`.  */
    internal var env: [String]?
    /** Command to run, as a string or array of strings. */
    internal var cmd: [String]?
    /** Runs the exec process with extended privileges. */
    internal var privileged: Bool? = false
    /** The user, and optionally, group to run the exec process inside the container. Format is one of: `user`, `user:group`, `uid`, or `uid:gid`.  */
    internal var user: String?
    /** The working directory for the exec process inside the container.  */
    internal var workingDir: String?

    internal init(
        attachStdin: Bool? = nil, attachStdout: Bool? = nil, attachStderr: Bool? = nil, consoleSize: [Int]? = nil, detachKeys: String? = nil, tty: Bool? = nil,
        env: [String]? = nil, cmd: [String]? = nil, privileged: Bool? = false, user: String? = nil, workingDir: String? = nil
    ) {
        self.attachStdin = attachStdin
        self.attachStdout = attachStdout
        self.attachStderr = attachStderr
        self.consoleSize = consoleSize
        self.detachKeys = detachKeys
        self.tty = tty
        self.env = env
        self.cmd = cmd
        self.privileged = privileged
        self.user = user
        self.workingDir = workingDir
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case attachStdin = "AttachStdin"
        case attachStdout = "AttachStdout"
        case attachStderr = "AttachStderr"
        case consoleSize = "ConsoleSize"
        case detachKeys = "DetachKeys"
        case tty = "Tty"
        case env = "Env"
        case cmd = "Cmd"
        case privileged = "Privileged"
        case user = "User"
        case workingDir = "WorkingDir"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(attachStdin, forKey: .attachStdin)
        try keyedContainer.encodeIfPresent(attachStdout, forKey: .attachStdout)
        try keyedContainer.encodeIfPresent(attachStderr, forKey: .attachStderr)
        try keyedContainer.encodeIfPresent(consoleSize, forKey: .consoleSize)
        try keyedContainer.encodeIfPresent(detachKeys, forKey: .detachKeys)
        try keyedContainer.encodeIfPresent(tty, forKey: .tty)
        try keyedContainer.encodeIfPresent(env, forKey: .env)
        try keyedContainer.encodeIfPresent(cmd, forKey: .cmd)
        try keyedContainer.encodeIfPresent(privileged, forKey: .privileged)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(workingDir, forKey: .workingDir)
    }
}
