//
// FilesystemChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Change in the container&#39;s filesystem.
internal struct FilesystemChange: Sendable, Content, Hashable {

    /** Path to file or directory that has changed.  */
    internal var path: String
    internal var kind: ChangeType

    internal init(path: String, kind: ChangeType) {
        self.path = path
        self.kind = kind
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case kind = "Kind"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(path, forKey: .path)
        try keyedContainer.encode(kind, forKey: .kind)
    }
}
