//
// FirewallInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about the daemon&#39;s firewalling configuration.  This field is currently only used on Linux, and omitted on other platforms.
internal struct FirewallInfo: Sendable, Content, Hashable {

    /** The name of the firewall backend driver.  */
    internal var driver: String?
    /** Information about the firewall backend, provided as \"label\" / \"value\" pairs.  <p><br /></p>  > **Note**: The information returned in this field, including the > formatting of values and labels, should not be considered stable, > and may change without notice.  */
    internal var info: [[String]]?

    internal init(driver: String? = nil, info: [[String]]? = nil) {
        self.driver = driver
        self.info = info
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case driver = "Driver"
        case info = "Info"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(info, forKey: .info)
    }
}
