//
// GenericResourcesInnerDiscreteResourceSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct GenericResourcesInnerDiscreteResourceSpec: Sendable, Content, Hashable {

    internal var kind: String?
    internal var value: Int64?

    internal init(kind: String? = nil, value: Int64? = nil) {
        self.kind = kind
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case kind = "Kind"
        case value = "Value"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(kind, forKey: .kind)
        try keyedContainer.encodeIfPresent(value, forKey: .value)
    }
}
