//
// GenericResourcesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct GenericResourcesInner: Sendable, Content, Hashable {

    internal var namedResourceSpec: GenericResourcesInnerNamedResourceSpec?
    internal var discreteResourceSpec: GenericResourcesInnerDiscreteResourceSpec?

    internal init(namedResourceSpec: GenericResourcesInnerNamedResourceSpec? = nil, discreteResourceSpec: GenericResourcesInnerDiscreteResourceSpec? = nil) {
        self.namedResourceSpec = namedResourceSpec
        self.discreteResourceSpec = discreteResourceSpec
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case namedResourceSpec = "NamedResourceSpec"
        case discreteResourceSpec = "DiscreteResourceSpec"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(namedResourceSpec, forKey: .namedResourceSpec)
        try keyedContainer.encodeIfPresent(discreteResourceSpec, forKey: .discreteResourceSpec)
    }
}
