//
// HealthcheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// HealthcheckResult stores information about a single run of a healthcheck probe
internal struct HealthcheckResult: Sendable, Content, Hashable {

    /** Date and time at which this check started in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var start: Date?
    /** Date and time at which this check ended in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var end: String?
    /** ExitCode meanings:  - `0` healthy - `1` unhealthy - `2` reserved (considered unhealthy) - other values: error running probe  */
    internal var exitCode: Int?
    /** Output from last check */
    internal var output: String?

    internal init(start: Date? = nil, end: String? = nil, exitCode: Int? = nil, output: String? = nil) {
        self.start = start
        self.end = end
        self.exitCode = exitCode
        self.output = output
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case start = "Start"
        case end = "End"
        case exitCode = "ExitCode"
        case output = "Output"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(start, forKey: .start)
        try keyedContainer.encodeIfPresent(end, forKey: .end)
        try keyedContainer.encodeIfPresent(exitCode, forKey: .exitCode)
        try keyedContainer.encodeIfPresent(output, forKey: .output)
    }
}
