//
// Health.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Health stores information about the container&#39;s healthcheck results.
internal struct Health: Sendable, Content, Hashable {

    internal enum Status: String, Sendable, Content, Hashable, CaseIterable {
        case `none` = "none"
        case starting = "starting"
        case healthy = "healthy"
        case unhealthy = "unhealthy"
    }
    /** Status is one of `none`, `starting`, `healthy` or `unhealthy`  - \"none\"      Indicates there is no healthcheck - \"starting\"  Starting indicates that the container is not yet ready - \"healthy\"   Healthy indicates that the container is running correctly - \"unhealthy\" Unhealthy indicates that the container has a problem  */
    internal var status: Status?
    /** FailingStreak is the number of consecutive failures */
    internal var failingStreak: Int?
    /** Log contains the last few results (oldest first)  */
    internal var log: [HealthcheckResult]?

    internal init(status: Status? = nil, failingStreak: Int? = nil, log: [HealthcheckResult]? = nil) {
        self.status = status
        self.failingStreak = failingStreak
        self.log = log
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case status = "Status"
        case failingStreak = "FailingStreak"
        case log = "Log"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
        try keyedContainer.encodeIfPresent(failingStreak, forKey: .failingStreak)
        try keyedContainer.encodeIfPresent(log, forKey: .log)
    }
}
