//
// HealthConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A test to perform to check that the container is healthy. Healthcheck commands should be side-effect free.
internal struct HealthConfig: Sendable, Content, Hashable {

    /** The test to perform. Possible values are:  - `[]` inherit healthcheck from image or parent image - `[\"NONE\"]` disable healthcheck - `[\"CMD\", args...]` exec arguments directly - `[\"CMD-SHELL\", command]` run command with system's default shell  A non-zero exit code indicates a failed healthcheck: - `0` healthy - `1` unhealthy - `2` reserved (treated as unhealthy) - other values: error running probe  */
    internal var test: [String]?
    /** The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    internal var interval: Int64?
    /** The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  If the health check command does not complete within this timeout, the check is considered failed and the health check process is forcibly terminated without a graceful shutdown.  */
    internal var timeout: Int64?
    /** The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.  */
    internal var retries: Int?
    /** Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    internal var startPeriod: Int64?
    /** The time to wait between checks in nanoseconds during the start period. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  */
    internal var startInterval: Int64?

    internal init(test: [String]? = nil, interval: Int64? = nil, timeout: Int64? = nil, retries: Int? = nil, startPeriod: Int64? = nil, startInterval: Int64? = nil) {
        self.test = test
        self.interval = interval
        self.timeout = timeout
        self.retries = retries
        self.startPeriod = startPeriod
        self.startInterval = startInterval
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case test = "Test"
        case interval = "Interval"
        case timeout = "Timeout"
        case retries = "Retries"
        case startPeriod = "StartPeriod"
        case startInterval = "StartInterval"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(test, forKey: .test)
        try keyedContainer.encodeIfPresent(interval, forKey: .interval)
        try keyedContainer.encodeIfPresent(timeout, forKey: .timeout)
        try keyedContainer.encodeIfPresent(retries, forKey: .retries)
        try keyedContainer.encodeIfPresent(startPeriod, forKey: .startPeriod)
        try keyedContainer.encodeIfPresent(startInterval, forKey: .startInterval)
    }
}
