//
// HostConfigAllOfLogConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The logging configuration for this container
internal struct HostConfigAllOfLogConfig: Sendable, Content, Hashable {

    internal enum ModelType: String, Sendable, Content, Hashable, CaseIterable {
        case local = "local"
        case jsonFile = "json-file"
        case syslog = "syslog"
        case journald = "journald"
        case gelf = "gelf"
        case fluentd = "fluentd"
        case awslogs = "awslogs"
        case splunk = "splunk"
        case etwlogs = "etwlogs"
        case `none` = "none"
    }
    /** Name of the logging driver used for the container or \"none\" if logging is disabled. */
    internal var type: ModelType?
    /** Driver-specific configuration options for the logging driver. */
    internal var config: [String: String]?

    internal init(type: ModelType? = nil, config: [String: String]? = nil) {
        self.type = type
        self.config = config
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case config = "Config"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(config, forKey: .config)
    }
}
