//
// IDResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Response to an API call that returns just an Id
internal struct IDResponse: Sendable, Content, Hashable {

    /** The id of the newly created object. */
    internal var id: String

    internal init(id: String) {
        self.id = id
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(id, forKey: .id)
    }
}
