//
// ImageManifestSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// ImageManifestSummary represents a summary of an image manifest.
internal struct ImageManifestSummary: Sendable, Content, Hashable {

    internal enum Kind: String, Sendable, Content, Hashable, CaseIterable {
        case image = "image"
        case attestation = "attestation"
        case unknown = "unknown"
    }
    /** ID is the content-addressable ID of an image and is the same as the digest of the image manifest.  */
    internal var ID: String
    internal var descriptor: OCIDescriptor
    /** Indicates whether all the child content (image config, layers) is fully available locally. */
    internal var available: Bool
    internal var size: ImageManifestSummarySize
    /** The kind of the manifest.  kind         | description -------------|----------------------------------------------------------- image        | Image manifest that can be used to start a container. attestation  | Attestation manifest produced by the Buildkit builder for a specific image manifest.  */
    internal var kind: Kind
    internal var imageData: ImageManifestSummaryImageData?
    internal var attestationData: ImageManifestSummaryAttestationData?

    internal init(
        ID: String, descriptor: OCIDescriptor, available: Bool, size: ImageManifestSummarySize, kind: Kind, imageData: ImageManifestSummaryImageData? = nil,
        attestationData: ImageManifestSummaryAttestationData? = nil
    ) {
        self.ID = ID
        self.descriptor = descriptor
        self.available = available
        self.size = size
        self.kind = kind
        self.imageData = imageData
        self.attestationData = attestationData
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case descriptor = "Descriptor"
        case available = "Available"
        case size = "Size"
        case kind = "Kind"
        case imageData = "ImageData"
        case attestationData = "AttestationData"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(ID, forKey: .ID)
        try keyedContainer.encode(descriptor, forKey: .descriptor)
        try keyedContainer.encode(available, forKey: .available)
        try keyedContainer.encode(size, forKey: .size)
        try keyedContainer.encode(kind, forKey: .kind)
        try keyedContainer.encodeIfPresent(imageData, forKey: .imageData)
        try keyedContainer.encodeIfPresent(attestationData, forKey: .attestationData)
    }
}
