//
// ImageInspectRootFS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about the image&#39;s RootFS, including the layer IDs.
internal struct ImageInspectRootFS: Sendable, Content, Hashable {

    internal var type: String
    internal var layers: [String]?

    internal init(type: String, layers: [String]? = nil) {
        self.type = type
        self.layers = layers
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case layers = "Layers"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(type, forKey: .type)
        try keyedContainer.encodeIfPresent(layers, forKey: .layers)
    }
}
