//
// ImageManifestSummaryAttestationData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The image data for the attestation manifest. This field is only populated when Kind is \&quot;attestation\&quot;.
internal struct ImageManifestSummaryAttestationData: Sendable, Content, Hashable {

    /** The digest of the image manifest that this attestation is for.  */
    internal var `for`: String

    internal init(`for`: String) {
        self.`for` = `for`
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case `for` = "For"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(`for`, forKey: .`for`)
    }
}
