//
// ImageSearchResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ImageSearchResponseItem: Sendable, Content, Hashable {

    internal var description: String?
    internal var isOfficial: Bool?
    /** Whether this repository has automated builds enabled.  <p><br /></p>  > **Deprecated**: This field is deprecated and will always be \"false\".  */
    internal var isAutomated: Bool?
    internal var name: String?
    internal var starCount: Int?

    internal init(description: String? = nil, isOfficial: Bool? = nil, isAutomated: Bool? = nil, name: String? = nil, starCount: Int? = nil) {
        self.description = description
        self.isOfficial = isOfficial
        self.isAutomated = isAutomated
        self.name = name
        self.starCount = starCount
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case isOfficial = "is_official"
        case isAutomated = "is_automated"
        case name
        case starCount = "star_count"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(description, forKey: .description)
        try keyedContainer.encodeIfPresent(isOfficial, forKey: .isOfficial)
        try keyedContainer.encodeIfPresent(isAutomated, forKey: .isAutomated)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(starCount, forKey: .starCount)
    }
}
