//
// ImageInspectMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Additional metadata of the image in the local cache. This information is local to the daemon, and not part of the image itself.
internal struct ImageInspectMetadata: Sendable, Content, Hashable {

    /** Date and time at which the image was last tagged in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  This information is only available if the image was tagged locally, and omitted otherwise.  */
    internal var lastTagTime: String?

    internal init(lastTagTime: String? = nil) {
        self.lastTagTime = lastTagTime
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case lastTagTime = "LastTagTime"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(lastTagTime, forKey: .lastTagTime)
    }
}
