//
// ImageInspect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about an image in the local image cache.
internal struct ImageInspect: Sendable, Content, Hashable {

    /** ID is the content-addressable ID of an image.  This identifier is a content-addressable digest calculated from the image's configuration (which includes the digests of layers used by the image).  Note that this digest differs from the `RepoDigests` below, which holds digests of image manifests that reference the image.  */
    internal var id: String?
    internal var descriptor: OCIDescriptor?
    /** Manifests is a list of image manifests available in this image. It provides a more detailed view of the platform-specific image manifests or other image-attached data like build attestations.  Only available if the daemon provides a multi-platform image store and the `manifests` option is set in the inspect request.  WARNING: This is experimental and may change at any time without any backward compatibility.  */
    internal var manifests: [ImageManifestSummary]?
    /** List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same image, and this list may be empty if no tags reference the image, in which case the image is \"untagged\", in which case it can still be referenced by its ID.  */
    internal var repoTags: [String]?
    /** List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.  */
    internal var repoDigests: [String]?
    /** ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry.  > **Deprecated**: This field is only set when using the deprecated > legacy builder. It is included in API responses for informational > purposes, but should not be depended on as it will be omitted > once the legacy builder is removed.  */
    internal var parent: String?
    /** Optional message that was set when committing or importing the image.  */
    internal var comment: String?
    /** Date and time at which the image was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  This information is only available if present in the image, and omitted otherwise.  */
    internal var created: String?
    /** The version of Docker that was used to build the image.  Depending on how the image was created, this field may be empty.  > **Deprecated**: This field is only set when using the deprecated > legacy builder. It is included in API responses for informational > purposes, but should not be depended on as it will be omitted > once the legacy builder is removed.  */
    internal var dockerVersion: String?
    /** Name of the author that was specified when committing the image, or as specified through MAINTAINER (deprecated) in the Dockerfile.  */
    internal var author: String?
    internal var config: ImageConfig?
    /** Hardware CPU architecture that the image runs on.  */
    internal var architecture: String?
    /** CPU architecture variant (presently ARM-only).  */
    internal var variant: String?
    /** Operating System the image is built to run on.  */
    internal var os: String?
    /** Operating System version the image is built to run on (especially for Windows).  */
    internal var osVersion: String?
    /** Total size of the image including all layers it is composed of.  */
    internal var size: Int64?
    internal var graphDriver: DriverData?
    internal var rootFS: ImageInspectRootFS?
    internal var metadata: ImageInspectMetadata?

    internal init(
        id: String? = nil, descriptor: OCIDescriptor? = nil, manifests: [ImageManifestSummary]? = nil, repoTags: [String]? = nil, repoDigests: [String]? = nil,
        parent: String? = nil, comment: String? = nil, created: String? = nil, dockerVersion: String? = nil, author: String? = nil, config: ImageConfig? = nil,
        architecture: String? = nil, variant: String? = nil, os: String? = nil, osVersion: String? = nil, size: Int64? = nil, graphDriver: DriverData? = nil,
        rootFS: ImageInspectRootFS? = nil, metadata: ImageInspectMetadata? = nil
    ) {
        self.id = id
        self.descriptor = descriptor
        self.manifests = manifests
        self.repoTags = repoTags
        self.repoDigests = repoDigests
        self.parent = parent
        self.comment = comment
        self.created = created
        self.dockerVersion = dockerVersion
        self.author = author
        self.config = config
        self.architecture = architecture
        self.variant = variant
        self.os = os
        self.osVersion = osVersion
        self.size = size
        self.graphDriver = graphDriver
        self.rootFS = rootFS
        self.metadata = metadata
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case descriptor = "Descriptor"
        case manifests = "Manifests"
        case repoTags = "RepoTags"
        case repoDigests = "RepoDigests"
        case parent = "Parent"
        case comment = "Comment"
        case created = "Created"
        case dockerVersion = "DockerVersion"
        case author = "Author"
        case config = "Config"
        case architecture = "Architecture"
        case variant = "Variant"
        case os = "Os"
        case osVersion = "OsVersion"
        case size = "Size"
        case graphDriver = "GraphDriver"
        case rootFS = "RootFS"
        case metadata = "Metadata"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(descriptor, forKey: .descriptor)
        try keyedContainer.encodeIfPresent(manifests, forKey: .manifests)
        try keyedContainer.encodeIfPresent(repoTags, forKey: .repoTags)
        try keyedContainer.encodeIfPresent(repoDigests, forKey: .repoDigests)
        try keyedContainer.encodeIfPresent(parent, forKey: .parent)
        try keyedContainer.encodeIfPresent(comment, forKey: .comment)
        try keyedContainer.encodeIfPresent(created, forKey: .created)
        try keyedContainer.encodeIfPresent(dockerVersion, forKey: .dockerVersion)
        try keyedContainer.encodeIfPresent(author, forKey: .author)
        try keyedContainer.encodeIfPresent(config, forKey: .config)
        try keyedContainer.encodeIfPresent(architecture, forKey: .architecture)
        try keyedContainer.encodeIfPresent(variant, forKey: .variant)
        try keyedContainer.encodeIfPresent(os, forKey: .os)
        try keyedContainer.encodeIfPresent(osVersion, forKey: .osVersion)
        try keyedContainer.encodeIfPresent(size, forKey: .size)
        try keyedContainer.encodeIfPresent(graphDriver, forKey: .graphDriver)
        try keyedContainer.encodeIfPresent(rootFS, forKey: .rootFS)
        try keyedContainer.encodeIfPresent(metadata, forKey: .metadata)
    }
}
