//
// ImageID.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Image ID or Digest
internal struct ImageID: Sendable, Content, Hashable {

    internal var ID: String?

    internal init(ID: String? = nil) {
        self.ID = ID
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
    }
}
