//
// ImageHistoryResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// individual image layer information in response to ImageHistory operation
internal struct ImageHistoryResponseItem: Sendable, Content, Hashable {

    internal var id: String
    internal var created: Int64
    internal var createdBy: String
    internal var tags: [String]
    internal var size: Int64
    internal var comment: String

    internal init(id: String, created: Int64, createdBy: String, tags: [String], size: Int64, comment: String) {
        self.id = id
        self.created = created
        self.createdBy = createdBy
        self.tags = tags
        self.size = size
        self.comment = comment
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case created = "Created"
        case createdBy = "CreatedBy"
        case tags = "Tags"
        case size = "Size"
        case comment = "Comment"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(id, forKey: .id)
        try keyedContainer.encode(created, forKey: .created)
        try keyedContainer.encode(createdBy, forKey: .createdBy)
        try keyedContainer.encode(tags, forKey: .tags)
        try keyedContainer.encode(size, forKey: .size)
        try keyedContainer.encode(comment, forKey: .comment)
    }
}
