//
// ImagePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ImagePruneResponse: Sendable, Content, Hashable {

    /** Images that were deleted */
    internal var imagesDeleted: [DockerImageDeleteResponseItem]?
    /** Disk space reclaimed in bytes */
    internal var spaceReclaimed: Int64?

    internal init(imagesDeleted: [DockerImageDeleteResponseItem]? = nil, spaceReclaimed: Int64? = nil) {
        self.imagesDeleted = imagesDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case imagesDeleted = "ImagesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(imagesDeleted, forKey: .imagesDeleted)
        try keyedContainer.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}
