//
// ImageManifestSummarySize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ImageManifestSummarySize: Sendable, Content, Hashable {

    /** Total is the total size (in bytes) of all the locally present data (both distributable and non-distributable) that's related to this manifest and its children. This equal to the sum of [Content] size AND all the sizes in the [Size] struct present in the Kind-specific data struct. For example, for an image kind (Kind == \"image\") this would include the size of the image content and unpacked image snapshots ([Size.Content] + [ImageData.Size.Unpacked]).  */
    internal var total: Int64
    /** Content is the size (in bytes) of all the locally present content in the content store (e.g. image config, layers) referenced by this manifest and its children. This only includes blobs in the content store.  */
    internal var content: Int64

    internal init(total: Int64, content: Int64) {
        self.total = total
        self.content = content
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case total = "Total"
        case content = "Content"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(total, forKey: .total)
        try keyedContainer.encode(content, forKey: .content)
    }
}
