//
// ImageManifestSummaryImageData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The image data for the image manifest. This field is only populated when Kind is \&quot;image\&quot;.
internal struct ImageManifestSummaryImageData: Sendable, Content, Hashable {

    internal var platform: OCIPlatform?
    /** The IDs of the containers that are using this image.  */
    internal var containers: [String]
    internal var size: ImageManifestSummaryImageDataSize

    internal init(platform: OCIPlatform?, containers: [String], size: ImageManifestSummaryImageDataSize) {
        self.platform = platform
        self.containers = containers
        self.size = size
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case platform = "Platform"
        case containers = "Containers"
        case size = "Size"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(platform, forKey: .platform)
        try keyedContainer.encode(containers, forKey: .containers)
        try keyedContainer.encode(size, forKey: .size)
    }
}
