//
// ImageConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Configuration of the image. These fields are used as defaults when starting a container from the image.
internal struct ImageConfig: Sendable, Content, Hashable {

    /** The user that commands are run as inside the container. */
    internal var user: String?
    /** An object mapping ports to an empty object in the form:  `{\"<port>/<tcp|udp|sctp>\": {}}`  */
    internal var exposedPorts: [String: JSONValue]?
    /** A list of environment variables to set inside the container in the form `[\"VAR=value\", ...]`. A variable without `=` is removed from the environment, rather than to have an empty value.  */
    internal var env: [String]?
    /** Command to run specified as a string or an array of strings.  */
    internal var cmd: [String]?
    internal var healthcheck: HealthConfig?
    /** Command is already escaped (Windows only) */
    internal var argsEscaped: Bool? = false
    /** An object mapping mount point paths inside the container to empty objects.  */
    internal var volumes: [String: JSONValue]?
    /** The working directory for commands to run in. */
    internal var workingDir: String?
    /** The entry point for the container as a string or an array of strings.  If the array consists of exactly one empty string (`[\"\"]`) then the entry point is reset to system default (i.e., the entry point used by docker when there is no `ENTRYPOINT` instruction in the `Dockerfile`).  */
    internal var entrypoint: [String]?
    /** `ONBUILD` metadata that were defined in the image's `Dockerfile`.  */
    internal var onBuild: [String]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** Signal to stop a container as a string or unsigned integer.  */
    internal var stopSignal: String?
    /** Shell for when `RUN`, `CMD`, and `ENTRYPOINT` uses a shell.  */
    internal var shell: [String]?

    internal init(
        user: String? = nil, exposedPorts: [String: JSONValue]? = nil, env: [String]? = nil, cmd: [String]? = nil, healthcheck: HealthConfig? = nil, argsEscaped: Bool? = false,
        volumes: [String: JSONValue]? = nil, workingDir: String? = nil, entrypoint: [String]? = nil, onBuild: [String]? = nil, labels: [String: String]? = nil,
        stopSignal: String? = nil, shell: [String]? = nil
    ) {
        self.user = user
        self.exposedPorts = exposedPorts
        self.env = env
        self.cmd = cmd
        self.healthcheck = healthcheck
        self.argsEscaped = argsEscaped
        self.volumes = volumes
        self.workingDir = workingDir
        self.entrypoint = entrypoint
        self.onBuild = onBuild
        self.labels = labels
        self.stopSignal = stopSignal
        self.shell = shell
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case user = "User"
        case exposedPorts = "ExposedPorts"
        case env = "Env"
        case cmd = "Cmd"
        case healthcheck = "Healthcheck"
        case argsEscaped = "ArgsEscaped"
        case volumes = "Volumes"
        case workingDir = "WorkingDir"
        case entrypoint = "Entrypoint"
        case onBuild = "OnBuild"
        case labels = "Labels"
        case stopSignal = "StopSignal"
        case shell = "Shell"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(exposedPorts, forKey: .exposedPorts)
        try keyedContainer.encodeIfPresent(env, forKey: .env)
        try keyedContainer.encodeIfPresent(cmd, forKey: .cmd)
        try keyedContainer.encodeIfPresent(healthcheck, forKey: .healthcheck)
        try keyedContainer.encodeIfPresent(argsEscaped, forKey: .argsEscaped)
        try keyedContainer.encodeIfPresent(volumes, forKey: .volumes)
        try keyedContainer.encodeIfPresent(workingDir, forKey: .workingDir)
        try keyedContainer.encodeIfPresent(entrypoint, forKey: .entrypoint)
        try keyedContainer.encodeIfPresent(onBuild, forKey: .onBuild)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(stopSignal, forKey: .stopSignal)
        try keyedContainer.encodeIfPresent(shell, forKey: .shell)
    }
}
