//
// ImageManifestSummaryImageDataSize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ImageManifestSummaryImageDataSize: Sendable, Content, Hashable {

    /** Unpacked is the size (in bytes) of the locally unpacked (uncompressed) image content that's directly usable by the containers running this image. It's independent of the distributable content - e.g. the image might still have an unpacked data that's still used by some container even when the distributable/compressed content is already gone.  */
    internal var unpacked: Int64

    internal init(unpacked: Int64) {
        self.unpacked = unpacked
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case unpacked = "Unpacked"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(unpacked, forKey: .unpacked)
    }
}
