//
// IPAMConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct IPAMConfig: Sendable, Content, Hashable {

    internal var subnet: String?
    internal var iPRange: String?
    internal var gateway: String?
    internal var auxiliaryAddresses: [String: String]?

    internal init(subnet: String? = nil, iPRange: String? = nil, gateway: String? = nil, auxiliaryAddresses: [String: String]? = nil) {
        self.subnet = subnet
        self.iPRange = iPRange
        self.gateway = gateway
        self.auxiliaryAddresses = auxiliaryAddresses
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case subnet = "Subnet"
        case iPRange = "IPRange"
        case gateway = "Gateway"
        case auxiliaryAddresses = "AuxiliaryAddresses"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(subnet, forKey: .subnet)
        try keyedContainer.encodeIfPresent(iPRange, forKey: .iPRange)
        try keyedContainer.encodeIfPresent(gateway, forKey: .gateway)
        try keyedContainer.encodeIfPresent(auxiliaryAddresses, forKey: .auxiliaryAddresses)
    }
}
