//
// IPAM.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct IPAM: Sendable, Content, Hashable {

    /** Name of the IPAM driver to use. */
    internal var driver: String? = "default"
    /** List of IPAM configuration options, specified as a map:  ``` {\"Subnet\": <CIDR>, \"IPRange\": <CIDR>, \"Gateway\": <IP address>, \"AuxAddress\": <device_name:IP address>} ```  */
    internal var config: [IPAMConfig]?
    /** Driver-specific options, specified as a map. */
    internal var options: [String: String]?

    internal init(driver: String? = "default", config: [IPAMConfig]? = nil, options: [String: String]? = nil) {
        self.driver = driver
        self.config = config
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case driver = "Driver"
        case config = "Config"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(config, forKey: .config)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
