//
// JoinTokens.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// JoinTokens contains the tokens workers and managers need to join the swarm.
internal struct JoinTokens: Sendable, Content, Hashable {

    /** The token workers can use to join the swarm.  */
    internal var worker: String?
    /** The token managers can use to join the swarm.  */
    internal var manager: String?

    internal init(worker: String? = nil, manager: String? = nil) {
        self.worker = worker
        self.manager = manager
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case worker = "Worker"
        case manager = "Manager"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(worker, forKey: .worker)
        try keyedContainer.encodeIfPresent(manager, forKey: .manager)
    }
}
