//
// Limit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// An object describing a limit on resources which can be requested by a task.
internal struct Limit: Sendable, Content, Hashable {

    internal var nanoCPUs: Int64?
    internal var memoryBytes: Int64?
    /** Limits the maximum number of PIDs in the container. Set `0` for unlimited.  */
    internal var pids: Int64? = 0

    internal init(nanoCPUs: Int64? = nil, memoryBytes: Int64? = nil, pids: Int64? = 0) {
        self.nanoCPUs = nanoCPUs
        self.memoryBytes = memoryBytes
        self.pids = pids
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case nanoCPUs = "NanoCPUs"
        case memoryBytes = "MemoryBytes"
        case pids = "Pids"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(nanoCPUs, forKey: .nanoCPUs)
        try keyedContainer.encodeIfPresent(memoryBytes, forKey: .memoryBytes)
        try keyedContainer.encodeIfPresent(pids, forKey: .pids)
    }
}
