//
// LocalNodeState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Current local status of this node.
internal enum LocalNodeState: String, Sendable, Content, Hashable, CaseIterable {
    case empty = ""
    case inactive = "inactive"
    case pending = "pending"
    case active = "active"
    case error = "error"
    case locked = "locked"
}
