//
// ManagerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// ManagerStatus represents the status of a manager.  It provides the current status of a node&#39;s manager component, if the node is a manager.
internal struct ManagerStatus: Sendable, Content, Hashable {

    internal var leader: Bool? = false
    internal var reachability: Reachability?
    /** The IP address and port at which the manager is reachable.  */
    internal var addr: String?

    internal init(leader: Bool? = false, reachability: Reachability? = nil, addr: String? = nil) {
        self.leader = leader
        self.reachability = reachability
        self.addr = addr
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case leader = "Leader"
        case reachability = "Reachability"
        case addr = "Addr"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(leader, forKey: .leader)
        try keyedContainer.encodeIfPresent(reachability, forKey: .reachability)
        try keyedContainer.encodeIfPresent(addr, forKey: .addr)
    }
}
