//
// MountPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container.
internal struct MountPoint: Sendable, Content, Hashable {

    /** The mount type:  - `bind` a mount of a file or directory from the host into the container. - `cluster` a Swarm cluster volume. - `image` an OCI image. - `npipe` a named pipe from the host into the container. - `tmpfs` a `tmpfs`. - `volume` a docker volume with the given `Name`.  */
    internal var type: MountType?
    /** Name is the name reference to the underlying data defined by `Source` e.g., the volume name.  */
    internal var name: String?
    /** Source location of the mount.  For volumes, this contains the storage location of the volume (within `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains the source (host) part of the bind-mount. For `tmpfs` mount points, this field is empty.  */
    internal var source: String?
    /** Destination is the path relative to the container root (`/`) where the `Source` is mounted inside the container.  */
    internal var destination: String?
    /** Driver is the volume driver used to create the volume (if it is a volume).  */
    internal var driver: String?
    /** Mode is a comma separated list of options supplied by the user when creating the bind/volume mount.  The default is platform-specific (`\"z\"` on Linux, empty on Windows).  */
    internal var mode: String?
    /** Whether the mount is mounted writable (read-write).  */
    internal var RW: Bool?
    /** Propagation describes how mounts are propagated from the host into the mount point, and vice-versa. Refer to the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) for details. This field is not used on Windows.  */
    internal var propagation: String?

    internal init(
        type: MountType? = nil, name: String? = nil, source: String? = nil, destination: String? = nil, driver: String? = nil, mode: String? = nil, RW: Bool? = nil,
        propagation: String? = nil
    ) {
        self.type = type
        self.name = name
        self.source = source
        self.destination = destination
        self.driver = driver
        self.mode = mode
        self.RW = RW
        self.propagation = propagation
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
        case name = "Name"
        case source = "Source"
        case destination = "Destination"
        case driver = "Driver"
        case mode = "Mode"
        case RW
        case propagation = "Propagation"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(source, forKey: .source)
        try keyedContainer.encodeIfPresent(destination, forKey: .destination)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
        try keyedContainer.encodeIfPresent(RW, forKey: .RW)
        try keyedContainer.encodeIfPresent(propagation, forKey: .propagation)
    }
}
