//
// MountBindOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Optional configuration for the &#x60;bind&#x60; type.
internal struct MountBindOptions: Sendable, Content, Hashable {

    internal enum Propagation: String, Sendable, Content, Hashable, CaseIterable {
        case `private` = "private"
        case rprivate = "rprivate"
        case shared = "shared"
        case rshared = "rshared"
        case slave = "slave"
        case rslave = "rslave"
    }
    /** A propagation mode with the value `[r]private`, `[r]shared`, or `[r]slave`. */
    internal var propagation: Propagation?
    /** Disable recursive bind mount. */
    internal var nonRecursive: Bool? = false
    /** Create mount point on host if missing */
    internal var createMountpoint: Bool? = false
    /** Make the mount non-recursively read-only, but still leave the mount recursive (unless NonRecursive is set to `true` in conjunction).  Added in v1.44, before that version all read-only mounts were non-recursive by default. To match the previous behaviour this will default to `true` for clients on versions prior to v1.44.  */
    internal var readOnlyNonRecursive: Bool? = false
    /** Raise an error if the mount cannot be made recursively read-only. */
    internal var readOnlyForceRecursive: Bool? = false

    internal init(
        propagation: Propagation? = nil, nonRecursive: Bool? = false, createMountpoint: Bool? = false, readOnlyNonRecursive: Bool? = false, readOnlyForceRecursive: Bool? = false
    ) {
        self.propagation = propagation
        self.nonRecursive = nonRecursive
        self.createMountpoint = createMountpoint
        self.readOnlyNonRecursive = readOnlyNonRecursive
        self.readOnlyForceRecursive = readOnlyForceRecursive
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case propagation = "Propagation"
        case nonRecursive = "NonRecursive"
        case createMountpoint = "CreateMountpoint"
        case readOnlyNonRecursive = "ReadOnlyNonRecursive"
        case readOnlyForceRecursive = "ReadOnlyForceRecursive"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(propagation, forKey: .propagation)
        try keyedContainer.encodeIfPresent(nonRecursive, forKey: .nonRecursive)
        try keyedContainer.encodeIfPresent(createMountpoint, forKey: .createMountpoint)
        try keyedContainer.encodeIfPresent(readOnlyNonRecursive, forKey: .readOnlyNonRecursive)
        try keyedContainer.encodeIfPresent(readOnlyForceRecursive, forKey: .readOnlyForceRecursive)
    }
}
