//
// MountVolumeOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Optional configuration for the &#x60;volume&#x60; type.
internal struct MountVolumeOptions: Sendable, Content, Hashable {

    /** Populate volume with data from the target. */
    internal var noCopy: Bool? = false
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    internal var driverConfig: MountVolumeOptionsDriverConfig?
    /** Source path inside the volume. Must be relative without any back traversals. */
    internal var subpath: String?

    internal init(noCopy: Bool? = false, labels: [String: String]? = nil, driverConfig: MountVolumeOptionsDriverConfig? = nil, subpath: String? = nil) {
        self.noCopy = noCopy
        self.labels = labels
        self.driverConfig = driverConfig
        self.subpath = subpath
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case noCopy = "NoCopy"
        case labels = "Labels"
        case driverConfig = "DriverConfig"
        case subpath = "Subpath"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(noCopy, forKey: .noCopy)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(driverConfig, forKey: .driverConfig)
        try keyedContainer.encodeIfPresent(subpath, forKey: .subpath)
    }
}
