//
// Mount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Mount: Sendable, Content, Hashable {

    /** Container path. */
    internal var target: String?
    /** Mount source (e.g. a volume name, a host path). The source cannot be specified when using `Type=tmpfs`. For `Type=bind`, the source path must either exist, or the `CreateMountpoint` must be set to `true` to create the source path on the host if missing.  For `Type=npipe`, the pipe must exist prior to creating the container. */
    internal var source: String?
    /** The mount type. Available types:  - `bind` Mounts a file or directory from the host into the container. The `Source` must exist prior to creating the container. - `cluster` a Swarm cluster volume - `image` Mounts an image. - `npipe` Mounts a named pipe from the host into the container. The `Source` must exist prior to creating the container. - `tmpfs` Create a tmpfs with the given options. The mount `Source` cannot be specified for tmpfs. - `volume` Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed.  */
    internal var type: MountType?
    /** Whether the mount should be read-only. */
    internal var readOnly: Bool?
    /** The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`. */
    internal var consistency: String?
    internal var bindOptions: MountBindOptions?
    internal var volumeOptions: MountVolumeOptions?
    internal var imageOptions: MountImageOptions?
    internal var tmpfsOptions: MountTmpfsOptions?

    internal init(
        target: String? = nil, source: String? = nil, type: MountType? = nil, readOnly: Bool? = nil, consistency: String? = nil, bindOptions: MountBindOptions? = nil,
        volumeOptions: MountVolumeOptions? = nil, imageOptions: MountImageOptions? = nil, tmpfsOptions: MountTmpfsOptions? = nil
    ) {
        self.target = target
        self.source = source
        self.type = type
        self.readOnly = readOnly
        self.consistency = consistency
        self.bindOptions = bindOptions
        self.volumeOptions = volumeOptions
        self.imageOptions = imageOptions
        self.tmpfsOptions = tmpfsOptions
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case target = "Target"
        case source = "Source"
        case type = "Type"
        case readOnly = "ReadOnly"
        case consistency = "Consistency"
        case bindOptions = "BindOptions"
        case volumeOptions = "VolumeOptions"
        case imageOptions = "ImageOptions"
        case tmpfsOptions = "TmpfsOptions"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(target, forKey: .target)
        try keyedContainer.encodeIfPresent(source, forKey: .source)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(readOnly, forKey: .readOnly)
        try keyedContainer.encodeIfPresent(consistency, forKey: .consistency)
        try keyedContainer.encodeIfPresent(bindOptions, forKey: .bindOptions)
        try keyedContainer.encodeIfPresent(volumeOptions, forKey: .volumeOptions)
        try keyedContainer.encodeIfPresent(imageOptions, forKey: .imageOptions)
        try keyedContainer.encodeIfPresent(tmpfsOptions, forKey: .tmpfsOptions)
    }
}
