//
// MountTmpfsOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Optional configuration for the &#x60;tmpfs&#x60; type.
internal struct MountTmpfsOptions: Sendable, Content, Hashable {

    /** The size for the tmpfs mount in bytes. */
    internal var sizeBytes: Int64?
    /** The permission mode for the tmpfs mount in an integer. The value must not be in octal format (e.g. 755) but rather the decimal representation of the octal value (e.g. 493).  */
    internal var mode: Int?
    /** The options to be passed to the tmpfs mount. An array of arrays. Flag options should be provided as 1-length arrays. Other types should be provided as as 2-length arrays, where the first item is the key and the second the value.  */
    internal var options: [[String]]?

    internal init(sizeBytes: Int64? = nil, mode: Int? = nil, options: [[String]]? = nil) {
        self.sizeBytes = sizeBytes
        self.mode = mode
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case sizeBytes = "SizeBytes"
        case mode = "Mode"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(sizeBytes, forKey: .sizeBytes)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
