//
// MountVolumeOptionsDriverConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Map of driver specific options
internal struct MountVolumeOptionsDriverConfig: Sendable, Content, Hashable {

    /** Name of the driver to use to create the volume. */
    internal var name: String?
    /** key/value map of driver specific options. */
    internal var options: [String: String]?

    internal init(name: String? = nil, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
