//
// MountType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The mount type. Available types:  - &#x60;bind&#x60; a mount of a file or directory from the host into the container. - &#x60;cluster&#x60; a Swarm cluster volume. - &#x60;image&#x60; an OCI image. - &#x60;npipe&#x60; a named pipe from the host into the container. - &#x60;tmpfs&#x60; a &#x60;tmpfs&#x60;. - &#x60;volume&#x60; a docker volume with the given &#x60;Name&#x60;.
internal enum MountType: String, Sendable, Content, Hashable, CaseIterable {
    case bind = "bind"
    case cluster = "cluster"
    case image = "image"
    case npipe = "npipe"
    case tmpfs = "tmpfs"
    case volume = "volume"
}
