//
// NetworkConnectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NetworkConnectRequest: Sendable, Content, Hashable {

    /** The ID or name of the container to connect to the network. */
    internal var container: String?
    internal var endpointConfig: EndpointSettings?

    internal init(container: String? = nil, endpointConfig: EndpointSettings? = nil) {
        self.container = container
        self.endpointConfig = endpointConfig
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
        case endpointConfig = "EndpointConfig"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(container, forKey: .container)
        try keyedContainer.encodeIfPresent(endpointConfig, forKey: .endpointConfig)
    }
}
