//
// NetworkContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NetworkContainer: Sendable, Content, Hashable {

    internal var name: String?
    internal var endpointID: String?
    internal var macAddress: String?
    internal var iPv4Address: String?
    internal var iPv6Address: String?

    internal init(name: String? = nil, endpointID: String? = nil, macAddress: String? = nil, iPv4Address: String? = nil, iPv6Address: String? = nil) {
        self.name = name
        self.endpointID = endpointID
        self.macAddress = macAddress
        self.iPv4Address = iPv4Address
        self.iPv6Address = iPv6Address
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case endpointID = "EndpointID"
        case macAddress = "MacAddress"
        case iPv4Address = "IPv4Address"
        case iPv6Address = "IPv6Address"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(endpointID, forKey: .endpointID)
        try keyedContainer.encodeIfPresent(macAddress, forKey: .macAddress)
        try keyedContainer.encodeIfPresent(iPv4Address, forKey: .iPv4Address)
        try keyedContainer.encodeIfPresent(iPv6Address, forKey: .iPv6Address)
    }
}
