//
// NetworkCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NetworkCreateRequest: Sendable, Content, Hashable {

    /** The network's name. */
    internal var name: String
    /** Name of the network driver plugin to use. */
    internal var driver: String? = "bridge"
    /** The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level).  */
    internal var scope: String?
    /** Restrict external access to the network. */
    internal var `internal`: Bool?
    /** Globally scoped network is manually attachable by regular containers from workers in swarm mode.  */
    internal var attachable: Bool?
    /** Ingress network is the network which provides the routing-mesh in swarm mode.  */
    internal var ingress: Bool?
    /** Creates a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.  */
    internal var configOnly: Bool? = false
    internal var configFrom: ConfigReference?
    internal var IPAM: IPAM?
    /** Enable IPv4 on the network. */
    internal var enableIPv4: Bool?
    /** Enable IPv6 on the network. */
    internal var enableIPv6: Bool?
    /** Network specific options to be used by the drivers. */
    internal var options: [String: String]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?

    internal init(
        name: String, driver: String? = "bridge", scope: String? = nil, `internal`: Bool? = nil, attachable: Bool? = nil, ingress: Bool? = nil, configOnly: Bool? = false,
        configFrom: ConfigReference? = nil, IPAM: IPAM? = nil, enableIPv4: Bool? = nil, enableIPv6: Bool? = nil, options: [String: String]? = nil, labels: [String: String]? = nil
    ) {
        self.name = name
        self.driver = driver
        self.scope = scope
        self.`internal` = `internal`
        self.attachable = attachable
        self.ingress = ingress
        self.configOnly = configOnly
        self.configFrom = configFrom
        self.IPAM = IPAM
        self.enableIPv4 = enableIPv4
        self.enableIPv6 = enableIPv6
        self.options = options
        self.labels = labels
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case driver = "Driver"
        case scope = "Scope"
        case `internal` = "Internal"
        case attachable = "Attachable"
        case ingress = "Ingress"
        case configOnly = "ConfigOnly"
        case configFrom = "ConfigFrom"
        case IPAM
        case enableIPv4 = "EnableIPv4"
        case enableIPv6 = "EnableIPv6"
        case options = "Options"
        case labels = "Labels"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(scope, forKey: .scope)
        try keyedContainer.encodeIfPresent(`internal`, forKey: .`internal`)
        try keyedContainer.encodeIfPresent(attachable, forKey: .attachable)
        try keyedContainer.encodeIfPresent(ingress, forKey: .ingress)
        try keyedContainer.encodeIfPresent(configOnly, forKey: .configOnly)
        try keyedContainer.encodeIfPresent(configFrom, forKey: .configFrom)
        try keyedContainer.encodeIfPresent(IPAM, forKey: .IPAM)
        try keyedContainer.encodeIfPresent(enableIPv4, forKey: .enableIPv4)
        try keyedContainer.encodeIfPresent(enableIPv6, forKey: .enableIPv6)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
    }
}
