//
// NetworkPruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NetworkPruneResponse: Sendable, Content, Hashable {

    /** Networks that were deleted */
    internal var networksDeleted: [String]?

    internal init(networksDeleted: [String]? = nil) {
        self.networksDeleted = networksDeleted
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case networksDeleted = "NetworksDeleted"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(networksDeleted, forKey: .networksDeleted)
    }
}
