//
// NetworkDisconnectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NetworkDisconnectRequest: Sendable, Content, Hashable {

    /** The ID or name of the container to disconnect from the network.  */
    internal var container: String?
    /** Force the container to disconnect from the network.  */
    internal var force: Bool?

    internal init(container: String? = nil, force: Bool? = nil) {
        self.container = container
        self.force = force
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case container = "Container"
        case force = "Force"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(container, forKey: .container)
        try keyedContainer.encodeIfPresent(force, forKey: .force)
    }
}
