//
// NetworkCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// OK response to NetworkCreate operation
internal struct NetworkCreateResponse: Sendable, Content, Hashable {

    /** The ID of the created network. */
    internal var id: String
    /** Warnings encountered when creating the container */
    internal var warning: String

    internal init(id: String, warning: String) {
        self.id = id
        self.warning = warning
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case warning = "Warning"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(id, forKey: .id)
        try keyedContainer.encode(warning, forKey: .warning)
    }
}
