//
// NetworkingConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// NetworkingConfig represents the container&#39;s networking configuration for each of its interfaces. It is used for the networking configs specified in the &#x60;docker create&#x60; and &#x60;docker network connect&#x60; commands.
internal struct NetworkingConfig: Sendable, Content, Hashable {

    /** A mapping of network name to endpoint configuration for that network. The endpoint configuration can be left empty to connect to that network with no particular endpoint configuration.  */
    internal var endpointsConfig: [String: EndpointSettings]?

    internal init(endpointsConfig: [String: EndpointSettings]? = nil) {
        self.endpointsConfig = endpointsConfig
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointsConfig = "EndpointsConfig"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(endpointsConfig, forKey: .endpointsConfig)
    }
}
