//
// Network.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Network: Sendable, Content, Hashable {

    /** Name of the network.  */
    internal var name: String?
    /** ID that uniquely identifies a network on a single machine.  */
    internal var id: String?
    /** Date and time at which the network was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var created: String?
    /** The level at which the network exists (e.g. `swarm` for cluster-wide or `local` for machine level)  */
    internal var scope: String?
    /** The name of the driver used to create the network (e.g. `bridge`, `overlay`).  */
    internal var driver: String?
    /** Whether the network was created with IPv4 enabled.  */
    internal var enableIPv4: Bool?
    /** Whether the network was created with IPv6 enabled.  */
    internal var enableIPv6: Bool?
    internal var IPAM: IPAM?
    /** Whether the network is created to only allow internal networking connectivity.  */
    internal var `internal`: Bool? = false
    /** Whether a global / swarm scope network is manually attachable by regular containers from workers in swarm mode.  */
    internal var attachable: Bool? = false
    /** Whether the network is providing the routing-mesh for the swarm cluster.  */
    internal var ingress: Bool? = false
    internal var configFrom: ConfigReference?
    /** Whether the network is a config-only network. Config-only networks are placeholder networks for network configurations to be used by other networks. Config-only networks cannot be used directly to run containers or services.  */
    internal var configOnly: Bool? = false
    /** Contains endpoints attached to the network.  */
    internal var containers: [String: NetworkContainer]?
    /** Network-specific options uses when creating the network.  */
    internal var options: [String: String]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** List of peer nodes for an overlay network. This field is only present for overlay networks, and omitted for other network types.  */
    internal var peers: [PeerInfo]?

    internal init(
        name: String? = nil, id: String? = nil, created: String? = nil, scope: String? = nil, driver: String? = nil, enableIPv4: Bool? = nil, enableIPv6: Bool? = nil,
        IPAM: IPAM? = nil, `internal`: Bool? = false, attachable: Bool? = false, ingress: Bool? = false, configFrom: ConfigReference? = nil, configOnly: Bool? = false,
        containers: [String: NetworkContainer]? = nil, options: [String: String]? = nil, labels: [String: String]? = nil, peers: [PeerInfo]? = nil
    ) {
        self.name = name
        self.id = id
        self.created = created
        self.scope = scope
        self.driver = driver
        self.enableIPv4 = enableIPv4
        self.enableIPv6 = enableIPv6
        self.IPAM = IPAM
        self.`internal` = `internal`
        self.attachable = attachable
        self.ingress = ingress
        self.configFrom = configFrom
        self.configOnly = configOnly
        self.containers = containers
        self.options = options
        self.labels = labels
        self.peers = peers
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case id = "Id"
        case created = "Created"
        case scope = "Scope"
        case driver = "Driver"
        case enableIPv4 = "EnableIPv4"
        case enableIPv6 = "EnableIPv6"
        case IPAM
        case `internal` = "Internal"
        case attachable = "Attachable"
        case ingress = "Ingress"
        case configFrom = "ConfigFrom"
        case configOnly = "ConfigOnly"
        case containers = "Containers"
        case options = "Options"
        case labels = "Labels"
        case peers = "Peers"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encodeIfPresent(created, forKey: .created)
        try keyedContainer.encodeIfPresent(scope, forKey: .scope)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(enableIPv4, forKey: .enableIPv4)
        try keyedContainer.encodeIfPresent(enableIPv6, forKey: .enableIPv6)
        try keyedContainer.encodeIfPresent(IPAM, forKey: .IPAM)
        try keyedContainer.encodeIfPresent(`internal`, forKey: .`internal`)
        try keyedContainer.encodeIfPresent(attachable, forKey: .attachable)
        try keyedContainer.encodeIfPresent(ingress, forKey: .ingress)
        try keyedContainer.encodeIfPresent(configFrom, forKey: .configFrom)
        try keyedContainer.encodeIfPresent(configOnly, forKey: .configOnly)
        try keyedContainer.encodeIfPresent(containers, forKey: .containers)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(peers, forKey: .peers)
    }
}
