//
// NetworkSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// NetworkSettings exposes the network settings in the API
internal struct NetworkSettings: Sendable, Content, Hashable {

    /** Name of the default bridge interface when dockerd's --bridge flag is set.  Deprecated: This field is only set when the daemon is started with the --bridge flag specified.  */
    internal var bridge: String?
    /** SandboxID uniquely represents a container's network stack. */
    internal var sandboxID: String?
    /** Indicates if hairpin NAT should be enabled on the virtual interface.  Deprecated: This field is never set and will be removed in a future release.  */
    internal var hairpinMode: Bool?
    /** IPv6 unicast address using the link-local prefix.  Deprecated: This field is never set and will be removed in a future release.  */
    internal var linkLocalIPv6Address: String?
    /** Prefix length of the IPv6 unicast address.  Deprecated: This field is never set and will be removed in a future release.  */
    internal var linkLocalIPv6PrefixLen: Int?
    /** PortMap describes the mapping of container ports to host ports, using the container's port-number and protocol as key in the format `<port>/<protocol>`, for example, `80/udp`.  If a container's port is mapped for multiple protocols, separate entries are added to the mapping table.  */
    internal var ports: [String: [PortBinding]?]?
    /** SandboxKey is the full path of the netns handle */
    internal var sandboxKey: String?
    /** Deprecated: This field is never set and will be removed in a future release. */
    internal var secondaryIPAddresses: [Address]?
    /** Deprecated: This field is never set and will be removed in a future release. */
    internal var secondaryIPv6Addresses: [Address]?
    /** EndpointID uniquely represents a service endpoint in a Sandbox.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var endpointID: String?
    /** Gateway address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var gateway: String?
    /** Global IPv6 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var globalIPv6Address: String?
    /** Mask length of the global IPv6 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var globalIPv6PrefixLen: Int?
    /** IPv4 address for the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var iPAddress: String?
    /** Mask length of the IPv4 address.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var iPPrefixLen: Int?
    /** IPv6 gateway address for this network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var iPv6Gateway: String?
    /** MAC address for the container on the default \"bridge\" network.  <p><br /></p>  > **Deprecated**: This field is only propagated when attached to the > default \"bridge\" network. Use the information from the \"bridge\" > network inside the `Networks` map instead, which contains the same > information. This field was deprecated in Docker 1.9 and is scheduled > to be removed in Docker 17.12.0  */
    internal var macAddress: String?
    /** Information about all networks that the container is connected to.  */
    internal var networks: [String: EndpointSettings]?

    internal init(
        bridge: String? = nil, sandboxID: String? = nil, hairpinMode: Bool? = nil, linkLocalIPv6Address: String? = nil, linkLocalIPv6PrefixLen: Int? = nil,
        ports: [String: [PortBinding]?]? = nil, sandboxKey: String? = nil, secondaryIPAddresses: [Address]? = nil, secondaryIPv6Addresses: [Address]? = nil,
        endpointID: String? = nil, gateway: String? = nil, globalIPv6Address: String? = nil, globalIPv6PrefixLen: Int? = nil, iPAddress: String? = nil, iPPrefixLen: Int? = nil,
        iPv6Gateway: String? = nil, macAddress: String? = nil, networks: [String: EndpointSettings]? = nil
    ) {
        self.bridge = bridge
        self.sandboxID = sandboxID
        self.hairpinMode = hairpinMode
        self.linkLocalIPv6Address = linkLocalIPv6Address
        self.linkLocalIPv6PrefixLen = linkLocalIPv6PrefixLen
        self.ports = ports
        self.sandboxKey = sandboxKey
        self.secondaryIPAddresses = secondaryIPAddresses
        self.secondaryIPv6Addresses = secondaryIPv6Addresses
        self.endpointID = endpointID
        self.gateway = gateway
        self.globalIPv6Address = globalIPv6Address
        self.globalIPv6PrefixLen = globalIPv6PrefixLen
        self.iPAddress = iPAddress
        self.iPPrefixLen = iPPrefixLen
        self.iPv6Gateway = iPv6Gateway
        self.macAddress = macAddress
        self.networks = networks
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case bridge = "Bridge"
        case sandboxID = "SandboxID"
        case hairpinMode = "HairpinMode"
        case linkLocalIPv6Address = "LinkLocalIPv6Address"
        case linkLocalIPv6PrefixLen = "LinkLocalIPv6PrefixLen"
        case ports = "Ports"
        case sandboxKey = "SandboxKey"
        case secondaryIPAddresses = "SecondaryIPAddresses"
        case secondaryIPv6Addresses = "SecondaryIPv6Addresses"
        case endpointID = "EndpointID"
        case gateway = "Gateway"
        case globalIPv6Address = "GlobalIPv6Address"
        case globalIPv6PrefixLen = "GlobalIPv6PrefixLen"
        case iPAddress = "IPAddress"
        case iPPrefixLen = "IPPrefixLen"
        case iPv6Gateway = "IPv6Gateway"
        case macAddress = "MacAddress"
        case networks = "Networks"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(bridge, forKey: .bridge)
        try keyedContainer.encodeIfPresent(sandboxID, forKey: .sandboxID)
        try keyedContainer.encodeIfPresent(hairpinMode, forKey: .hairpinMode)
        try keyedContainer.encodeIfPresent(linkLocalIPv6Address, forKey: .linkLocalIPv6Address)
        try keyedContainer.encodeIfPresent(linkLocalIPv6PrefixLen, forKey: .linkLocalIPv6PrefixLen)
        try keyedContainer.encodeIfPresent(ports, forKey: .ports)
        try keyedContainer.encodeIfPresent(sandboxKey, forKey: .sandboxKey)
        try keyedContainer.encodeIfPresent(secondaryIPAddresses, forKey: .secondaryIPAddresses)
        try keyedContainer.encodeIfPresent(secondaryIPv6Addresses, forKey: .secondaryIPv6Addresses)
        try keyedContainer.encodeIfPresent(endpointID, forKey: .endpointID)
        try keyedContainer.encodeIfPresent(gateway, forKey: .gateway)
        try keyedContainer.encodeIfPresent(globalIPv6Address, forKey: .globalIPv6Address)
        try keyedContainer.encodeIfPresent(globalIPv6PrefixLen, forKey: .globalIPv6PrefixLen)
        try keyedContainer.encodeIfPresent(iPAddress, forKey: .iPAddress)
        try keyedContainer.encodeIfPresent(iPPrefixLen, forKey: .iPPrefixLen)
        try keyedContainer.encodeIfPresent(iPv6Gateway, forKey: .iPv6Gateway)
        try keyedContainer.encodeIfPresent(macAddress, forKey: .macAddress)
        try keyedContainer.encodeIfPresent(networks, forKey: .networks)
    }
}
