//
// NetworkAttachmentConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specifies how a service should be attached to a particular network.
internal struct NetworkAttachmentConfig: Sendable, Content, Hashable {

    /** The target network for attachment. Must be a network name or ID.  */
    internal var target: String?
    /** Discoverable alternate names for the service on this network.  */
    internal var aliases: [String]?
    /** Driver attachment options for the network target.  */
    internal var driverOpts: [String: String]?

    internal init(target: String? = nil, aliases: [String]? = nil, driverOpts: [String: String]? = nil) {
        self.target = target
        self.aliases = aliases
        self.driverOpts = driverOpts
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case target = "Target"
        case aliases = "Aliases"
        case driverOpts = "DriverOpts"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(target, forKey: .target)
        try keyedContainer.encodeIfPresent(aliases, forKey: .aliases)
        try keyedContainer.encodeIfPresent(driverOpts, forKey: .driverOpts)
    }
}
