//
// Node.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Node: Sendable, Content, Hashable {

    internal var ID: String?
    internal var version: ObjectVersion?
    /** Date and time at which the node was added to the swarm in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var createdAt: String?
    /** Date and time at which the node was last updated in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var updatedAt: String?
    internal var spec: NodeSpec?
    internal var description: NodeDescription?
    internal var status: NodeStatus?
    internal var managerStatus: ManagerStatus?

    internal init(
        ID: String? = nil, version: ObjectVersion? = nil, createdAt: String? = nil, updatedAt: String? = nil, spec: NodeSpec? = nil, description: NodeDescription? = nil,
        status: NodeStatus? = nil, managerStatus: ManagerStatus? = nil
    ) {
        self.ID = ID
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.spec = spec
        self.description = description
        self.status = status
        self.managerStatus = managerStatus
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case version = "Version"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case spec = "Spec"
        case description = "Description"
        case status = "Status"
        case managerStatus = "ManagerStatus"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
        try keyedContainer.encodeIfPresent(description, forKey: .description)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
        try keyedContainer.encodeIfPresent(managerStatus, forKey: .managerStatus)
    }
}
