//
// NodeDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// NodeDescription encapsulates the properties of the Node as reported by the agent.
internal struct NodeDescription: Sendable, Content, Hashable {

    internal var hostname: String?
    internal var platform: DockerPlatform?
    internal var resources: ResourceObject?
    internal var engine: EngineDescription?
    internal var tLSInfo: TLSInfo?

    internal init(hostname: String? = nil, platform: DockerPlatform? = nil, resources: ResourceObject? = nil, engine: EngineDescription? = nil, tLSInfo: TLSInfo? = nil) {
        self.hostname = hostname
        self.platform = platform
        self.resources = resources
        self.engine = engine
        self.tLSInfo = tLSInfo
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case hostname = "Hostname"
        case platform = "Platform"
        case resources = "Resources"
        case engine = "Engine"
        case tLSInfo = "TLSInfo"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(hostname, forKey: .hostname)
        try keyedContainer.encodeIfPresent(platform, forKey: .platform)
        try keyedContainer.encodeIfPresent(resources, forKey: .resources)
        try keyedContainer.encodeIfPresent(engine, forKey: .engine)
        try keyedContainer.encodeIfPresent(tLSInfo, forKey: .tLSInfo)
    }
}
