//
// NodeSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct NodeSpec: Sendable, Content, Hashable {

    internal enum Role: String, Sendable, Content, Hashable, CaseIterable {
        case worker = "worker"
        case manager = "manager"
    }
    internal enum Availability: String, Sendable, Content, Hashable, CaseIterable {
        case active = "active"
        case pause = "pause"
        case drain = "drain"
    }
    /** Name for the node. */
    internal var name: String?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** Role of the node. */
    internal var role: Role?
    /** Availability of the node. */
    internal var availability: Availability?

    internal init(name: String? = nil, labels: [String: String]? = nil, role: Role? = nil, availability: Availability? = nil) {
        self.name = name
        self.labels = labels
        self.role = role
        self.availability = availability
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case labels = "Labels"
        case role = "Role"
        case availability = "Availability"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(role, forKey: .role)
        try keyedContainer.encodeIfPresent(availability, forKey: .availability)
    }
}
