//
// NodeState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// NodeState represents the state of a node.
internal enum NodeState: String, Sendable, Content, Hashable, CaseIterable {
    case unknown = "unknown"
    case down = "down"
    case ready = "ready"
    case disconnected = "disconnected"
}
