//
// NodeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager.
internal struct NodeStatus: Sendable, Content, Hashable {

    internal var state: NodeState?
    internal var message: String?
    /** IP address of the node. */
    internal var addr: String?

    internal init(state: NodeState? = nil, message: String? = nil, addr: String? = nil) {
        self.state = state
        self.message = message
        self.addr = addr
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case state = "State"
        case message = "Message"
        case addr = "Addr"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(state, forKey: .state)
        try keyedContainer.encodeIfPresent(message, forKey: .message)
        try keyedContainer.encodeIfPresent(addr, forKey: .addr)
    }
}
