//
// ObjectVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The version number of the object such as node, service, etc. This is needed to avoid conflicting writes. The client must send the version number along with the modified specification when updating these objects.  This approach ensures safe concurrency and determinism in that the change on the object may not be applied if the version number has changed from the last read. In other words, if two update requests specify the same base version, only one of the requests can succeed. As a result, two separate update requests that happen at the same time will not unintentionally overwrite each other.
internal struct ObjectVersion: Sendable, Content, Hashable {

    internal var index: Int?

    internal init(index: Int? = nil) {
        self.index = index
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case index = "Index"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(index, forKey: .index)
    }
}
