//
// OCIDescriptor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
internal struct OCIDescriptor: Sendable, Content, Hashable {

    /** The media type of the object this schema refers to.  */
    internal var mediaType: String?
    /** The digest of the targeted content.  */
    internal var digest: String?
    /** The size in bytes of the blob.  */
    internal var size: Int64?
    /** List of URLs from which this object MAY be downloaded. */
    internal var urls: [String]?
    /** Arbitrary metadata relating to the targeted content. */
    internal var annotations: [String: String]?
    /** Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content. */
    internal var data: String?
    internal var platform: OCIPlatform?
    /** ArtifactType is the IANA media type of this artifact. */
    internal var artifactType: String?

    internal init(
        mediaType: String? = nil, digest: String? = nil, size: Int64? = nil, urls: [String]? = nil, annotations: [String: String]? = nil, data: String? = nil,
        platform: OCIPlatform? = nil, artifactType: String? = nil
    ) {
        self.mediaType = mediaType
        self.digest = digest
        self.size = size
        self.urls = urls
        self.annotations = annotations
        self.data = data
        self.platform = platform
        self.artifactType = artifactType
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaType
        case digest
        case size
        case urls
        case annotations
        case data
        case platform
        case artifactType
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(mediaType, forKey: .mediaType)
        try keyedContainer.encodeIfPresent(digest, forKey: .digest)
        try keyedContainer.encodeIfPresent(size, forKey: .size)
        try keyedContainer.encodeIfPresent(urls, forKey: .urls)
        try keyedContainer.encodeIfPresent(annotations, forKey: .annotations)
        try keyedContainer.encodeIfPresent(data, forKey: .data)
        try keyedContainer.encodeIfPresent(platform, forKey: .platform)
        try keyedContainer.encodeIfPresent(artifactType, forKey: .artifactType)
    }
}
