//
// OCIPlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md).
internal struct OCIPlatform: Sendable, Content, Hashable {

    /** The CPU architecture, for example `amd64` or `ppc64`.  */
    internal var architecture: String?
    /** The operating system, for example `linux` or `windows`.  */
    internal var os: String?
    /** Optional field specifying the operating system version, for example on Windows `10.0.19041.1165`.  */
    internal var osVersion: String?
    /** Optional field specifying an array of strings, each listing a required OS feature (for example on Windows `win32k`).  */
    internal var osFeatures: [String]?
    /** Optional field specifying a variant of the CPU, for example `v7` to specify ARMv7 when architecture is `arm`.  */
    internal var variant: String?

    internal init(architecture: String? = nil, os: String? = nil, osVersion: String? = nil, osFeatures: [String]? = nil, variant: String? = nil) {
        self.architecture = architecture
        self.os = os
        self.osVersion = osVersion
        self.osFeatures = osFeatures
        self.variant = variant
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case architecture
        case os
        case osVersion = "os.version"
        case osFeatures = "os.features"
        case variant
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(architecture, forKey: .architecture)
        try keyedContainer.encodeIfPresent(os, forKey: .os)
        try keyedContainer.encodeIfPresent(osVersion, forKey: .osVersion)
        try keyedContainer.encodeIfPresent(osFeatures, forKey: .osFeatures)
        try keyedContainer.encodeIfPresent(variant, forKey: .variant)
    }
}
