//
// PeerInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// PeerInfo represents one peer of an overlay network.
internal struct PeerInfo: Sendable, Content, Hashable {

    /** ID of the peer-node in the Swarm cluster. */
    internal var name: String?
    /** IP-address of the peer-node in the Swarm cluster. */
    internal var IP: String?

    internal init(name: String? = nil, IP: String? = nil) {
        self.name = name
        self.IP = IP
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case IP
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(IP, forKey: .IP)
    }
}
