//
// PeerNode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Represents a peer-node in the swarm
internal struct PeerNode: Sendable, Content, Hashable {

    /** Unique identifier of for this node in the swarm. */
    internal var nodeID: String?
    /** IP address and ports at which this node can be reached.  */
    internal var addr: String?

    internal init(nodeID: String? = nil, addr: String? = nil) {
        self.nodeID = nodeID
        self.addr = addr
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case nodeID = "NodeID"
        case addr = "Addr"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(nodeID, forKey: .nodeID)
        try keyedContainer.encodeIfPresent(addr, forKey: .addr)
    }
}
