//
// PluginEnv.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginEnv: Sendable, Content, Hashable {

    internal var name: String
    internal var description: String
    internal var settable: [String]
    internal var value: String

    internal init(name: String, description: String, settable: [String], value: String) {
        self.name = name
        self.description = description
        self.settable = settable
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case description = "Description"
        case settable = "Settable"
        case value = "Value"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(description, forKey: .description)
        try keyedContainer.encode(settable, forKey: .settable)
        try keyedContainer.encode(value, forKey: .value)
    }
}
