//
// PluginInterfaceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginInterfaceType: Sendable, Content, Hashable {

    internal var `prefix`: String
    internal var capability: String
    internal var version: String

    internal init(`prefix`: String, capability: String, version: String) {
        self.`prefix` = `prefix`
        self.capability = capability
        self.version = version
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case `prefix` = "Prefix"
        case capability = "Capability"
        case version = "Version"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(`prefix`, forKey: .`prefix`)
        try keyedContainer.encode(capability, forKey: .capability)
        try keyedContainer.encode(version, forKey: .version)
    }
}
