//
// Plugin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A plugin for the Engine API
internal struct Plugin: Sendable, Content, Hashable {

    internal var id: String?
    internal var name: String
    /** True if the plugin is running. False if the plugin is not running, only installed. */
    internal var enabled: Bool
    internal var settings: PluginSettings
    /** plugin remote reference used to push/pull the plugin */
    internal var pluginReference: String?
    internal var config: PluginConfig

    internal init(id: String? = nil, name: String, enabled: Bool, settings: PluginSettings, pluginReference: String? = nil, config: PluginConfig) {
        self.id = id
        self.name = name
        self.enabled = enabled
        self.settings = settings
        self.pluginReference = pluginReference
        self.config = config
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case name = "Name"
        case enabled = "Enabled"
        case settings = "Settings"
        case pluginReference = "PluginReference"
        case config = "Config"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(id, forKey: .id)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(enabled, forKey: .enabled)
        try keyedContainer.encode(settings, forKey: .settings)
        try keyedContainer.encodeIfPresent(pluginReference, forKey: .pluginReference)
        try keyedContainer.encode(config, forKey: .config)
    }
}
