//
// PluginPrivilege.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Describes a permission the user has to accept upon installing the plugin.
internal struct PluginPrivilege: Sendable, Content, Hashable {

    internal var name: String?
    internal var description: String?
    internal var value: [String]?

    internal init(name: String? = nil, description: String? = nil, value: [String]? = nil) {
        self.name = name
        self.description = description
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case description = "Description"
        case value = "Value"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(description, forKey: .description)
        try keyedContainer.encodeIfPresent(value, forKey: .value)
    }
}
