//
// PluginConfigNetwork.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginConfigNetwork: Sendable, Content, Hashable {

    internal var type: String

    internal init(type: String) {
        self.type = type
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "Type"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(type, forKey: .type)
    }
}
