//
// PluginsInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Available plugins per type.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: Only unmanaged (V1) plugins are included in this list. &gt; V1 plugins are \&quot;lazily\&quot; loaded, and are not returned in this list &gt; if there is no resource using the plugin.
internal struct PluginsInfo: Sendable, Content, Hashable {

    /** Names of available volume-drivers, and network-driver plugins. */
    internal var volume: [String]?
    /** Names of available network-drivers, and network-driver plugins. */
    internal var network: [String]?
    /** Names of available authorization plugins. */
    internal var authorization: [String]?
    /** Names of available logging-drivers, and logging-driver plugins. */
    internal var log: [String]?

    internal init(volume: [String]? = nil, network: [String]? = nil, authorization: [String]? = nil, log: [String]? = nil) {
        self.volume = volume
        self.network = network
        self.authorization = authorization
        self.log = log
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case volume = "Volume"
        case network = "Network"
        case authorization = "Authorization"
        case log = "Log"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(volume, forKey: .volume)
        try keyedContainer.encodeIfPresent(network, forKey: .network)
        try keyedContainer.encodeIfPresent(authorization, forKey: .authorization)
        try keyedContainer.encodeIfPresent(log, forKey: .log)
    }
}
