//
// PluginConfigRootfs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginConfigRootfs: Sendable, Content, Hashable {

    internal var type: String?
    internal var diffIds: [String]?

    internal init(type: String? = nil, diffIds: [String]? = nil) {
        self.type = type
        self.diffIds = diffIds
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case diffIds = "diff_ids"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(diffIds, forKey: .diffIds)
    }
}
