//
// PluginConfigInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The interface between Docker and the plugin
internal struct PluginConfigInterface: Sendable, Content, Hashable {

    internal enum ProtocolScheme: String, Sendable, Content, Hashable, CaseIterable {
        case empty = ""
        case mobyPeriodPluginsPeriodHttpSlashV1 = "moby.plugins.http/v1"
    }
    internal var types: [PluginInterfaceType]
    internal var socket: String
    /** Protocol to use for clients connecting to the plugin. */
    internal var protocolScheme: ProtocolScheme?

    internal init(types: [PluginInterfaceType], socket: String, protocolScheme: ProtocolScheme? = nil) {
        self.types = types
        self.socket = socket
        self.protocolScheme = protocolScheme
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case types = "Types"
        case socket = "Socket"
        case protocolScheme = "ProtocolScheme"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(types, forKey: .types)
        try keyedContainer.encode(socket, forKey: .socket)
        try keyedContainer.encodeIfPresent(protocolScheme, forKey: .protocolScheme)
    }
}
