//
// PluginSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Settings that can be modified by users.
internal struct PluginSettings: Sendable, Content, Hashable {

    internal var mounts: [PluginMount]
    internal var env: [String]
    internal var args: [String]
    internal var devices: [PluginDevice]

    internal init(mounts: [PluginMount], env: [String], args: [String], devices: [PluginDevice]) {
        self.mounts = mounts
        self.env = env
        self.args = args
        self.devices = devices
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mounts = "Mounts"
        case env = "Env"
        case args = "Args"
        case devices = "Devices"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(mounts, forKey: .mounts)
        try keyedContainer.encode(env, forKey: .env)
        try keyedContainer.encode(args, forKey: .args)
        try keyedContainer.encode(devices, forKey: .devices)
    }
}
