//
// PluginConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The config of a plugin.
internal struct PluginConfig: Sendable, Content, Hashable {

    /** Docker Version used to create the plugin.  Depending on how the plugin was created, this field may be empty or omitted.  Deprecated: this field is no longer set, and will be removed in the next API version. */
    internal var dockerVersion: String?
    internal var description: String
    internal var documentation: String
    internal var interface: PluginConfigInterface
    internal var entrypoint: [String]
    internal var workDir: String
    internal var user: PluginConfigUser?
    internal var network: PluginConfigNetwork
    internal var linux: PluginConfigLinux
    internal var propagatedMount: String
    internal var ipcHost: Bool
    internal var pidHost: Bool
    internal var mounts: [PluginMount]
    internal var env: [PluginEnv]
    internal var args: PluginConfigArgs
    internal var rootfs: PluginConfigRootfs?

    internal init(
        dockerVersion: String? = nil, description: String, documentation: String, interface: PluginConfigInterface, entrypoint: [String], workDir: String,
        user: PluginConfigUser? = nil, network: PluginConfigNetwork, linux: PluginConfigLinux, propagatedMount: String, ipcHost: Bool, pidHost: Bool, mounts: [PluginMount],
        env: [PluginEnv], args: PluginConfigArgs, rootfs: PluginConfigRootfs? = nil
    ) {
        self.dockerVersion = dockerVersion
        self.description = description
        self.documentation = documentation
        self.interface = interface
        self.entrypoint = entrypoint
        self.workDir = workDir
        self.user = user
        self.network = network
        self.linux = linux
        self.propagatedMount = propagatedMount
        self.ipcHost = ipcHost
        self.pidHost = pidHost
        self.mounts = mounts
        self.env = env
        self.args = args
        self.rootfs = rootfs
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case dockerVersion = "DockerVersion"
        case description = "Description"
        case documentation = "Documentation"
        case interface = "Interface"
        case entrypoint = "Entrypoint"
        case workDir = "WorkDir"
        case user = "User"
        case network = "Network"
        case linux = "Linux"
        case propagatedMount = "PropagatedMount"
        case ipcHost = "IpcHost"
        case pidHost = "PidHost"
        case mounts = "Mounts"
        case env = "Env"
        case args = "Args"
        case rootfs
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(dockerVersion, forKey: .dockerVersion)
        try keyedContainer.encode(description, forKey: .description)
        try keyedContainer.encode(documentation, forKey: .documentation)
        try keyedContainer.encode(interface, forKey: .interface)
        try keyedContainer.encode(entrypoint, forKey: .entrypoint)
        try keyedContainer.encode(workDir, forKey: .workDir)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encode(network, forKey: .network)
        try keyedContainer.encode(linux, forKey: .linux)
        try keyedContainer.encode(propagatedMount, forKey: .propagatedMount)
        try keyedContainer.encode(ipcHost, forKey: .ipcHost)
        try keyedContainer.encode(pidHost, forKey: .pidHost)
        try keyedContainer.encode(mounts, forKey: .mounts)
        try keyedContainer.encode(env, forKey: .env)
        try keyedContainer.encode(args, forKey: .args)
        try keyedContainer.encodeIfPresent(rootfs, forKey: .rootfs)
    }
}
