//
// PluginConfigLinux.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginConfigLinux: Sendable, Content, Hashable {

    internal var capabilities: [String]
    internal var allowAllDevices: Bool
    internal var devices: [PluginDevice]

    internal init(capabilities: [String], allowAllDevices: Bool, devices: [PluginDevice]) {
        self.capabilities = capabilities
        self.allowAllDevices = allowAllDevices
        self.devices = devices
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case capabilities = "Capabilities"
        case allowAllDevices = "AllowAllDevices"
        case devices = "Devices"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(capabilities, forKey: .capabilities)
        try keyedContainer.encode(allowAllDevices, forKey: .allowAllDevices)
        try keyedContainer.encode(devices, forKey: .devices)
    }
}
