//
// PluginConfigUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginConfigUser: Sendable, Content, Hashable {

    internal var UID: Int?
    internal var GID: Int?

    internal init(UID: Int? = nil, GID: Int? = nil) {
        self.UID = UID
        self.GID = GID
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case UID
        case GID
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(UID, forKey: .UID)
        try keyedContainer.encodeIfPresent(GID, forKey: .GID)
    }
}
