//
// PluginDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct PluginDevice: Sendable, Content, Hashable {

    internal var name: String
    internal var description: String
    internal var settable: [String]
    internal var path: String

    internal init(name: String, description: String, settable: [String], path: String) {
        self.name = name
        self.description = description
        self.settable = settable
        self.path = path
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case description = "Description"
        case settable = "Settable"
        case path = "Path"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(description, forKey: .description)
        try keyedContainer.encode(settable, forKey: .settable)
        try keyedContainer.encode(path, forKey: .path)
    }
}
