//
// Port.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// An open port on a container
internal struct Port: Sendable, Content, Hashable {

    internal enum ModelType: String, Sendable, Content, Hashable, CaseIterable {
        case tcp = "tcp"
        case udp = "udp"
        case sctp = "sctp"
    }
    /** Host IP address that the container's port is mapped to */
    internal var IP: String?
    /** Port on the container */
    internal var privatePort: Int
    /** Port exposed on the host */
    internal var publicPort: Int?
    internal var type: ModelType

    internal init(IP: String? = nil, privatePort: Int, publicPort: Int? = nil, type: ModelType) {
        self.IP = IP
        self.privatePort = privatePort
        self.publicPort = publicPort
        self.type = type
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case IP
        case privatePort = "PrivatePort"
        case publicPort = "PublicPort"
        case type = "Type"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(IP, forKey: .IP)
        try keyedContainer.encode(privatePort, forKey: .privatePort)
        try keyedContainer.encodeIfPresent(publicPort, forKey: .publicPort)
        try keyedContainer.encode(type, forKey: .type)
    }
}
