//
// PortBinding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// PortBinding represents a binding between a host IP address and a host port.
internal struct PortBinding: Sendable, Content, Hashable {

    /** Host IP address that the container's port is mapped to. */
    internal var hostIp: String?
    /** Host port number that the container's port is mapped to. */
    internal var hostPort: String?

    internal init(hostIp: String? = nil, hostPort: String? = nil) {
        self.hostIp = hostIp
        self.hostPort = hostPort
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case hostIp = "HostIp"
        case hostPort = "HostPort"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(hostIp, forKey: .hostIp)
        try keyedContainer.encodeIfPresent(hostPort, forKey: .hostPort)
    }
}
