//
// PortStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// represents the port status of a task&#39;s host ports whose service has published host ports
internal struct PortStatus: Sendable, Content, Hashable {

    internal var ports: [EndpointPortConfig]?

    internal init(ports: [EndpointPortConfig]? = nil) {
        self.ports = ports
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ports = "Ports"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ports, forKey: .ports)
    }
}
