//
// ProcessConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ProcessConfig: Sendable, Content, Hashable {

    internal var privileged: Bool?
    internal var user: String?
    internal var tty: Bool?
    internal var entrypoint: String?
    internal var arguments: [String]?

    internal init(privileged: Bool? = nil, user: String? = nil, tty: Bool? = nil, entrypoint: String? = nil, arguments: [String]? = nil) {
        self.privileged = privileged
        self.user = user
        self.tty = tty
        self.entrypoint = entrypoint
        self.arguments = arguments
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case privileged
        case user
        case tty
        case entrypoint
        case arguments
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(privileged, forKey: .privileged)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(tty, forKey: .tty)
        try keyedContainer.encodeIfPresent(entrypoint, forKey: .entrypoint)
        try keyedContainer.encodeIfPresent(arguments, forKey: .arguments)
    }
}
