//
// ProgressDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ProgressDetail: Sendable, Content, Hashable {

    internal var current: Int?
    internal var total: Int?

    internal init(current: Int? = nil, total: Int? = nil) {
        self.current = current
        self.total = total
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case total
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(current, forKey: .current)
        try keyedContainer.encodeIfPresent(total, forKey: .total)
    }
}
