//
// Reachability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Reachability represents the reachability of a node.
internal enum Reachability: String, Sendable, Content, Hashable, CaseIterable {
    case unknown = "unknown"
    case unreachable = "unreachable"
    case reachable = "reachable"
}
