//
// RegistryServiceConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// RegistryServiceConfig stores daemon registry services configuration.
internal struct RegistryServiceConfig: Sendable, Content, Hashable {

    /** List of IP ranges of insecure registries, using the CIDR syntax ([RFC 4632](https://tools.ietf.org/html/4632)). Insecure registries accept un-encrypted (HTTP) and/or untrusted (HTTPS with certificates from unknown CAs) communication.  By default, local registries (`::1/128` and `127.0.0.0/8`) are configured as insecure. All other registries are secure. Communicating with an insecure registry is not possible if the daemon assumes that registry is secure.  This configuration override this behavior, insecure communication with registries whose resolved IP address is within the subnet described by the CIDR syntax.  Registries can also be marked insecure by hostname. Those registries are listed under `IndexConfigs` and have their `Secure` field set to `false`.  > **Warning**: Using this option can be useful when running a local > registry, but introduces security vulnerabilities. This option > should therefore ONLY be used for testing purposes. For increased > security, users should add their CA to their system's list of trusted > CAs instead of enabling this option.  */
    internal var insecureRegistryCIDRs: [String]?
    internal var indexConfigs: [String: IndexInfo]?
    /** List of registry URLs that act as a mirror for the official (`docker.io`) registry.  */
    internal var mirrors: [String]?

    internal init(insecureRegistryCIDRs: [String]? = nil, indexConfigs: [String: IndexInfo]? = nil, mirrors: [String]? = nil) {
        self.insecureRegistryCIDRs = insecureRegistryCIDRs
        self.indexConfigs = indexConfigs
        self.mirrors = mirrors
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case insecureRegistryCIDRs = "InsecureRegistryCIDRs"
        case indexConfigs = "IndexConfigs"
        case mirrors = "Mirrors"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(insecureRegistryCIDRs, forKey: .insecureRegistryCIDRs)
        try keyedContainer.encodeIfPresent(indexConfigs, forKey: .indexConfigs)
        try keyedContainer.encodeIfPresent(mirrors, forKey: .mirrors)
    }
}
