//
// ResourcesBlkioWeightDeviceInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ResourcesBlkioWeightDeviceInner: Sendable, Content, Hashable {

    internal var path: String?
    internal var weight: Int?

    internal init(path: String? = nil, weight: Int? = nil) {
        self.path = path
        self.weight = weight
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case weight = "Weight"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(path, forKey: .path)
        try keyedContainer.encodeIfPresent(weight, forKey: .weight)
    }
}
