//
// ResourcesUlimitsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ResourcesUlimitsInner: Sendable, Content, Hashable {

    /** Name of ulimit */
    internal var name: String?
    /** Soft limit */
    internal var soft: Int?
    /** Hard limit */
    internal var hard: Int?

    internal init(name: String? = nil, soft: Int? = nil, hard: Int? = nil) {
        self.name = name
        self.soft = soft
        self.hard = hard
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case soft = "Soft"
        case hard = "Hard"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(soft, forKey: .soft)
        try keyedContainer.encodeIfPresent(hard, forKey: .hard)
    }
}
