//
// RestartPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The behavior to apply when the container exits. The default is not to restart.  An ever increasing delay (double the previous delay, starting at 100ms) is added before each restart to prevent flooding the server.
internal struct RestartPolicy: Sendable, Content, Hashable {

    internal enum Name: String, Sendable, Content, Hashable, CaseIterable {
        case empty = ""
        case no = "no"
        case always = "always"
        case unlessStopped = "unless-stopped"
        case onFailure = "on-failure"
    }
    /** - Empty string means not to restart - `no` Do not automatically restart - `always` Always restart - `unless-stopped` Restart always except when the user has manually stopped the container - `on-failure` Restart only when the container exit code is non-zero  */
    internal var name: Name?
    /** If `on-failure` is used, the number of times to retry before giving up.  */
    internal var maximumRetryCount: Int?

    internal init(name: Name? = nil, maximumRetryCount: Int? = nil) {
        self.name = name
        self.maximumRetryCount = maximumRetryCount
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case maximumRetryCount = "MaximumRetryCount"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(maximumRetryCount, forKey: .maximumRetryCount)
    }
}
