//
// Runtime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Runtime describes an [OCI compliant](https://github.com/opencontainers/runtime-spec) runtime.  The runtime is invoked by the daemon via the &#x60;containerd&#x60; daemon. OCI runtimes act as an interface to the Linux kernel namespaces, cgroups, and SELinux.
internal struct Runtime: Sendable, Content, Hashable {

    /** Name and, optional, path, of the OCI executable binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  */
    internal var path: String?
    /** List of command-line arguments to pass to the runtime when invoked.  */
    internal var runtimeArgs: [String]?
    /** Information specific to the runtime.  While this API specification does not define data provided by runtimes, the following well-known properties may be provided by runtimes:  `org.opencontainers.runtime-spec.features`: features structure as defined in the [OCI Runtime Specification](https://github.com/opencontainers/runtime-spec/blob/main/features.md), in a JSON string representation.  <p><br /></p>  > **Note**: The information returned in this field, including the > formatting of values and labels, should not be considered stable, > and may change without notice.  */
    internal var status: [String: String]?

    internal init(path: String? = nil, runtimeArgs: [String]? = nil, status: [String: String]? = nil) {
        self.path = path
        self.runtimeArgs = runtimeArgs
        self.status = status
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case runtimeArgs
        case status
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(path, forKey: .path)
        try keyedContainer.encodeIfPresent(runtimeArgs, forKey: .runtimeArgs)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
    }
}
