//
// SecretCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SecretCreateRequest: Sendable, Content, Hashable {

    /** User-defined name of the secret. */
    internal var name: String?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    /** Data is the data to store as a secret, formatted as a standard base64-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-4)) string. It must be empty if the Driver field is set, in which case the data is loaded from an external secret store. The maximum allowed size is 500KB, as defined in [MaxSecretSize](https://pkg.go.dev/github.com/moby/swarmkit/v2@v2.0.0/api/validation#MaxSecretSize).  This field is only used to _create_ a secret, and is not returned by other endpoints.  */
    internal var data: String?
    internal var driver: Driver?
    internal var templating: Driver?

    internal init(name: String? = nil, labels: [String: String]? = nil, data: String? = nil, driver: Driver? = nil, templating: Driver? = nil) {
        self.name = name
        self.labels = labels
        self.data = data
        self.driver = driver
        self.templating = templating
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case labels = "Labels"
        case data = "Data"
        case driver = "Driver"
        case templating = "Templating"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(data, forKey: .data)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(templating, forKey: .templating)
    }
}
