//
// Secret.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Secret: Sendable, Content, Hashable {

    internal var ID: String?
    internal var version: ObjectVersion?
    internal var createdAt: String?
    internal var updatedAt: String?
    internal var spec: SecretSpec?

    internal init(ID: String? = nil, version: ObjectVersion? = nil, createdAt: String? = nil, updatedAt: String? = nil, spec: SecretSpec? = nil) {
        self.ID = ID
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.spec = spec
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case version = "Version"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case spec = "Spec"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
    }
}
