//
// ServiceEndpointVirtualIPsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ServiceEndpointVirtualIPsInner: Sendable, Content, Hashable {

    internal var networkID: String?
    internal var addr: String?

    internal init(networkID: String? = nil, addr: String? = nil) {
        self.networkID = networkID
        self.addr = addr
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case networkID = "NetworkID"
        case addr = "Addr"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(networkID, forKey: .networkID)
        try keyedContainer.encodeIfPresent(addr, forKey: .addr)
    }
}
