//
// ServiceCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// contains the information returned to a client on the creation of a new service.
internal struct ServiceCreateResponse: Sendable, Content, Hashable {

    /** The ID of the created service. */
    internal var ID: String?
    /** Optional warning message.  FIXME(thaJeztah): this should have \"omitempty\" in the generated type.  */
    internal var warnings: [String]?

    internal init(ID: String? = nil, warnings: [String]? = nil) {
        self.ID = ID
        self.warnings = warnings
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(warnings, forKey: .warnings)
    }
}
