//
// ServiceJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service&#39;s version, does not need to be sent with an update request.
internal struct ServiceJobStatus: Sendable, Content, Hashable {

    internal var jobIteration: ObjectVersion?
    /** The last time, as observed by the server, that this job was started.  */
    internal var lastExecution: String?

    internal init(jobIteration: ObjectVersion? = nil, lastExecution: String? = nil) {
        self.jobIteration = jobIteration
        self.lastExecution = lastExecution
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case jobIteration = "JobIteration"
        case lastExecution = "LastExecution"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(jobIteration, forKey: .jobIteration)
        try keyedContainer.encodeIfPresent(lastExecution, forKey: .lastExecution)
    }
}
