//
// ServiceUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ServiceUpdateResponse: Sendable, Content, Hashable {

    /** Optional warning messages */
    internal var warnings: [String]?

    internal init(warnings: [String]? = nil) {
        self.warnings = warnings
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(warnings, forKey: .warnings)
    }
}
