//
// ServiceSpecRollbackConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specification for the rollback strategy of the service.
internal struct ServiceSpecRollbackConfig: Sendable, Content, Hashable {

    internal enum FailureAction: String, Sendable, Content, Hashable, CaseIterable {
        case `continue` = "continue"
        case pause = "pause"
    }
    internal enum Order: String, Sendable, Content, Hashable, CaseIterable {
        case stopFirst = "stop-first"
        case startFirst = "start-first"
    }
    /** Maximum number of tasks to be rolled back in one iteration (0 means unlimited parallelism).  */
    internal var parallelism: Int64?
    /** Amount of time between rollback iterations, in nanoseconds.  */
    internal var delay: Int64?
    /** Action to take if an rolled back task fails to run, or stops running during the rollback.  */
    internal var failureAction: FailureAction?
    /** Amount of time to monitor each rolled back task for failures, in nanoseconds.  */
    internal var monitor: Int64?
    /** The fraction of tasks that may fail during a rollback before the failure action is invoked, specified as a floating point number between 0 and 1.  */
    internal var maxFailureRatio: Double?
    /** The order of operations when rolling back a task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.  */
    internal var order: Order?

    internal init(parallelism: Int64? = nil, delay: Int64? = nil, failureAction: FailureAction? = nil, monitor: Int64? = nil, maxFailureRatio: Double? = nil, order: Order? = nil) {
        self.parallelism = parallelism
        self.delay = delay
        self.failureAction = failureAction
        self.monitor = monitor
        self.maxFailureRatio = maxFailureRatio
        self.order = order
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case parallelism = "Parallelism"
        case delay = "Delay"
        case failureAction = "FailureAction"
        case monitor = "Monitor"
        case maxFailureRatio = "MaxFailureRatio"
        case order = "Order"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(parallelism, forKey: .parallelism)
        try keyedContainer.encodeIfPresent(delay, forKey: .delay)
        try keyedContainer.encodeIfPresent(failureAction, forKey: .failureAction)
        try keyedContainer.encodeIfPresent(monitor, forKey: .monitor)
        try keyedContainer.encodeIfPresent(maxFailureRatio, forKey: .maxFailureRatio)
        try keyedContainer.encodeIfPresent(order, forKey: .order)
    }
}
