//
// ServiceServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The status of the service&#39;s tasks. Provided only when requested as part of a ServiceList operation.
internal struct ServiceServiceStatus: Sendable, Content, Hashable {

    /** The number of tasks for the service currently in the Running state.  */
    internal var runningTasks: Int?
    /** The number of tasks for the service desired to be running. For replicated services, this is the replica count from the service spec. For global services, this is computed by taking count of all tasks for the service with a Desired State other than Shutdown.  */
    internal var desiredTasks: Int?
    /** The number of tasks for a job that are in the Completed state. This field must be cross-referenced with the service type, as the value of 0 may mean the service is not in a job mode, or it may mean the job-mode service has no tasks yet Completed.  */
    internal var completedTasks: Int?

    internal init(runningTasks: Int? = nil, desiredTasks: Int? = nil, completedTasks: Int? = nil) {
        self.runningTasks = runningTasks
        self.desiredTasks = desiredTasks
        self.completedTasks = completedTasks
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case runningTasks = "RunningTasks"
        case desiredTasks = "DesiredTasks"
        case completedTasks = "CompletedTasks"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(runningTasks, forKey: .runningTasks)
        try keyedContainer.encodeIfPresent(desiredTasks, forKey: .desiredTasks)
        try keyedContainer.encodeIfPresent(completedTasks, forKey: .completedTasks)
    }
}
