//
// ServiceCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ServiceCreateRequest: Sendable, Content, Hashable {

    /** Name of the service. */
    internal var name: String?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    internal var taskTemplate: TaskSpec?
    internal var mode: ServiceSpecMode?
    internal var updateConfig: ServiceSpecUpdateConfig?
    internal var rollbackConfig: ServiceSpecRollbackConfig?
    /** Specifies which networks the service should attach to.  Deprecated: This field is deprecated since v1.44. The Networks field in TaskSpec should be used instead.  */
    internal var networks: [NetworkAttachmentConfig]?
    internal var endpointSpec: EndpointSpec?

    internal init(
        name: String? = nil, labels: [String: String]? = nil, taskTemplate: TaskSpec? = nil, mode: ServiceSpecMode? = nil, updateConfig: ServiceSpecUpdateConfig? = nil,
        rollbackConfig: ServiceSpecRollbackConfig? = nil, networks: [NetworkAttachmentConfig]? = nil, endpointSpec: EndpointSpec? = nil
    ) {
        self.name = name
        self.labels = labels
        self.taskTemplate = taskTemplate
        self.mode = mode
        self.updateConfig = updateConfig
        self.rollbackConfig = rollbackConfig
        self.networks = networks
        self.endpointSpec = endpointSpec
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case labels = "Labels"
        case taskTemplate = "TaskTemplate"
        case mode = "Mode"
        case updateConfig = "UpdateConfig"
        case rollbackConfig = "RollbackConfig"
        case networks = "Networks"
        case endpointSpec = "EndpointSpec"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(taskTemplate, forKey: .taskTemplate)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
        try keyedContainer.encodeIfPresent(updateConfig, forKey: .updateConfig)
        try keyedContainer.encodeIfPresent(rollbackConfig, forKey: .rollbackConfig)
        try keyedContainer.encodeIfPresent(networks, forKey: .networks)
        try keyedContainer.encodeIfPresent(endpointSpec, forKey: .endpointSpec)
    }
}
