//
// Service.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Service: Sendable, Content, Hashable {

    internal var ID: String?
    internal var version: ObjectVersion?
    internal var createdAt: String?
    internal var updatedAt: String?
    internal var spec: ServiceSpec?
    internal var endpoint: ServiceEndpoint?
    internal var updateStatus: ServiceUpdateStatus?
    internal var serviceStatus: ServiceServiceStatus?
    internal var jobStatus: ServiceJobStatus?

    internal init(
        ID: String? = nil, version: ObjectVersion? = nil, createdAt: String? = nil, updatedAt: String? = nil, spec: ServiceSpec? = nil, endpoint: ServiceEndpoint? = nil,
        updateStatus: ServiceUpdateStatus? = nil, serviceStatus: ServiceServiceStatus? = nil, jobStatus: ServiceJobStatus? = nil
    ) {
        self.ID = ID
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.spec = spec
        self.endpoint = endpoint
        self.updateStatus = updateStatus
        self.serviceStatus = serviceStatus
        self.jobStatus = jobStatus
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case version = "Version"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case spec = "Spec"
        case endpoint = "Endpoint"
        case updateStatus = "UpdateStatus"
        case serviceStatus = "ServiceStatus"
        case jobStatus = "JobStatus"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
        try keyedContainer.encodeIfPresent(endpoint, forKey: .endpoint)
        try keyedContainer.encodeIfPresent(updateStatus, forKey: .updateStatus)
        try keyedContainer.encodeIfPresent(serviceStatus, forKey: .serviceStatus)
        try keyedContainer.encodeIfPresent(jobStatus, forKey: .jobStatus)
    }
}
