//
// ServiceSpecModeReplicated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ServiceSpecModeReplicated: Sendable, Content, Hashable {

    internal var replicas: Int64?

    internal init(replicas: Int64? = nil) {
        self.replicas = replicas
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case replicas = "Replicas"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(replicas, forKey: .replicas)
    }
}
