//
// ServiceSpecUpdateConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specification for the update strategy of the service.
internal struct ServiceSpecUpdateConfig: Sendable, Content, Hashable {

    internal enum FailureAction: String, Sendable, Content, Hashable, CaseIterable {
        case `continue` = "continue"
        case pause = "pause"
        case rollback = "rollback"
    }
    internal enum Order: String, Sendable, Content, Hashable, CaseIterable {
        case stopFirst = "stop-first"
        case startFirst = "start-first"
    }
    /** Maximum number of tasks to be updated in one iteration (0 means unlimited parallelism).  */
    internal var parallelism: Int64?
    /** Amount of time between updates, in nanoseconds. */
    internal var delay: Int64?
    /** Action to take if an updated task fails to run, or stops running during the update.  */
    internal var failureAction: FailureAction?
    /** Amount of time to monitor each updated task for failures, in nanoseconds.  */
    internal var monitor: Int64?
    /** The fraction of tasks that may fail during an update before the failure action is invoked, specified as a floating point number between 0 and 1.  */
    internal var maxFailureRatio: Double?
    /** The order of operations when rolling out an updated task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.  */
    internal var order: Order?

    internal init(parallelism: Int64? = nil, delay: Int64? = nil, failureAction: FailureAction? = nil, monitor: Int64? = nil, maxFailureRatio: Double? = nil, order: Order? = nil) {
        self.parallelism = parallelism
        self.delay = delay
        self.failureAction = failureAction
        self.monitor = monitor
        self.maxFailureRatio = maxFailureRatio
        self.order = order
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case parallelism = "Parallelism"
        case delay = "Delay"
        case failureAction = "FailureAction"
        case monitor = "Monitor"
        case maxFailureRatio = "MaxFailureRatio"
        case order = "Order"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(parallelism, forKey: .parallelism)
        try keyedContainer.encodeIfPresent(delay, forKey: .delay)
        try keyedContainer.encodeIfPresent(failureAction, forKey: .failureAction)
        try keyedContainer.encodeIfPresent(monitor, forKey: .monitor)
        try keyedContainer.encodeIfPresent(maxFailureRatio, forKey: .maxFailureRatio)
        try keyedContainer.encodeIfPresent(order, forKey: .order)
    }
}
