//
// ServiceUpdateStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The status of a service update.
internal struct ServiceUpdateStatus: Sendable, Content, Hashable {

    internal enum State: String, Sendable, Content, Hashable, CaseIterable {
        case updating = "updating"
        case paused = "paused"
        case completed = "completed"
    }
    internal var state: State?
    internal var startedAt: String?
    internal var completedAt: String?
    internal var message: String?

    internal init(state: State? = nil, startedAt: String? = nil, completedAt: String? = nil, message: String? = nil) {
        self.state = state
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.message = message
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case state = "State"
        case startedAt = "StartedAt"
        case completedAt = "CompletedAt"
        case message = "Message"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(state, forKey: .state)
        try keyedContainer.encodeIfPresent(startedAt, forKey: .startedAt)
        try keyedContainer.encodeIfPresent(completedAt, forKey: .completedAt)
        try keyedContainer.encodeIfPresent(message, forKey: .message)
    }
}
