//
// ServiceSpecMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Scheduling mode for the service.
internal struct ServiceSpecMode: Sendable, Content, Hashable {

    internal var replicated: ServiceSpecModeReplicated?
    internal var global: JSONValue?
    internal var replicatedJob: ServiceSpecModeReplicatedJob?
    /** The mode used for services which run a task to the completed state on each valid node.  */
    internal var globalJob: JSONValue?

    internal init(replicated: ServiceSpecModeReplicated? = nil, global: JSONValue? = nil, replicatedJob: ServiceSpecModeReplicatedJob? = nil, globalJob: JSONValue? = nil) {
        self.replicated = replicated
        self.global = global
        self.replicatedJob = replicatedJob
        self.globalJob = globalJob
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case replicated = "Replicated"
        case global = "Global"
        case replicatedJob = "ReplicatedJob"
        case globalJob = "GlobalJob"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(replicated, forKey: .replicated)
        try keyedContainer.encodeIfPresent(global, forKey: .global)
        try keyedContainer.encodeIfPresent(replicatedJob, forKey: .replicatedJob)
        try keyedContainer.encodeIfPresent(globalJob, forKey: .globalJob)
    }
}
