//
// SwarmSpecDispatcher.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Dispatcher configuration.
internal struct SwarmSpecDispatcher: Sendable, Content, Hashable {

    /** The delay for an agent to send a heartbeat to the dispatcher.  */
    internal var heartbeatPeriod: Int64?

    internal init(heartbeatPeriod: Int64? = nil) {
        self.heartbeatPeriod = heartbeatPeriod
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case heartbeatPeriod = "HeartbeatPeriod"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(heartbeatPeriod, forKey: .heartbeatPeriod)
    }
}
