//
// SwarmSpecOrchestration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Orchestration configuration.
internal struct SwarmSpecOrchestration: Sendable, Content, Hashable {

    /** The number of historic tasks to keep per instance or node. If negative, never remove completed or failed tasks.  */
    internal var taskHistoryRetentionLimit: Int64?

    internal init(taskHistoryRetentionLimit: Int64? = nil) {
        self.taskHistoryRetentionLimit = taskHistoryRetentionLimit
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case taskHistoryRetentionLimit = "TaskHistoryRetentionLimit"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(taskHistoryRetentionLimit, forKey: .taskHistoryRetentionLimit)
    }
}
