//
// SwarmSpecEncryptionConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Parameters related to encryption-at-rest.
internal struct SwarmSpecEncryptionConfig: Sendable, Content, Hashable {

    /** If set, generate a key and use it to lock data stored on the managers.  */
    internal var autoLockManagers: Bool?

    internal init(autoLockManagers: Bool? = nil) {
        self.autoLockManagers = autoLockManagers
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case autoLockManagers = "AutoLockManagers"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(autoLockManagers, forKey: .autoLockManagers)
    }
}
