//
// SwarmSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// User modifiable swarm configuration.
internal struct SwarmSpec: Sendable, Content, Hashable {

    /** Name of the swarm. */
    internal var name: String?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    internal var orchestration: SwarmSpecOrchestration?
    internal var raft: SwarmSpecRaft?
    internal var dispatcher: SwarmSpecDispatcher?
    internal var cAConfig: SwarmSpecCAConfig?
    internal var encryptionConfig: SwarmSpecEncryptionConfig?
    internal var taskDefaults: SwarmSpecTaskDefaults?

    internal init(
        name: String? = nil, labels: [String: String]? = nil, orchestration: SwarmSpecOrchestration? = nil, raft: SwarmSpecRaft? = nil, dispatcher: SwarmSpecDispatcher? = nil,
        cAConfig: SwarmSpecCAConfig? = nil, encryptionConfig: SwarmSpecEncryptionConfig? = nil, taskDefaults: SwarmSpecTaskDefaults? = nil
    ) {
        self.name = name
        self.labels = labels
        self.orchestration = orchestration
        self.raft = raft
        self.dispatcher = dispatcher
        self.cAConfig = cAConfig
        self.encryptionConfig = encryptionConfig
        self.taskDefaults = taskDefaults
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case labels = "Labels"
        case orchestration = "Orchestration"
        case raft = "Raft"
        case dispatcher = "Dispatcher"
        case cAConfig = "CAConfig"
        case encryptionConfig = "EncryptionConfig"
        case taskDefaults = "TaskDefaults"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(orchestration, forKey: .orchestration)
        try keyedContainer.encodeIfPresent(raft, forKey: .raft)
        try keyedContainer.encodeIfPresent(dispatcher, forKey: .dispatcher)
        try keyedContainer.encodeIfPresent(cAConfig, forKey: .cAConfig)
        try keyedContainer.encodeIfPresent(encryptionConfig, forKey: .encryptionConfig)
        try keyedContainer.encodeIfPresent(taskDefaults, forKey: .taskDefaults)
    }
}
