//
// SwarmSpecCAConfigExternalCAsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SwarmSpecCAConfigExternalCAsInner: Sendable, Content, Hashable {

    internal enum ModelProtocol: String, Sendable, Content, Hashable, CaseIterable {
        case cfssl = "cfssl"
    }
    /** Protocol for communication with the external CA (currently only `cfssl` is supported).  */
    internal var `protocol`: ModelProtocol? = .cfssl
    /** URL where certificate signing requests should be sent.  */
    internal var URL: String?
    /** An object with key/value pairs that are interpreted as protocol-specific options for the external CA driver.  */
    internal var options: [String: String]?
    /** The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to be to the current swarm root CA certificate if not provided).  */
    internal var cACert: String?

    internal init(`protocol`: ModelProtocol? = .cfssl, URL: String? = nil, options: [String: String]? = nil, cACert: String? = nil) {
        self.`protocol` = `protocol`
        self.URL = URL
        self.options = options
        self.cACert = cACert
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case `protocol` = "Protocol"
        case URL
        case options = "Options"
        case cACert = "CACert"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(`protocol`, forKey: .`protocol`)
        try keyedContainer.encodeIfPresent(URL, forKey: .URL)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
        try keyedContainer.encodeIfPresent(cACert, forKey: .cACert)
    }
}
