//
// SwarmSpecCAConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// CA configuration.
internal struct SwarmSpecCAConfig: Sendable, Content, Hashable {

    /** The duration node certificates are issued for. */
    internal var nodeCertExpiry: Int64?
    /** Configuration for forwarding signing requests to an external certificate authority.  */
    internal var externalCAs: [SwarmSpecCAConfigExternalCAsInner]?
    /** The desired signing CA certificate for all swarm node TLS leaf certificates, in PEM format.  */
    internal var signingCACert: String?
    /** The desired signing CA key for all swarm node TLS leaf certificates, in PEM format.  */
    internal var signingCAKey: String?
    /** An integer whose purpose is to force swarm to generate a new signing CA certificate and key, if none have been specified in `SigningCACert` and `SigningCAKey`  */
    internal var forceRotate: Int?

    internal init(
        nodeCertExpiry: Int64? = nil, externalCAs: [SwarmSpecCAConfigExternalCAsInner]? = nil, signingCACert: String? = nil, signingCAKey: String? = nil, forceRotate: Int? = nil
    ) {
        self.nodeCertExpiry = nodeCertExpiry
        self.externalCAs = externalCAs
        self.signingCACert = signingCACert
        self.signingCAKey = signingCAKey
        self.forceRotate = forceRotate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case nodeCertExpiry = "NodeCertExpiry"
        case externalCAs = "ExternalCAs"
        case signingCACert = "SigningCACert"
        case signingCAKey = "SigningCAKey"
        case forceRotate = "ForceRotate"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(nodeCertExpiry, forKey: .nodeCertExpiry)
        try keyedContainer.encodeIfPresent(externalCAs, forKey: .externalCAs)
        try keyedContainer.encodeIfPresent(signingCACert, forKey: .signingCACert)
        try keyedContainer.encodeIfPresent(signingCAKey, forKey: .signingCAKey)
        try keyedContainer.encodeIfPresent(forceRotate, forKey: .forceRotate)
    }
}
