//
// SwarmInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Represents generic information about swarm.
internal struct SwarmInfo: Sendable, Content, Hashable {

    /** Unique identifier of for this node in the swarm. */
    internal var nodeID: String? = ""
    /** IP address at which this node can be reached by other nodes in the swarm.  */
    internal var nodeAddr: String? = ""
    internal var localNodeState: LocalNodeState?
    internal var controlAvailable: Bool? = false
    internal var error: String? = ""
    /** List of ID's and addresses of other managers in the swarm.  */
    internal var remoteManagers: [PeerNode]?
    /** Total number of nodes in the swarm. */
    internal var nodes: Int?
    /** Total number of managers in the swarm. */
    internal var managers: Int?
    internal var cluster: ClusterInfo?

    internal init(
        nodeID: String? = "", nodeAddr: String? = "", localNodeState: LocalNodeState? = nil, controlAvailable: Bool? = false, error: String? = "",
        remoteManagers: [PeerNode]? = nil, nodes: Int? = nil, managers: Int? = nil, cluster: ClusterInfo? = nil
    ) {
        self.nodeID = nodeID
        self.nodeAddr = nodeAddr
        self.localNodeState = localNodeState
        self.controlAvailable = controlAvailable
        self.error = error
        self.remoteManagers = remoteManagers
        self.nodes = nodes
        self.managers = managers
        self.cluster = cluster
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case nodeID = "NodeID"
        case nodeAddr = "NodeAddr"
        case localNodeState = "LocalNodeState"
        case controlAvailable = "ControlAvailable"
        case error = "Error"
        case remoteManagers = "RemoteManagers"
        case nodes = "Nodes"
        case managers = "Managers"
        case cluster = "Cluster"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(nodeID, forKey: .nodeID)
        try keyedContainer.encodeIfPresent(nodeAddr, forKey: .nodeAddr)
        try keyedContainer.encodeIfPresent(localNodeState, forKey: .localNodeState)
        try keyedContainer.encodeIfPresent(controlAvailable, forKey: .controlAvailable)
        try keyedContainer.encodeIfPresent(error, forKey: .error)
        try keyedContainer.encodeIfPresent(remoteManagers, forKey: .remoteManagers)
        try keyedContainer.encodeIfPresent(nodes, forKey: .nodes)
        try keyedContainer.encodeIfPresent(managers, forKey: .managers)
        try keyedContainer.encodeIfPresent(cluster, forKey: .cluster)
    }
}
