//
// SwarmJoinRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SwarmJoinRequest: Sendable, Content, Hashable {

    /** Listen address used for inter-manager communication if the node gets promoted to manager, as well as determining the networking interface used for the VXLAN Tunnel Endpoint (VTEP).  */
    internal var listenAddr: String?
    /** Externally reachable address advertised to other nodes. This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the port number from the listen address is used. If `AdvertiseAddr` is not specified, it will be automatically detected when possible.  */
    internal var advertiseAddr: String?
    /** Address or interface to use for data path traffic (format: `<ip|interface>`), for example,  `192.168.1.1`, or an interface, like `eth0`. If `DataPathAddr` is unspecified, the same address as `AdvertiseAddr` is used.  The `DataPathAddr` specifies the address that global scope network drivers will publish towards other nodes in order to reach the containers running on this node. Using this parameter it is possible to separate the container data traffic from the management traffic of the cluster.  */
    internal var dataPathAddr: String?
    /** Addresses of manager nodes already participating in the swarm.  */
    internal var remoteAddrs: [String]?
    /** Secret token for joining this swarm. */
    internal var joinToken: String?

    internal init(listenAddr: String? = nil, advertiseAddr: String? = nil, dataPathAddr: String? = nil, remoteAddrs: [String]? = nil, joinToken: String? = nil) {
        self.listenAddr = listenAddr
        self.advertiseAddr = advertiseAddr
        self.dataPathAddr = dataPathAddr
        self.remoteAddrs = remoteAddrs
        self.joinToken = joinToken
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case listenAddr = "ListenAddr"
        case advertiseAddr = "AdvertiseAddr"
        case dataPathAddr = "DataPathAddr"
        case remoteAddrs = "RemoteAddrs"
        case joinToken = "JoinToken"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(listenAddr, forKey: .listenAddr)
        try keyedContainer.encodeIfPresent(advertiseAddr, forKey: .advertiseAddr)
        try keyedContainer.encodeIfPresent(dataPathAddr, forKey: .dataPathAddr)
        try keyedContainer.encodeIfPresent(remoteAddrs, forKey: .remoteAddrs)
        try keyedContainer.encodeIfPresent(joinToken, forKey: .joinToken)
    }
}
