//
// SwarmSpecTaskDefaultsLogDriver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// The log driver to use for tasks created in the orchestrator if unspecified by a service.  Updating this value only affects new tasks. Existing tasks continue to use their previously configured log driver until recreated.
internal struct SwarmSpecTaskDefaultsLogDriver: Sendable, Content, Hashable {

    /** The log driver to use as a default for new tasks.  */
    internal var name: String?
    /** Driver-specific options for the selected log driver, specified as key/value pairs.  */
    internal var options: [String: String]?

    internal init(name: String? = nil, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
