//
// SwarmUnlockRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SwarmUnlockRequest: Sendable, Content, Hashable {

    /** The swarm's unlock key. */
    internal var unlockKey: String?

    internal init(unlockKey: String? = nil) {
        self.unlockKey = unlockKey
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case unlockKey = "UnlockKey"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(unlockKey, forKey: .unlockKey)
    }
}
