//
// SwarmSpecTaskDefaults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Defaults for creating tasks in this cluster.
internal struct SwarmSpecTaskDefaults: Sendable, Content, Hashable {

    internal var logDriver: SwarmSpecTaskDefaultsLogDriver?

    internal init(logDriver: SwarmSpecTaskDefaultsLogDriver? = nil) {
        self.logDriver = logDriver
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case logDriver = "LogDriver"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(logDriver, forKey: .logDriver)
    }
}
