//
// SwarmSpecRaft.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Raft configuration.
internal struct SwarmSpecRaft: Sendable, Content, Hashable {

    /** The number of log entries between snapshots. */
    internal var snapshotInterval: Int?
    /** The number of snapshots to keep beyond the current snapshot.  */
    internal var keepOldSnapshots: Int?
    /** The number of log entries to keep around to sync up slow followers after a snapshot is created.  */
    internal var logEntriesForSlowFollowers: Int?
    /** The number of ticks that a follower will wait for a message from the leader before becoming a candidate and starting an election. `ElectionTick` must be greater than `HeartbeatTick`.  A tick currently defaults to one second, so these translate directly to seconds currently, but this is NOT guaranteed.  */
    internal var electionTick: Int?
    /** The number of ticks between heartbeats. Every HeartbeatTick ticks, the leader will send a heartbeat to the followers.  A tick currently defaults to one second, so these translate directly to seconds currently, but this is NOT guaranteed.  */
    internal var heartbeatTick: Int?

    internal init(snapshotInterval: Int? = nil, keepOldSnapshots: Int? = nil, logEntriesForSlowFollowers: Int? = nil, electionTick: Int? = nil, heartbeatTick: Int? = nil) {
        self.snapshotInterval = snapshotInterval
        self.keepOldSnapshots = keepOldSnapshots
        self.logEntriesForSlowFollowers = logEntriesForSlowFollowers
        self.electionTick = electionTick
        self.heartbeatTick = heartbeatTick
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case snapshotInterval = "SnapshotInterval"
        case keepOldSnapshots = "KeepOldSnapshots"
        case logEntriesForSlowFollowers = "LogEntriesForSlowFollowers"
        case electionTick = "ElectionTick"
        case heartbeatTick = "HeartbeatTick"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(snapshotInterval, forKey: .snapshotInterval)
        try keyedContainer.encodeIfPresent(keepOldSnapshots, forKey: .keepOldSnapshots)
        try keyedContainer.encodeIfPresent(logEntriesForSlowFollowers, forKey: .logEntriesForSlowFollowers)
        try keyedContainer.encodeIfPresent(electionTick, forKey: .electionTick)
        try keyedContainer.encodeIfPresent(heartbeatTick, forKey: .heartbeatTick)
    }
}
