//
// SystemVersionPlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemVersionPlatform: Sendable, Content, Hashable {

    internal var name: String

    internal init(name: String) {
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
    }
}
