//
// SystemVersionComponentsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemVersionComponentsInner: Sendable, Content, Hashable {

    /** Name of the component  */
    internal var name: String
    /** Version of the component  */
    internal var version: String
    /** Key/value pairs of strings with additional information about the component. These values are intended for informational purposes only, and their content is not defined, and not part of the API specification.  These messages can be printed by the client as information to the user.  */
    internal var details: JSONValue?

    internal init(name: String, version: String, details: JSONValue? = nil) {
        self.name = name
        self.version = version
        self.details = details
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case version = "Version"
        case details = "Details"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(version, forKey: .version)
        try keyedContainer.encodeIfPresent(details, forKey: .details)
    }
}
