//
// SystemAuthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemAuthResponse: Sendable, Content, Hashable {

    /** The status of the authentication */
    internal var status: String
    /** An opaque token used to authenticate a user after a successful login */
    internal var identityToken: String?

    internal init(status: String, identityToken: String? = nil) {
        self.status = status
        self.identityToken = identityToken
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case status = "Status"
        case identityToken = "IdentityToken"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(status, forKey: .status)
        try keyedContainer.encodeIfPresent(identityToken, forKey: .identityToken)
    }
}
