//
// SystemInfoDefaultAddressPoolsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemInfoDefaultAddressPoolsInner: Sendable, Content, Hashable {

    /** The network address in CIDR format */
    internal var base: String?
    /** The network pool size */
    internal var size: Int?

    internal init(base: String? = nil, size: Int? = nil) {
        self.base = base
        self.size = size
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case base = "Base"
        case size = "Size"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(base, forKey: .base)
        try keyedContainer.encodeIfPresent(size, forKey: .size)
    }
}
