//
// SystemVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Response of Engine API: GET \&quot;/version\&quot;
internal struct SystemVersion: Sendable, Content, Hashable {

    internal var platform: SystemVersionPlatform?
    /** Information about system components  */
    internal var components: [SystemVersionComponentsInner]?
    /** The version of the daemon */
    internal var version: String?
    /** The default (and highest) API version that is supported by the daemon  */
    internal var apiVersion: String?
    /** The minimum API version that is supported by the daemon  */
    internal var minAPIVersion: String?
    /** The Git commit of the source code that was used to build the daemon  */
    internal var gitCommit: String?
    /** The version Go used to compile the daemon, and the version of the Go runtime in use.  */
    internal var goVersion: String?
    /** The operating system that the daemon is running on (\"linux\" or \"windows\")  */
    internal var os: String?
    /** Architecture of the daemon, as returned by the Go runtime (`GOARCH`).  A full list of possible values can be found in the [Go documentation](https://go.dev/doc/install/source#environment).  */
    internal var arch: String?
    /** The kernel version (`uname -r`) that the daemon is running on.  This field is omitted when empty.  */
    internal var kernelVersion: String?
    /** Indicates if the daemon is started with experimental features enabled.  This field is omitted when empty / false.  */
    internal var experimental: Bool?
    /** The date and time that the daemon was compiled.  */
    internal var buildTime: String?

    internal init(
        platform: SystemVersionPlatform? = nil, components: [SystemVersionComponentsInner]? = nil, version: String? = nil, apiVersion: String? = nil, minAPIVersion: String? = nil,
        gitCommit: String? = nil, goVersion: String? = nil, os: String? = nil, arch: String? = nil, kernelVersion: String? = nil, experimental: Bool? = nil,
        buildTime: String? = nil
    ) {
        self.platform = platform
        self.components = components
        self.version = version
        self.apiVersion = apiVersion
        self.minAPIVersion = minAPIVersion
        self.gitCommit = gitCommit
        self.goVersion = goVersion
        self.os = os
        self.arch = arch
        self.kernelVersion = kernelVersion
        self.experimental = experimental
        self.buildTime = buildTime
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case platform = "Platform"
        case components = "Components"
        case version = "Version"
        case apiVersion = "ApiVersion"
        case minAPIVersion = "MinAPIVersion"
        case gitCommit = "GitCommit"
        case goVersion = "GoVersion"
        case os = "Os"
        case arch = "Arch"
        case kernelVersion = "KernelVersion"
        case experimental = "Experimental"
        case buildTime = "BuildTime"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(platform, forKey: .platform)
        try keyedContainer.encodeIfPresent(components, forKey: .components)
        try keyedContainer.encodeIfPresent(version, forKey: .version)
        try keyedContainer.encodeIfPresent(apiVersion, forKey: .apiVersion)
        try keyedContainer.encodeIfPresent(minAPIVersion, forKey: .minAPIVersion)
        try keyedContainer.encodeIfPresent(gitCommit, forKey: .gitCommit)
        try keyedContainer.encodeIfPresent(goVersion, forKey: .goVersion)
        try keyedContainer.encodeIfPresent(os, forKey: .os)
        try keyedContainer.encodeIfPresent(arch, forKey: .arch)
        try keyedContainer.encodeIfPresent(kernelVersion, forKey: .kernelVersion)
        try keyedContainer.encodeIfPresent(experimental, forKey: .experimental)
        try keyedContainer.encodeIfPresent(buildTime, forKey: .buildTime)
    }
}
