//
// SystemDataUsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemDataUsageResponse: Sendable, Content, Hashable {

    internal var layersSize: Int64?
    internal var images: [ImageSummary]?
    internal var containers: [ContainerSummary]?
    internal var volumes: [Volume]?
    internal var buildCache: [BuildCache]?

    internal init(layersSize: Int64? = nil, images: [ImageSummary]? = nil, containers: [ContainerSummary]? = nil, volumes: [Volume]? = nil, buildCache: [BuildCache]? = nil) {
        self.layersSize = layersSize
        self.images = images
        self.containers = containers
        self.volumes = volumes
        self.buildCache = buildCache
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case layersSize = "LayersSize"
        case images = "Images"
        case containers = "Containers"
        case volumes = "Volumes"
        case buildCache = "BuildCache"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(layersSize, forKey: .layersSize)
        try keyedContainer.encodeIfPresent(images, forKey: .images)
        try keyedContainer.encodeIfPresent(containers, forKey: .containers)
        try keyedContainer.encodeIfPresent(volumes, forKey: .volumes)
        try keyedContainer.encodeIfPresent(buildCache, forKey: .buildCache)
    }
}
