//
// SystemInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct SystemInfo: Sendable, Content, Hashable {

    internal enum CgroupDriver: String, Sendable, Content, Hashable, CaseIterable {
        case cgroupfs = "cgroupfs"
        case systemd = "systemd"
        case `none` = "none"
    }
    internal enum CgroupVersion: String, Sendable, Content, Hashable, CaseIterable {
        case _1 = "1"
        case _2 = "2"
    }
    internal enum Isolation: String, Sendable, Content, Hashable, CaseIterable {
        case `default` = "default"
        case hyperv = "hyperv"
        case process = "process"
        case empty = ""
    }
    /** Unique identifier of the daemon.  <p><br /></p>  > **Note**: The format of the ID itself is not part of the API, and > should not be considered stable.  */
    internal var ID: String?
    /** Total number of containers on the host. */
    internal var containers: Int?
    /** Number of containers with status `\"running\"`.  */
    internal var containersRunning: Int?
    /** Number of containers with status `\"paused\"`.  */
    internal var containersPaused: Int?
    /** Number of containers with status `\"stopped\"`.  */
    internal var containersStopped: Int?
    /** Total number of images on the host.  Both _tagged_ and _untagged_ (dangling) images are counted.  */
    internal var images: Int?
    /** Name of the storage driver in use. */
    internal var driver: String?
    /** Information specific to the storage driver, provided as \"label\" / \"value\" pairs.  This information is provided by the storage driver, and formatted in a way consistent with the output of `docker info` on the command line.  <p><br /></p>  > **Note**: The information returned in this field, including the > formatting of values and labels, should not be considered stable, > and may change without notice.  */
    internal var driverStatus: [[String]]?
    /** Root directory of persistent Docker state.  Defaults to `/var/lib/docker` on Linux, and `C:\\ProgramData\\docker` on Windows.  */
    internal var dockerRootDir: String?
    internal var plugins: PluginsInfo?
    /** Indicates if the host has memory limit support enabled. */
    internal var memoryLimit: Bool?
    /** Indicates if the host has memory swap limit support enabled. */
    internal var swapLimit: Bool?
    /** Indicates if the host has kernel memory TCP limit support enabled. This field is omitted if not supported.  Kernel memory TCP limits are not supported when using cgroups v2, which does not support the corresponding `memory.kmem.tcp.limit_in_bytes` cgroup.  **Deprecated**: This field is deprecated as kernel 6.12 has deprecated kernel memory TCP accounting.  */
    internal var kernelMemoryTCP: Bool?
    /** Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.  */
    internal var cpuCfsPeriod: Bool?
    /** Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.  */
    internal var cpuCfsQuota: Bool?
    /** Indicates if CPU Shares limiting is supported by the host.  */
    internal var cPUShares: Bool?
    /** Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.  See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)  */
    internal var cPUSet: Bool?
    /** Indicates if the host kernel has PID limit support enabled. */
    internal var pidsLimit: Bool?
    /** Indicates if OOM killer disable is supported on the host. */
    internal var oomKillDisable: Bool?
    /** Indicates IPv4 forwarding is enabled. */
    internal var iPv4Forwarding: Bool?
    /** Indicates if the daemon is running in debug-mode / with debug-level logging enabled.  */
    internal var debug: Bool?
    /** The total number of file Descriptors in use by the daemon process.  This information is only returned if debug-mode is enabled.  */
    internal var nFd: Int?
    /** The  number of goroutines that currently exist.  This information is only returned if debug-mode is enabled.  */
    internal var nGoroutines: Int?
    /** Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  */
    internal var systemTime: String?
    /** The logging driver to use as a default for new containers.  */
    internal var loggingDriver: String?
    /** The driver to use for managing cgroups.  */
    internal var cgroupDriver: CgroupDriver? = .cgroupfs
    /** The version of the cgroup.  */
    internal var cgroupVersion: CgroupVersion? = ._1
    /** Number of event listeners subscribed. */
    internal var nEventsListener: Int?
    /** Kernel version of the host.  On Linux, this information obtained from `uname`. On Windows this information is queried from the <kbd>HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\</kbd> registry value, for example _\"10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)\"_.  */
    internal var kernelVersion: String?
    /** Name of the host's operating system, for example: \"Ubuntu 24.04 LTS\" or \"Windows Server 2016 Datacenter\"  */
    internal var operatingSystem: String?
    /** Version of the host's operating system  <p><br /></p>  > **Note**: The information returned in this field, including its > very existence, and the formatting of values, should not be considered > stable, and may change without notice.  */
    internal var oSVersion: String?
    /** Generic type of the operating system of the host, as returned by the Go runtime (`GOOS`).  Currently returned values are \"linux\" and \"windows\". A full list of possible values can be found in the [Go documentation](https://go.dev/doc/install/source#environment).  */
    internal var oSType: String?
    /** Hardware architecture of the host, as returned by the operating system. This is equivalent to the output of `uname -m` on Linux.  Unlike `Arch` (from `/version`), this reports the machine's native architecture, which can differ from the Go runtime architecture when running a binary compiled for a different architecture (for example, a 32-bit binary running on 64-bit hardware).  */
    internal var architecture: String?
    /** The number of logical CPUs usable by the daemon.  The number of available CPUs is checked by querying the operating system when the daemon starts. Changes to operating system CPU allocation after the daemon is started are not reflected.  */
    internal var NCPU: Int?
    /** Total amount of physical memory available on the host, in bytes.  */
    internal var memTotal: Int64?
    /** Address / URL of the index server that is used for image search, and as a default for user authentication for Docker Hub and Docker Cloud.  */
    internal var indexServerAddress: String? = "https://index.docker.io/v1/"
    internal var registryConfig: RegistryServiceConfig?
    /** User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, `GPU=UUID1`).  */
    internal var genericResources: [GenericResourcesInner]?
    /** HTTP-proxy configured for the daemon. This value is obtained from the [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  */
    internal var httpProxy: String?
    /** HTTPS-proxy configured for the daemon. This value is obtained from the [`HTTPS_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  */
    internal var httpsProxy: String?
    /** Comma-separated list of domain extensions for which no proxy should be used. This value is obtained from the [`NO_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.  Containers do not automatically inherit this configuration.  */
    internal var noProxy: String?
    /** Hostname of the host. */
    internal var name: String?
    /** User-defined labels (key/value metadata) as set on the daemon.  <p><br /></p>  > **Note**: When part of a Swarm, nodes can both have _daemon_ labels, > set through the daemon configuration, and _node_ labels, set from a > manager node in the Swarm. Node labels are not included in this > field. Node labels can be retrieved using the `/nodes/(id)` endpoint > on a manager node in the Swarm.  */
    internal var labels: [String]?
    /** Indicates if experimental features are enabled on the daemon.  */
    internal var experimentalBuild: Bool?
    /** Version string of the daemon.  */
    internal var serverVersion: String?
    /** List of [OCI compliant](https://github.com/opencontainers/runtime-spec) runtimes configured on the daemon. Keys hold the \"name\" used to reference the runtime.  The Docker daemon relies on an OCI compliant runtime (invoked via the `containerd` daemon) as its interface to the Linux kernel namespaces, cgroups, and SELinux.  The default runtime is `runc`, and automatically configured. Additional runtimes can be configured by the user and will be listed here.  */
    internal var runtimes: [String: Runtime]?
    /** Name of the default OCI runtime that is used when starting containers.  The default can be overridden per-container at create time.  */
    internal var defaultRuntime: String? = "runc"
    internal var swarm: SwarmInfo?
    /** Indicates if live restore is enabled.  If enabled, containers are kept running when the daemon is shutdown or upon daemon start if running containers are detected.  */
    internal var liveRestoreEnabled: Bool? = false
    /** Represents the isolation technology to use as a default for containers. The supported values are platform-specific.  If no isolation value is specified on daemon start, on Windows client, the default is `hyperv`, and on Windows server, the default is `process`.  This option is currently not used on other platforms.  */
    internal var isolation: Isolation? = .`default`
    /** Name and, optional, path of the `docker-init` binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  */
    internal var initBinary: String?
    internal var containerdCommit: Commit?
    internal var runcCommit: Commit?
    internal var initCommit: Commit?
    /** List of security features that are enabled on the daemon, such as apparmor, seccomp, SELinux, user-namespaces (userns), rootless and no-new-privileges.  Additional configuration options for each security feature may be present, and are included as a comma-separated list of key/value pairs.  */
    internal var securityOptions: [String]?
    /** Reports a summary of the product license on the daemon.  If a commercial license has been applied to the daemon, information such as number of nodes, and expiration are included.  */
    internal var productLicense: String?
    /** List of custom default address pools for local networks, which can be specified in the daemon.json file or dockerd option.  Example: a Base \"10.10.0.0/16\" with Size 24 will define the set of 256 10.10.[0-255].0/24 address pools.  */
    internal var defaultAddressPools: [SystemInfoDefaultAddressPoolsInner]?
    internal var firewallBackend: FirewallInfo?
    /** List of devices discovered by device drivers.  Each device includes information about its source driver, kind, name, and additional driver-specific attributes.  */
    internal var discoveredDevices: [DeviceInfo]?
    /** List of warnings / informational messages about missing features, or issues related to the daemon configuration.  These messages can be printed by the client as information to the user.  */
    internal var warnings: [String]?
    /** List of directories where (Container Device Interface) CDI specifications are located.  These specifications define vendor-specific modifications to an OCI runtime specification for a container being created.  An empty list indicates that CDI device injection is disabled.  Note that since using CDI device injection requires the daemon to have experimental enabled. For non-experimental daemons an empty list will always be returned.  */
    internal var cDISpecDirs: [String]?
    internal var containerd: ContainerdInfo?

    internal init(
        ID: String? = nil, containers: Int? = nil, containersRunning: Int? = nil, containersPaused: Int? = nil, containersStopped: Int? = nil, images: Int? = nil,
        driver: String? = nil, driverStatus: [[String]]? = nil, dockerRootDir: String? = nil, plugins: PluginsInfo? = nil, memoryLimit: Bool? = nil, swapLimit: Bool? = nil,
        kernelMemoryTCP: Bool? = nil, cpuCfsPeriod: Bool? = nil, cpuCfsQuota: Bool? = nil, cPUShares: Bool? = nil, cPUSet: Bool? = nil, pidsLimit: Bool? = nil,
        oomKillDisable: Bool? = nil, iPv4Forwarding: Bool? = nil, debug: Bool? = nil, nFd: Int? = nil, nGoroutines: Int? = nil, systemTime: String? = nil,
        loggingDriver: String? = nil, cgroupDriver: CgroupDriver? = .cgroupfs, cgroupVersion: CgroupVersion? = ._1, nEventsListener: Int? = nil, kernelVersion: String? = nil,
        operatingSystem: String? = nil, oSVersion: String? = nil, oSType: String? = nil, architecture: String? = nil, NCPU: Int? = nil, memTotal: Int64? = nil,
        indexServerAddress: String? = "https://index.docker.io/v1/", registryConfig: RegistryServiceConfig? = nil, genericResources: [GenericResourcesInner]? = nil,
        httpProxy: String? = nil, httpsProxy: String? = nil, noProxy: String? = nil, name: String? = nil, labels: [String]? = nil, experimentalBuild: Bool? = nil,
        serverVersion: String? = nil, runtimes: [String: Runtime]? = nil, defaultRuntime: String? = "runc", swarm: SwarmInfo? = nil, liveRestoreEnabled: Bool? = false,
        isolation: Isolation? = .`default`, initBinary: String? = nil, containerdCommit: Commit? = nil, runcCommit: Commit? = nil, initCommit: Commit? = nil,
        securityOptions: [String]? = nil, productLicense: String? = nil, defaultAddressPools: [SystemInfoDefaultAddressPoolsInner]? = nil, firewallBackend: FirewallInfo? = nil,
        discoveredDevices: [DeviceInfo]? = nil, warnings: [String]? = nil, cDISpecDirs: [String]? = nil, containerd: ContainerdInfo? = nil
    ) {
        self.ID = ID
        self.containers = containers
        self.containersRunning = containersRunning
        self.containersPaused = containersPaused
        self.containersStopped = containersStopped
        self.images = images
        self.driver = driver
        self.driverStatus = driverStatus
        self.dockerRootDir = dockerRootDir
        self.plugins = plugins
        self.memoryLimit = memoryLimit
        self.swapLimit = swapLimit
        self.kernelMemoryTCP = kernelMemoryTCP
        self.cpuCfsPeriod = cpuCfsPeriod
        self.cpuCfsQuota = cpuCfsQuota
        self.cPUShares = cPUShares
        self.cPUSet = cPUSet
        self.pidsLimit = pidsLimit
        self.oomKillDisable = oomKillDisable
        self.iPv4Forwarding = iPv4Forwarding
        self.debug = debug
        self.nFd = nFd
        self.nGoroutines = nGoroutines
        self.systemTime = systemTime
        self.loggingDriver = loggingDriver
        self.cgroupDriver = cgroupDriver
        self.cgroupVersion = cgroupVersion
        self.nEventsListener = nEventsListener
        self.kernelVersion = kernelVersion
        self.operatingSystem = operatingSystem
        self.oSVersion = oSVersion
        self.oSType = oSType
        self.architecture = architecture
        self.NCPU = NCPU
        self.memTotal = memTotal
        self.indexServerAddress = indexServerAddress
        self.registryConfig = registryConfig
        self.genericResources = genericResources
        self.httpProxy = httpProxy
        self.httpsProxy = httpsProxy
        self.noProxy = noProxy
        self.name = name
        self.labels = labels
        self.experimentalBuild = experimentalBuild
        self.serverVersion = serverVersion
        self.runtimes = runtimes
        self.defaultRuntime = defaultRuntime
        self.swarm = swarm
        self.liveRestoreEnabled = liveRestoreEnabled
        self.isolation = isolation
        self.initBinary = initBinary
        self.containerdCommit = containerdCommit
        self.runcCommit = runcCommit
        self.initCommit = initCommit
        self.securityOptions = securityOptions
        self.productLicense = productLicense
        self.defaultAddressPools = defaultAddressPools
        self.firewallBackend = firewallBackend
        self.discoveredDevices = discoveredDevices
        self.warnings = warnings
        self.cDISpecDirs = cDISpecDirs
        self.containerd = containerd
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case containers = "Containers"
        case containersRunning = "ContainersRunning"
        case containersPaused = "ContainersPaused"
        case containersStopped = "ContainersStopped"
        case images = "Images"
        case driver = "Driver"
        case driverStatus = "DriverStatus"
        case dockerRootDir = "DockerRootDir"
        case plugins = "Plugins"
        case memoryLimit = "MemoryLimit"
        case swapLimit = "SwapLimit"
        case kernelMemoryTCP = "KernelMemoryTCP"
        case cpuCfsPeriod = "CpuCfsPeriod"
        case cpuCfsQuota = "CpuCfsQuota"
        case cPUShares = "CPUShares"
        case cPUSet = "CPUSet"
        case pidsLimit = "PidsLimit"
        case oomKillDisable = "OomKillDisable"
        case iPv4Forwarding = "IPv4Forwarding"
        case debug = "Debug"
        case nFd = "NFd"
        case nGoroutines = "NGoroutines"
        case systemTime = "SystemTime"
        case loggingDriver = "LoggingDriver"
        case cgroupDriver = "CgroupDriver"
        case cgroupVersion = "CgroupVersion"
        case nEventsListener = "NEventsListener"
        case kernelVersion = "KernelVersion"
        case operatingSystem = "OperatingSystem"
        case oSVersion = "OSVersion"
        case oSType = "OSType"
        case architecture = "Architecture"
        case NCPU
        case memTotal = "MemTotal"
        case indexServerAddress = "IndexServerAddress"
        case registryConfig = "RegistryConfig"
        case genericResources = "GenericResources"
        case httpProxy = "HttpProxy"
        case httpsProxy = "HttpsProxy"
        case noProxy = "NoProxy"
        case name = "Name"
        case labels = "Labels"
        case experimentalBuild = "ExperimentalBuild"
        case serverVersion = "ServerVersion"
        case runtimes = "Runtimes"
        case defaultRuntime = "DefaultRuntime"
        case swarm = "Swarm"
        case liveRestoreEnabled = "LiveRestoreEnabled"
        case isolation = "Isolation"
        case initBinary = "InitBinary"
        case containerdCommit = "ContainerdCommit"
        case runcCommit = "RuncCommit"
        case initCommit = "InitCommit"
        case securityOptions = "SecurityOptions"
        case productLicense = "ProductLicense"
        case defaultAddressPools = "DefaultAddressPools"
        case firewallBackend = "FirewallBackend"
        case discoveredDevices = "DiscoveredDevices"
        case warnings = "Warnings"
        case cDISpecDirs = "CDISpecDirs"
        case containerd = "Containerd"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(ID, forKey: .ID)
        try keyedContainer.encodeIfPresent(containers, forKey: .containers)
        try keyedContainer.encodeIfPresent(containersRunning, forKey: .containersRunning)
        try keyedContainer.encodeIfPresent(containersPaused, forKey: .containersPaused)
        try keyedContainer.encodeIfPresent(containersStopped, forKey: .containersStopped)
        try keyedContainer.encodeIfPresent(images, forKey: .images)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(driverStatus, forKey: .driverStatus)
        try keyedContainer.encodeIfPresent(dockerRootDir, forKey: .dockerRootDir)
        try keyedContainer.encodeIfPresent(plugins, forKey: .plugins)
        try keyedContainer.encodeIfPresent(memoryLimit, forKey: .memoryLimit)
        try keyedContainer.encodeIfPresent(swapLimit, forKey: .swapLimit)
        try keyedContainer.encodeIfPresent(kernelMemoryTCP, forKey: .kernelMemoryTCP)
        try keyedContainer.encodeIfPresent(cpuCfsPeriod, forKey: .cpuCfsPeriod)
        try keyedContainer.encodeIfPresent(cpuCfsQuota, forKey: .cpuCfsQuota)
        try keyedContainer.encodeIfPresent(cPUShares, forKey: .cPUShares)
        try keyedContainer.encodeIfPresent(cPUSet, forKey: .cPUSet)
        try keyedContainer.encodeIfPresent(pidsLimit, forKey: .pidsLimit)
        try keyedContainer.encodeIfPresent(oomKillDisable, forKey: .oomKillDisable)
        try keyedContainer.encodeIfPresent(iPv4Forwarding, forKey: .iPv4Forwarding)
        try keyedContainer.encodeIfPresent(debug, forKey: .debug)
        try keyedContainer.encodeIfPresent(nFd, forKey: .nFd)
        try keyedContainer.encodeIfPresent(nGoroutines, forKey: .nGoroutines)
        try keyedContainer.encodeIfPresent(systemTime, forKey: .systemTime)
        try keyedContainer.encodeIfPresent(loggingDriver, forKey: .loggingDriver)
        try keyedContainer.encodeIfPresent(cgroupDriver, forKey: .cgroupDriver)
        try keyedContainer.encodeIfPresent(cgroupVersion, forKey: .cgroupVersion)
        try keyedContainer.encodeIfPresent(nEventsListener, forKey: .nEventsListener)
        try keyedContainer.encodeIfPresent(kernelVersion, forKey: .kernelVersion)
        try keyedContainer.encodeIfPresent(operatingSystem, forKey: .operatingSystem)
        try keyedContainer.encodeIfPresent(oSVersion, forKey: .oSVersion)
        try keyedContainer.encodeIfPresent(oSType, forKey: .oSType)
        try keyedContainer.encodeIfPresent(architecture, forKey: .architecture)
        try keyedContainer.encodeIfPresent(NCPU, forKey: .NCPU)
        try keyedContainer.encodeIfPresent(memTotal, forKey: .memTotal)
        try keyedContainer.encodeIfPresent(indexServerAddress, forKey: .indexServerAddress)
        try keyedContainer.encodeIfPresent(registryConfig, forKey: .registryConfig)
        try keyedContainer.encodeIfPresent(genericResources, forKey: .genericResources)
        try keyedContainer.encodeIfPresent(httpProxy, forKey: .httpProxy)
        try keyedContainer.encodeIfPresent(httpsProxy, forKey: .httpsProxy)
        try keyedContainer.encodeIfPresent(noProxy, forKey: .noProxy)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(experimentalBuild, forKey: .experimentalBuild)
        try keyedContainer.encodeIfPresent(serverVersion, forKey: .serverVersion)
        try keyedContainer.encodeIfPresent(runtimes, forKey: .runtimes)
        try keyedContainer.encodeIfPresent(defaultRuntime, forKey: .defaultRuntime)
        try keyedContainer.encodeIfPresent(swarm, forKey: .swarm)
        try keyedContainer.encodeIfPresent(liveRestoreEnabled, forKey: .liveRestoreEnabled)
        try keyedContainer.encodeIfPresent(isolation, forKey: .isolation)
        try keyedContainer.encodeIfPresent(initBinary, forKey: .initBinary)
        try keyedContainer.encodeIfPresent(containerdCommit, forKey: .containerdCommit)
        try keyedContainer.encodeIfPresent(runcCommit, forKey: .runcCommit)
        try keyedContainer.encodeIfPresent(initCommit, forKey: .initCommit)
        try keyedContainer.encodeIfPresent(securityOptions, forKey: .securityOptions)
        try keyedContainer.encodeIfPresent(productLicense, forKey: .productLicense)
        try keyedContainer.encodeIfPresent(defaultAddressPools, forKey: .defaultAddressPools)
        try keyedContainer.encodeIfPresent(firewallBackend, forKey: .firewallBackend)
        try keyedContainer.encodeIfPresent(discoveredDevices, forKey: .discoveredDevices)
        try keyedContainer.encodeIfPresent(warnings, forKey: .warnings)
        try keyedContainer.encodeIfPresent(cDISpecDirs, forKey: .cDISpecDirs)
        try keyedContainer.encodeIfPresent(containerd, forKey: .containerd)
    }
}
