//
// TaskSpecRestartPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specification for the restart policy which applies to containers created as part of this service.
internal struct TaskSpecRestartPolicy: Sendable, Content, Hashable {

    internal enum Condition: String, Sendable, Content, Hashable, CaseIterable {
        case `none` = "none"
        case onFailure = "on-failure"
        case any = "any"
    }
    /** Condition for restart. */
    internal var condition: Condition?
    /** Delay between restart attempts. */
    internal var delay: Int64?
    /** Maximum attempts to restart a given container before giving up (default value is 0, which is ignored).  */
    internal var maxAttempts: Int64? = 0
    /** Windows is the time window used to evaluate the restart policy (default value is 0, which is unbounded).  */
    internal var window: Int64? = 0

    internal init(condition: Condition? = nil, delay: Int64? = nil, maxAttempts: Int64? = 0, window: Int64? = 0) {
        self.condition = condition
        self.delay = delay
        self.maxAttempts = maxAttempts
        self.window = window
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case condition = "Condition"
        case delay = "Delay"
        case maxAttempts = "MaxAttempts"
        case window = "Window"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(condition, forKey: .condition)
        try keyedContainer.encodeIfPresent(delay, forKey: .delay)
        try keyedContainer.encodeIfPresent(maxAttempts, forKey: .maxAttempts)
        try keyedContainer.encodeIfPresent(window, forKey: .window)
    }
}
