//
// TaskSpecContainerSpecDNSConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specification for DNS related configurations in resolver configuration file (&#x60;resolv.conf&#x60;).
internal struct TaskSpecContainerSpecDNSConfig: Sendable, Content, Hashable {

    /** The IP addresses of the name servers. */
    internal var nameservers: [String]?
    /** A search list for host-name lookup. */
    internal var search: [String]?
    /** A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).  */
    internal var options: [String]?

    internal init(nameservers: [String]? = nil, search: [String]? = nil, options: [String]? = nil) {
        self.nameservers = nameservers
        self.search = search
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case nameservers = "Nameservers"
        case search = "Search"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(nameservers, forKey: .nameservers)
        try keyedContainer.encodeIfPresent(search, forKey: .search)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
