//
// TaskSpecContainerSpecSecretsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct TaskSpecContainerSpecSecretsInner: Sendable, Content, Hashable {

    internal var file: TaskSpecContainerSpecSecretsInnerFile?
    /** SecretID represents the ID of the specific secret that we're referencing.  */
    internal var secretID: String?
    /** SecretName is the name of the secret that this references, but this is just provided for lookup/display purposes. The secret in the reference will be identified by its ID.  */
    internal var secretName: String?

    internal init(file: TaskSpecContainerSpecSecretsInnerFile? = nil, secretID: String? = nil, secretName: String? = nil) {
        self.file = file
        self.secretID = secretID
        self.secretName = secretName
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case file = "File"
        case secretID = "SecretID"
        case secretName = "SecretName"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(file, forKey: .file)
        try keyedContainer.encodeIfPresent(secretID, forKey: .secretID)
        try keyedContainer.encodeIfPresent(secretName, forKey: .secretName)
    }
}
