//
// TaskSpecLogDriver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified.
internal struct TaskSpecLogDriver: Sendable, Content, Hashable {

    internal var name: String?
    internal var options: [String: String]?

    internal init(name: String? = nil, options: [String: String]? = nil) {
        self.name = name
        self.options = options
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case options = "Options"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(options, forKey: .options)
    }
}
