//
// TaskSpecPlacementPreferencesInnerSpread.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct TaskSpecPlacementPreferencesInnerSpread: Sendable, Content, Hashable {

    /** label descriptor, such as `engine.labels.az`.  */
    internal var spreadDescriptor: String?

    internal init(spreadDescriptor: String? = nil) {
        self.spreadDescriptor = spreadDescriptor
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case spreadDescriptor = "SpreadDescriptor"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(spreadDescriptor, forKey: .spreadDescriptor)
    }
}
