//
// TaskSpecContainerSpecPrivilegesSeccomp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Options for configuring seccomp on the container
internal struct TaskSpecContainerSpecPrivilegesSeccomp: Sendable, Content, Hashable {

    internal enum Mode: String, Sendable, Content, Hashable, CaseIterable {
        case `default` = "default"
        case unconfined = "unconfined"
        case custom = "custom"
    }
    internal var mode: Mode?
    /** The custom seccomp profile as a json object */
    internal var profile: String?

    internal init(mode: Mode? = nil, profile: String? = nil) {
        self.mode = mode
        self.profile = profile
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mode = "Mode"
        case profile = "Profile"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
        try keyedContainer.encodeIfPresent(profile, forKey: .profile)
    }
}
