//
// TaskSpecContainerSpecConfigsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct TaskSpecContainerSpecConfigsInner: Sendable, Content, Hashable {

    internal var file: TaskSpecContainerSpecConfigsInnerFile?
    /** Runtime represents a target that is not mounted into the container but is used by the task  <p><br /><p>  > **Note**: `Configs.File` and `Configs.Runtime` are mutually > exclusive  */
    internal var runtime: JSONValue?
    /** ConfigID represents the ID of the specific config that we're referencing.  */
    internal var configID: String?
    /** ConfigName is the name of the config that this references, but this is just provided for lookup/display purposes. The config in the reference will be identified by its ID.  */
    internal var configName: String?

    internal init(file: TaskSpecContainerSpecConfigsInnerFile? = nil, runtime: JSONValue? = nil, configID: String? = nil, configName: String? = nil) {
        self.file = file
        self.runtime = runtime
        self.configID = configID
        self.configName = configName
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case file = "File"
        case runtime = "Runtime"
        case configID = "ConfigID"
        case configName = "ConfigName"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(file, forKey: .file)
        try keyedContainer.encodeIfPresent(runtime, forKey: .runtime)
        try keyedContainer.encodeIfPresent(configID, forKey: .configID)
        try keyedContainer.encodeIfPresent(configName, forKey: .configName)
    }
}
