//
// TaskSpecPlacementPreferencesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct TaskSpecPlacementPreferencesInner: Sendable, Content, Hashable {

    internal var spread: TaskSpecPlacementPreferencesInnerSpread?

    internal init(spread: TaskSpecPlacementPreferencesInnerSpread? = nil) {
        self.spread = spread
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case spread = "Spread"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(spread, forKey: .spread)
    }
}
