//
// TaskSpecContainerSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Container spec for the service.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are &gt; mutually exclusive. PluginSpec is only used when the Runtime field &gt; is set to &#x60;plugin&#x60;. NetworkAttachmentSpec is used when the Runtime &gt; field is set to &#x60;attachment&#x60;.
internal struct TaskSpecContainerSpec: Sendable, Content, Hashable {

    internal enum Isolation: String, Sendable, Content, Hashable, CaseIterable {
        case `default` = "default"
        case process = "process"
        case hyperv = "hyperv"
        case empty = ""
    }
    /** The image name to use for the container */
    internal var image: String?
    /** User-defined key/value data. */
    internal var labels: [String: String]?
    /** The command to be run in the image. */
    internal var command: [String]?
    /** Arguments to the command. */
    internal var args: [String]?
    /** The hostname to use for the container, as a valid [RFC 1123](https://tools.ietf.org/html/rfc1123) hostname.  */
    internal var hostname: String?
    /** A list of environment variables in the form `VAR=value`.  */
    internal var env: [String]?
    /** The working directory for commands to run in. */
    internal var dir: String?
    /** The user inside the container. */
    internal var user: String?
    /** A list of additional groups that the container process will run as.  */
    internal var groups: [String]?
    internal var privileges: TaskSpecContainerSpecPrivileges?
    /** Whether a pseudo-TTY should be allocated. */
    internal var TTY: Bool?
    /** Open `stdin` */
    internal var openStdin: Bool?
    /** Mount the container's root filesystem as read only. */
    internal var readOnly: Bool?
    /** Specification for mounts to be added to containers created as part of the service.  */
    internal var mounts: [Mount]?
    /** Signal to stop the container. */
    internal var stopSignal: String?
    /** Amount of time to wait for the container to terminate before forcefully killing it.  */
    internal var stopGracePeriod: Int64?
    internal var healthCheck: HealthConfig?
    /** A list of hostname/IP mappings to add to the container's `hosts` file. The format of extra hosts is specified in the [hosts(5)](http://man7.org/linux/man-pages/man5/hosts.5.html) man page:      IP_address canonical_hostname [aliases...]  */
    internal var hosts: [String]?
    internal var dNSConfig: TaskSpecContainerSpecDNSConfig?
    /** Secrets contains references to zero or more secrets that will be exposed to the service.  */
    internal var secrets: [TaskSpecContainerSpecSecretsInner]?
    /** An integer value containing the score given to the container in order to tune OOM killer preferences.  */
    internal var oomScoreAdj: Int64?
    /** Configs contains references to zero or more configs that will be exposed to the service.  */
    internal var configs: [TaskSpecContainerSpecConfigsInner]?
    /** Isolation technology of the containers running the service. (Windows only)  */
    internal var isolation: Isolation?
    /** Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.  */
    internal var `init`: Bool?
    /** Set kernel namedspaced parameters (sysctls) in the container. The Sysctls option on services accepts the same sysctls as the are supported on containers. Note that while the same sysctls are supported, no guarantees or checks are made about their suitability for a clustered environment, and it's up to the user to determine whether a given sysctl will work properly in a Service.  */
    internal var sysctls: [String: String]?
    /** A list of kernel capabilities to add to the default set for the container.  */
    internal var capabilityAdd: [String]?
    /** A list of kernel capabilities to drop from the default set for the container.  */
    internal var capabilityDrop: [String]?
    /** A list of resource limits to set in the container. For example: `{\"Name\": \"nofile\", \"Soft\": 1024, \"Hard\": 2048}`\"  */
    internal var ulimits: [ResourcesUlimitsInner]?

    internal init(
        image: String? = nil, labels: [String: String]? = nil, command: [String]? = nil, args: [String]? = nil, hostname: String? = nil, env: [String]? = nil, dir: String? = nil,
        user: String? = nil, groups: [String]? = nil, privileges: TaskSpecContainerSpecPrivileges? = nil, TTY: Bool? = nil, openStdin: Bool? = nil, readOnly: Bool? = nil,
        mounts: [Mount]? = nil, stopSignal: String? = nil, stopGracePeriod: Int64? = nil, healthCheck: HealthConfig? = nil, hosts: [String]? = nil,
        dNSConfig: TaskSpecContainerSpecDNSConfig? = nil, secrets: [TaskSpecContainerSpecSecretsInner]? = nil, oomScoreAdj: Int64? = nil,
        configs: [TaskSpecContainerSpecConfigsInner]? = nil, isolation: Isolation? = nil, `init`: Bool? = nil, sysctls: [String: String]? = nil, capabilityAdd: [String]? = nil,
        capabilityDrop: [String]? = nil, ulimits: [ResourcesUlimitsInner]? = nil
    ) {
        self.image = image
        self.labels = labels
        self.command = command
        self.args = args
        self.hostname = hostname
        self.env = env
        self.dir = dir
        self.user = user
        self.groups = groups
        self.privileges = privileges
        self.TTY = TTY
        self.openStdin = openStdin
        self.readOnly = readOnly
        self.mounts = mounts
        self.stopSignal = stopSignal
        self.stopGracePeriod = stopGracePeriod
        self.healthCheck = healthCheck
        self.hosts = hosts
        self.dNSConfig = dNSConfig
        self.secrets = secrets
        self.oomScoreAdj = oomScoreAdj
        self.configs = configs
        self.isolation = isolation
        self.`init` = `init`
        self.sysctls = sysctls
        self.capabilityAdd = capabilityAdd
        self.capabilityDrop = capabilityDrop
        self.ulimits = ulimits
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case image = "Image"
        case labels = "Labels"
        case command = "Command"
        case args = "Args"
        case hostname = "Hostname"
        case env = "Env"
        case dir = "Dir"
        case user = "User"
        case groups = "Groups"
        case privileges = "Privileges"
        case TTY
        case openStdin = "OpenStdin"
        case readOnly = "ReadOnly"
        case mounts = "Mounts"
        case stopSignal = "StopSignal"
        case stopGracePeriod = "StopGracePeriod"
        case healthCheck = "HealthCheck"
        case hosts = "Hosts"
        case dNSConfig = "DNSConfig"
        case secrets = "Secrets"
        case oomScoreAdj = "OomScoreAdj"
        case configs = "Configs"
        case isolation = "Isolation"
        case `init` = "Init"
        case sysctls = "Sysctls"
        case capabilityAdd = "CapabilityAdd"
        case capabilityDrop = "CapabilityDrop"
        case ulimits = "Ulimits"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(image, forKey: .image)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(command, forKey: .command)
        try keyedContainer.encodeIfPresent(args, forKey: .args)
        try keyedContainer.encodeIfPresent(hostname, forKey: .hostname)
        try keyedContainer.encodeIfPresent(env, forKey: .env)
        try keyedContainer.encodeIfPresent(dir, forKey: .dir)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(groups, forKey: .groups)
        try keyedContainer.encodeIfPresent(privileges, forKey: .privileges)
        try keyedContainer.encodeIfPresent(TTY, forKey: .TTY)
        try keyedContainer.encodeIfPresent(openStdin, forKey: .openStdin)
        try keyedContainer.encodeIfPresent(readOnly, forKey: .readOnly)
        try keyedContainer.encodeIfPresent(mounts, forKey: .mounts)
        try keyedContainer.encodeIfPresent(stopSignal, forKey: .stopSignal)
        try keyedContainer.encodeIfPresent(stopGracePeriod, forKey: .stopGracePeriod)
        try keyedContainer.encodeIfPresent(healthCheck, forKey: .healthCheck)
        try keyedContainer.encodeIfPresent(hosts, forKey: .hosts)
        try keyedContainer.encodeIfPresent(dNSConfig, forKey: .dNSConfig)
        try keyedContainer.encodeIfPresent(secrets, forKey: .secrets)
        try keyedContainer.encodeIfPresent(oomScoreAdj, forKey: .oomScoreAdj)
        try keyedContainer.encodeIfPresent(configs, forKey: .configs)
        try keyedContainer.encodeIfPresent(isolation, forKey: .isolation)
        try keyedContainer.encodeIfPresent(`init`, forKey: .`init`)
        try keyedContainer.encodeIfPresent(sysctls, forKey: .sysctls)
        try keyedContainer.encodeIfPresent(capabilityAdd, forKey: .capabilityAdd)
        try keyedContainer.encodeIfPresent(capabilityDrop, forKey: .capabilityDrop)
        try keyedContainer.encodeIfPresent(ulimits, forKey: .ulimits)
    }
}
