//
// TaskSpecContainerSpecPrivileges.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Security options for the container
internal struct TaskSpecContainerSpecPrivileges: Sendable, Content, Hashable {

    internal var credentialSpec: TaskSpecContainerSpecPrivilegesCredentialSpec?
    internal var sELinuxContext: TaskSpecContainerSpecPrivilegesSELinuxContext?
    internal var seccomp: TaskSpecContainerSpecPrivilegesSeccomp?
    internal var appArmor: TaskSpecContainerSpecPrivilegesAppArmor?
    /** Configuration of the no_new_privs bit in the container */
    internal var noNewPrivileges: Bool?

    internal init(
        credentialSpec: TaskSpecContainerSpecPrivilegesCredentialSpec? = nil, sELinuxContext: TaskSpecContainerSpecPrivilegesSELinuxContext? = nil,
        seccomp: TaskSpecContainerSpecPrivilegesSeccomp? = nil, appArmor: TaskSpecContainerSpecPrivilegesAppArmor? = nil, noNewPrivileges: Bool? = nil
    ) {
        self.credentialSpec = credentialSpec
        self.sELinuxContext = sELinuxContext
        self.seccomp = seccomp
        self.appArmor = appArmor
        self.noNewPrivileges = noNewPrivileges
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case credentialSpec = "CredentialSpec"
        case sELinuxContext = "SELinuxContext"
        case seccomp = "Seccomp"
        case appArmor = "AppArmor"
        case noNewPrivileges = "NoNewPrivileges"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(credentialSpec, forKey: .credentialSpec)
        try keyedContainer.encodeIfPresent(sELinuxContext, forKey: .sELinuxContext)
        try keyedContainer.encodeIfPresent(seccomp, forKey: .seccomp)
        try keyedContainer.encodeIfPresent(appArmor, forKey: .appArmor)
        try keyedContainer.encodeIfPresent(noNewPrivileges, forKey: .noNewPrivileges)
    }
}
