//
// TaskSpecResources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Resource requirements which apply to each individual container created as part of the service.
internal struct TaskSpecResources: Sendable, Content, Hashable {

    internal var limits: Limit?
    internal var reservations: ResourceObject?

    internal init(limits: Limit? = nil, reservations: ResourceObject? = nil) {
        self.limits = limits
        self.reservations = reservations
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case limits = "Limits"
        case reservations = "Reservations"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(limits, forKey: .limits)
        try keyedContainer.encodeIfPresent(reservations, forKey: .reservations)
    }
}
