//
// TaskSpecContainerSpecPrivilegesSELinuxContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// SELinux labels of the container
internal struct TaskSpecContainerSpecPrivilegesSELinuxContext: Sendable, Content, Hashable {

    /** Disable SELinux */
    internal var disable: Bool?
    /** SELinux user label */
    internal var user: String?
    /** SELinux role label */
    internal var role: String?
    /** SELinux type label */
    internal var type: String?
    /** SELinux level label */
    internal var level: String?

    internal init(disable: Bool? = nil, user: String? = nil, role: String? = nil, type: String? = nil, level: String? = nil) {
        self.disable = disable
        self.user = user
        self.role = role
        self.type = type
        self.level = level
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case disable = "Disable"
        case user = "User"
        case role = "Role"
        case type = "Type"
        case level = "Level"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(disable, forKey: .disable)
        try keyedContainer.encodeIfPresent(user, forKey: .user)
        try keyedContainer.encodeIfPresent(role, forKey: .role)
        try keyedContainer.encodeIfPresent(type, forKey: .type)
        try keyedContainer.encodeIfPresent(level, forKey: .level)
    }
}
