//
// TaskStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// represents the status of a task.
internal struct TaskStatus: Sendable, Content, Hashable {

    internal var timestamp: String?
    internal var state: TaskState?
    internal var message: String?
    internal var err: String?
    internal var containerStatus: ContainerStatus?
    internal var portStatus: PortStatus?

    internal init(
        timestamp: String? = nil, state: TaskState? = nil, message: String? = nil, err: String? = nil, containerStatus: ContainerStatus? = nil, portStatus: PortStatus? = nil
    ) {
        self.timestamp = timestamp
        self.state = state
        self.message = message
        self.err = err
        self.containerStatus = containerStatus
        self.portStatus = portStatus
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp = "Timestamp"
        case state = "State"
        case message = "Message"
        case err = "Err"
        case containerStatus = "ContainerStatus"
        case portStatus = "PortStatus"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(timestamp, forKey: .timestamp)
        try keyedContainer.encodeIfPresent(state, forKey: .state)
        try keyedContainer.encodeIfPresent(message, forKey: .message)
        try keyedContainer.encodeIfPresent(err, forKey: .err)
        try keyedContainer.encodeIfPresent(containerStatus, forKey: .containerStatus)
        try keyedContainer.encodeIfPresent(portStatus, forKey: .portStatus)
    }
}
