//
// TaskSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// User modifiable task configuration.
internal struct TaskSpec: Sendable, Content, Hashable {

    internal var pluginSpec: TaskSpecPluginSpec?
    internal var containerSpec: TaskSpecContainerSpec?
    internal var networkAttachmentSpec: TaskSpecNetworkAttachmentSpec?
    internal var resources: TaskSpecResources?
    internal var restartPolicy: TaskSpecRestartPolicy?
    internal var placement: TaskSpecPlacement?
    /** A counter that triggers an update even if no relevant parameters have been changed.  */
    internal var forceUpdate: Int?
    /** Runtime is the type of runtime specified for the task executor.  */
    internal var runtime: String?
    /** Specifies which networks the service should attach to. */
    internal var networks: [NetworkAttachmentConfig]?
    internal var logDriver: TaskSpecLogDriver?

    internal init(
        pluginSpec: TaskSpecPluginSpec? = nil, containerSpec: TaskSpecContainerSpec? = nil, networkAttachmentSpec: TaskSpecNetworkAttachmentSpec? = nil,
        resources: TaskSpecResources? = nil, restartPolicy: TaskSpecRestartPolicy? = nil, placement: TaskSpecPlacement? = nil, forceUpdate: Int? = nil, runtime: String? = nil,
        networks: [NetworkAttachmentConfig]? = nil, logDriver: TaskSpecLogDriver? = nil
    ) {
        self.pluginSpec = pluginSpec
        self.containerSpec = containerSpec
        self.networkAttachmentSpec = networkAttachmentSpec
        self.resources = resources
        self.restartPolicy = restartPolicy
        self.placement = placement
        self.forceUpdate = forceUpdate
        self.runtime = runtime
        self.networks = networks
        self.logDriver = logDriver
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case pluginSpec = "PluginSpec"
        case containerSpec = "ContainerSpec"
        case networkAttachmentSpec = "NetworkAttachmentSpec"
        case resources = "Resources"
        case restartPolicy = "RestartPolicy"
        case placement = "Placement"
        case forceUpdate = "ForceUpdate"
        case runtime = "Runtime"
        case networks = "Networks"
        case logDriver = "LogDriver"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(pluginSpec, forKey: .pluginSpec)
        try keyedContainer.encodeIfPresent(containerSpec, forKey: .containerSpec)
        try keyedContainer.encodeIfPresent(networkAttachmentSpec, forKey: .networkAttachmentSpec)
        try keyedContainer.encodeIfPresent(resources, forKey: .resources)
        try keyedContainer.encodeIfPresent(restartPolicy, forKey: .restartPolicy)
        try keyedContainer.encodeIfPresent(placement, forKey: .placement)
        try keyedContainer.encodeIfPresent(forceUpdate, forKey: .forceUpdate)
        try keyedContainer.encodeIfPresent(runtime, forKey: .runtime)
        try keyedContainer.encodeIfPresent(networks, forKey: .networks)
        try keyedContainer.encodeIfPresent(logDriver, forKey: .logDriver)
    }
}
