//
// TaskSpecContainerSpecConfigsInnerFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// File represents a specific target that is backed by a file.  &lt;p&gt;&lt;br /&gt;&lt;p&gt;  &gt; **Note**: &#x60;Configs.File&#x60; and &#x60;Configs.Runtime&#x60; are mutually exclusive
internal struct TaskSpecContainerSpecConfigsInnerFile: Sendable, Content, Hashable {

    /** Name represents the final filename in the filesystem.  */
    internal var name: String?
    /** UID represents the file UID. */
    internal var UID: String?
    /** GID represents the file GID. */
    internal var GID: String?
    /** Mode represents the FileMode of the file. */
    internal var mode: Int?

    internal init(name: String? = nil, UID: String? = nil, GID: String? = nil, mode: Int? = nil) {
        self.name = name
        self.UID = UID
        self.GID = GID
        self.mode = mode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case UID
        case GID
        case mode = "Mode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(UID, forKey: .UID)
        try keyedContainer.encodeIfPresent(GID, forKey: .GID)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
    }
}
