//
// TaskSpecPluginSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Plugin spec for the service.  *(Experimental release only.)*  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are &gt; mutually exclusive. PluginSpec is only used when the Runtime field &gt; is set to &#x60;plugin&#x60;. NetworkAttachmentSpec is used when the Runtime &gt; field is set to &#x60;attachment&#x60;.
internal struct TaskSpecPluginSpec: Sendable, Content, Hashable {

    /** The name or 'alias' to use for the plugin. */
    internal var name: String?
    /** The plugin image reference to use. */
    internal var remote: String?
    /** Disable the plugin once scheduled. */
    internal var disabled: Bool?
    internal var pluginPrivilege: [PluginPrivilege]?

    internal init(name: String? = nil, remote: String? = nil, disabled: Bool? = nil, pluginPrivilege: [PluginPrivilege]? = nil) {
        self.name = name
        self.remote = remote
        self.disabled = disabled
        self.pluginPrivilege = pluginPrivilege
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case remote = "Remote"
        case disabled = "Disabled"
        case pluginPrivilege = "PluginPrivilege"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(remote, forKey: .remote)
        try keyedContainer.encodeIfPresent(disabled, forKey: .disabled)
        try keyedContainer.encodeIfPresent(pluginPrivilege, forKey: .pluginPrivilege)
    }
}
