//
// TaskSpecContainerSpecPrivilegesAppArmor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Options for configuring AppArmor on the container
internal struct TaskSpecContainerSpecPrivilegesAppArmor: Sendable, Content, Hashable {

    internal enum Mode: String, Sendable, Content, Hashable, CaseIterable {
        case `default` = "default"
        case disabled = "disabled"
    }
    internal var mode: Mode?

    internal init(mode: Mode? = nil) {
        self.mode = mode
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mode = "Mode"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(mode, forKey: .mode)
    }
}
