//
// TaskSpecNetworkAttachmentSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Read-only spec type for non-swarm containers attached to swarm overlay networks.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are &gt; mutually exclusive. PluginSpec is only used when the Runtime field &gt; is set to &#x60;plugin&#x60;. NetworkAttachmentSpec is used when the Runtime &gt; field is set to &#x60;attachment&#x60;.
internal struct TaskSpecNetworkAttachmentSpec: Sendable, Content, Hashable {

    /** ID of the container represented by this task */
    internal var containerID: String?

    internal init(containerID: String? = nil) {
        self.containerID = containerID
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case containerID = "ContainerID"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(containerID, forKey: .containerID)
    }
}
