//
// ThrottleDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct ThrottleDevice: Sendable, Content, Hashable {

    /** Device path */
    internal var path: String?
    /** Rate */
    internal var rate: Int64?

    internal init(path: String? = nil, rate: Int64? = nil) {
        self.path = path
        self.rate = rate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case rate = "Rate"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(path, forKey: .path)
        try keyedContainer.encodeIfPresent(rate, forKey: .rate)
    }
}
