//
// TLSInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Information about the issuer of leaf TLS certificates and the trusted root CA certificate.
internal struct TLSInfo: Sendable, Content, Hashable {

    /** The root CA certificate(s) that are used to validate leaf TLS certificates.  */
    internal var trustRoot: String?
    /** The base64-url-safe-encoded raw subject bytes of the issuer. */
    internal var certIssuerSubject: String?
    /** The base64-url-safe-encoded raw public key bytes of the issuer.  */
    internal var certIssuerPublicKey: String?

    internal init(trustRoot: String? = nil, certIssuerSubject: String? = nil, certIssuerPublicKey: String? = nil) {
        self.trustRoot = trustRoot
        self.certIssuerSubject = certIssuerSubject
        self.certIssuerPublicKey = certIssuerPublicKey
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case trustRoot = "TrustRoot"
        case certIssuerSubject = "CertIssuerSubject"
        case certIssuerPublicKey = "CertIssuerPublicKey"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(trustRoot, forKey: .trustRoot)
        try keyedContainer.encodeIfPresent(certIssuerSubject, forKey: .certIssuerSubject)
        try keyedContainer.encodeIfPresent(certIssuerPublicKey, forKey: .certIssuerPublicKey)
    }
}
