//
// Topology.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// A map of topological domains to topological segments. For in depth details, see documentation for the Topology object in the CSI specification.
internal struct Topology: Sendable, Content, Hashable {

    internal var segments: [String: String]?

    internal init(segments: [String: String]? = nil) {
        self.segments = segments
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case segments = "Segments"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(segments, forKey: .segments)
    }
}
