//
// VolumePruneResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct VolumePruneResponse: Sendable, Content, Hashable {

    /** Volumes that were deleted */
    internal var volumesDeleted: [String]?
    /** Disk space reclaimed in bytes */
    internal var spaceReclaimed: Int64?

    internal init(volumesDeleted: [String]? = nil, spaceReclaimed: Int64? = nil) {
        self.volumesDeleted = volumesDeleted
        self.spaceReclaimed = spaceReclaimed
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case volumesDeleted = "VolumesDeleted"
        case spaceReclaimed = "SpaceReclaimed"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(volumesDeleted, forKey: .volumesDeleted)
        try keyedContainer.encodeIfPresent(spaceReclaimed, forKey: .spaceReclaimed)
    }
}
