//
// VolumeUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Volume configuration
internal struct VolumeUpdateRequest: Sendable, Content, Hashable {

    internal var spec: ClusterVolumeSpec?

    internal init(spec: ClusterVolumeSpec? = nil) {
        self.spec = spec
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case spec = "Spec"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(spec, forKey: .spec)
    }
}
