//
// Volume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

internal struct Volume: Sendable, Content, Hashable {

    internal enum Scope: String, Sendable, Content, Hashable, CaseIterable {
        case local = "local"
        case global = "global"
    }
    /** Name of the volume. */
    internal var name: String
    /** Name of the volume driver used by the volume. */
    internal var driver: String
    /** Mount path of the volume on the host. */
    internal var mountpoint: String
    /** Date/Time the volume was created. */
    internal var createdAt: String?
    /** Low-level details about the volume, provided by the volume driver. Details are returned as a map with key/value pairs: `{\"key\":\"value\",\"key2\":\"value2\"}`.  The `Status` field is optional, and is omitted if the volume driver does not support this feature.  */
    internal var status: [String: JSONValue]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]
    /** The level at which the volume exists. Either `global` for cluster-wide, or `local` for machine level.  */
    internal var scope: Scope = .local
    internal var clusterVolume: ClusterVolume?
    /** The driver specific options used when creating the volume.  */
    internal var options: [String: String]
    internal var usageData: VolumeUsageData?

    internal init(
        name: String, driver: String, mountpoint: String, createdAt: String? = nil, status: [String: JSONValue]? = nil, labels: [String: String], scope: Scope = .local,
        clusterVolume: ClusterVolume? = nil, options: [String: String], usageData: VolumeUsageData? = nil
    ) {
        self.name = name
        self.driver = driver
        self.mountpoint = mountpoint
        self.createdAt = createdAt
        self.status = status
        self.labels = labels
        self.scope = scope
        self.clusterVolume = clusterVolume
        self.options = options
        self.usageData = usageData
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case driver = "Driver"
        case mountpoint = "Mountpoint"
        case createdAt = "CreatedAt"
        case status = "Status"
        case labels = "Labels"
        case scope = "Scope"
        case clusterVolume = "ClusterVolume"
        case options = "Options"
        case usageData = "UsageData"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encode(name, forKey: .name)
        try keyedContainer.encode(driver, forKey: .driver)
        try keyedContainer.encode(mountpoint, forKey: .mountpoint)
        try keyedContainer.encodeIfPresent(createdAt, forKey: .createdAt)
        try keyedContainer.encodeIfPresent(status, forKey: .status)
        try keyedContainer.encode(labels, forKey: .labels)
        try keyedContainer.encode(scope, forKey: .scope)
        try keyedContainer.encodeIfPresent(clusterVolume, forKey: .clusterVolume)
        try keyedContainer.encode(options, forKey: .options)
        try keyedContainer.encodeIfPresent(usageData, forKey: .usageData)
    }
}
