//
// VolumeCreateOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Volume configuration
internal struct VolumeCreateOptions: Sendable, Content, Hashable {

    /** The new volume's name. If not specified, Docker generates a name.  */
    internal var name: String?
    /** Name of the volume driver to use. */
    internal var driver: String? = "local"
    /** A mapping of driver options and values. These options are passed directly to the driver and are driver specific.  */
    internal var driverOpts: [String: String]?
    /** User-defined key/value metadata. */
    internal var labels: [String: String]?
    internal var clusterVolumeSpec: ClusterVolumeSpec?

    internal init(name: String? = nil, driver: String? = "local", driverOpts: [String: String]? = nil, labels: [String: String]? = nil, clusterVolumeSpec: ClusterVolumeSpec? = nil)
    {
        self.name = name
        self.driver = driver
        self.driverOpts = driverOpts
        self.labels = labels
        self.clusterVolumeSpec = clusterVolumeSpec
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case driver = "Driver"
        case driverOpts = "DriverOpts"
        case labels = "Labels"
        case clusterVolumeSpec = "ClusterVolumeSpec"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(name, forKey: .name)
        try keyedContainer.encodeIfPresent(driver, forKey: .driver)
        try keyedContainer.encodeIfPresent(driverOpts, forKey: .driverOpts)
        try keyedContainer.encodeIfPresent(labels, forKey: .labels)
        try keyedContainer.encodeIfPresent(clusterVolumeSpec, forKey: .clusterVolumeSpec)
    }
}
