//
// VolumeListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/// Volume list response
internal struct VolumeListResponse: Sendable, Content, Hashable {

    /** List of volumes */
    internal var volumes: [Volume]?
    /** Warnings that occurred when fetching the list of volumes.  */
    internal var warnings: [String]?

    internal init(volumes: [Volume]? = nil, warnings: [String]? = nil) {
        self.volumes = volumes
        self.warnings = warnings
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case volumes = "Volumes"
        case warnings = "Warnings"
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var keyedContainer = encoder.container(keyedBy: CodingKeys.self)
        try keyedContainer.encodeIfPresent(volumes, forKey: .volumes)
        try keyedContainer.encodeIfPresent(warnings, forKey: .warnings)
    }
}
